var makefile =
{
    "Config": {
        "PROJECT_NAME": "Coconut2D",
        "PROJECT_DISPLAY_NAME": "Coconut2D",
        "PROJECT_PACKAGE": "com.mobilefx.Coconut2D",
        "PROJECT_VERSION": "1.0.0",
        "PROJECT_VERSION_SHORT": "1.0",
        "PROJECT_FRAMEWORKS": "org.coconut2d.sdk.html5;org.coconut2d.sdk.webgl;org.coconut2d.sdk.system;org.coconut2d.sdk.anim;org.coconut2d.sdk.net;org.coconut2d.sdk.ui;org.coconut2d.sdk.tests",
        "CONFIGURATION": "Debug",
        "DEBUG_HOST_IP": "192.168.1.168",
        "DEBUG_HOST_PORT": "9999",
        "TAGS": {
            "OG_COMPANY_ADDRESS": "52 Electras str",
            "OG_COMPANY_COUNTRY": "Greece",
            "OG_COMPANY_EMAIL": "info@mobilefx.com",
            "OG_COMPANY_NAME": "mobileFX",
            "OG_COMPANY_PHONE": "+302109522504",
            "OG_COMPANY_POSTCODE": "17673",
            "OG_COMPANY_REGION": "N. Attikis",
            "OG_COPYRIGHT": "Copyright (C) 2014 mobileFX, All Rights Reserved",
            "OG_CURRENCY": "Eur",
            "OG_DEMO_VIDEO_HEIGHT": "385",
            "OG_DEMO_VIDEO_URL": "http://www.youtube.com/mobileFX",
            "OG_DEMO_VIDEO_WIDTH": "640",
            "OG_DESCRIPTION": "mobileFX presents Coconut2D",
            "OG_PRICE": "Free",
            "OG_PUBLISHER": "mobileFX",
            "OG_TITLE": "Coconut2D",
            "OG_HOST": "http://www.mobilefx.com/games",
            "OG_URL": "http://www.mobilefx.com/games/Coconut2D.html"
        },
        "PROJECT_PATHS": {
            "TARGETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets",
            "SDK": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK",
            "SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src",
            "NATIVE_COMMON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/_Common",
            "SOURCES_MASK": "*.jspp",
            "ANIMATION_SCRIPTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src/animations",
            "ICON_2048x2048": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/icon.png",
            "ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets",
            "ASSETS_ANIMATIONS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/animations",
            "ASSETS_FONTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/fonts",
            "ASSETS_IMAGES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/images",
            "ASSETS_SOUNDS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/sounds",
            "ASSETS_VIDEOS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/videos"
        },
        "DEVICE_VIEWPORT": {
            "VIEW_WIDTH": 320,
            "VIEW_HEIGHT": 480,
            "VIEW_PIXEL_RATIO": 1
        },
        "TARGETS": {
            "CocoPlayer": {
                "TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer",
                "TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj",
                "TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
                "TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/main.js",
                "TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
                "TARGET_EXPORT": "all",
                "TARGET_ADDITIONAL_FRAMEWORKS": null,
                "TARGET_FILTER": "",
                "TARGET_ADDITIONAL_NATIVE_SOURCES": null,
                "TARGET_NATIVE_MASK": null,
                "TARGET_RESOURCES_MASK": null,
                "RELOAD_AFTER_BUILD": true,
                "DEVICE_WRAPPER": {
                    "CLASS": "COCO_PLAYER",
                    "PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/web/CocoPlayer",
                    "TEMPLATES": null,
                    "TEMPLATE_EXCLUDE_VARS": null
                },
                "DEVICES": {
                    "CocoPlayer": {
                        "Debugger": "Debugger_V8Local",
                        "Debug": "CocoPlayer",
                        "Release": "CocoPlayer"
                    }
                },
                "APP_SETTINGS": {}
            }
        }
    },
    "Vars": {
        "APP_PATH": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio",
        "USERPROFILE": "C:/Users/admin",
        "TARGET": "CocoPlayer",
        "TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer",
        "TARGET_DEVICE": "CocoPlayer",
        "CHROME_DEBUG_PORT": "9999",
        "TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/main.js",
        "SURFACE_WIDTH": "320",
        "SURFACE_HEIGHT": "480",
        "LOCALHOST_IP": "192.168.1.168",
        "PROJECT_NAME": "Coconut2D",
        "PROJECT_DISPLAY_NAME": "Coconut2D",
        "PROJECT_PACKAGE": "com.mobilefx.Coconut2D",
        "PROJECT_VERSION": "1.0.0",
        "PROJECT_VERSION_SHORT": "1.0",
        "PROJECT_FRAMEWORKS": "org.coconut2d.sdk.html5;org.coconut2d.sdk.webgl;org.coconut2d.sdk.system;org.coconut2d.sdk.anim;org.coconut2d.sdk.net;org.coconut2d.sdk.ui;org.coconut2d.sdk.tests",
        "CONFIGURATION": "Debug",
        "DEBUG_HOST_IP": "192.168.1.168",
        "DEBUG_HOST_PORT": "9999",
        "TAGS.OG_COMPANY_ADDRESS": "52 Electras str",
        "TAGS.OG_COMPANY_COUNTRY": "Greece",
        "TAGS.OG_COMPANY_EMAIL": "info@mobilefx.com",
        "TAGS.OG_COMPANY_NAME": "mobileFX",
        "TAGS.OG_COMPANY_PHONE": "+302109522504",
        "TAGS.OG_COMPANY_POSTCODE": "17673",
        "TAGS.OG_COMPANY_REGION": "N. Attikis",
        "TAGS.OG_COPYRIGHT": "Copyright (C) 2014 mobileFX, All Rights Reserved",
        "TAGS.OG_CURRENCY": "Eur",
        "TAGS.OG_DEMO_VIDEO_HEIGHT": "385",
        "TAGS.OG_DEMO_VIDEO_URL": "http://www.youtube.com/mobileFX",
        "TAGS.OG_DEMO_VIDEO_WIDTH": "640",
        "TAGS.OG_DESCRIPTION": "mobileFX presents Coconut2D",
        "TAGS.OG_PRICE": "Free",
        "TAGS.OG_PUBLISHER": "mobileFX",
        "TAGS.OG_TITLE": "Coconut2D",
        "TAGS.OG_HOST": "http://www.mobilefx.com/games",
        "TAGS.OG_URL": "http://www.mobilefx.com/games/Coconut2D.html",
        "PROJECT_PATHS.TARGETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets",
        "PROJECT_PATHS.SDK": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK",
        "PROJECT_PATHS.SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src",
        "PROJECT_PATHS.NATIVE_COMMON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/_Common",
        "PROJECT_PATHS.SOURCES_MASK": "*.jspp",
        "PROJECT_PATHS.ANIMATION_SCRIPTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src/animations",
        "PROJECT_PATHS.ICON_2048x2048": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/icon.png",
        "PROJECT_PATHS.ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets",
        "PROJECT_PATHS.ASSETS_ANIMATIONS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/animations",
        "PROJECT_PATHS.ASSETS_FONTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/fonts",
        "PROJECT_PATHS.ASSETS_IMAGES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/images",
        "PROJECT_PATHS.ASSETS_SOUNDS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/sounds",
        "PROJECT_PATHS.ASSETS_VIDEOS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/videos",
        "DEVICE_VIEWPORT.VIEW_WIDTH": "320",
        "DEVICE_VIEWPORT.VIEW_HEIGHT": "480",
        "DEVICE_VIEWPORT.VIEW_PIXEL_RATIO": "1",
        "TARGETS.CocoPlayer.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer",
        "TARGETS.CocoPlayer.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj",
        "TARGETS.CocoPlayer.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.CocoPlayer.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/main.js",
        "TARGETS.CocoPlayer.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.CocoPlayer.TARGET_EXPORT": "all",
        "TARGETS.CocoPlayer.TARGET_FILTER": "",
        "TARGETS.CocoPlayer.RELOAD_AFTER_BUILD": "true",
        "TARGETS.CocoPlayer.DEVICE_WRAPPER.CLASS": "COCO_PLAYER",
        "TARGETS.CocoPlayer.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/web/CocoPlayer",
        "TARGETS.CocoPlayer.DEVICES.CocoPlayer.Debugger": "Debugger_V8Local",
        "TARGETS.CocoPlayer.DEVICES.CocoPlayer.Debug": "CocoPlayer",
        "TARGETS.CocoPlayer.DEVICES.CocoPlayer.Release": "CocoPlayer",
        "TARGETS.HTML5.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/HTML5",
        "TARGETS.HTML5.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj",
        "TARGETS.HTML5.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.HTML5.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/index.html",
        "TARGETS.HTML5.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.HTML5.TARGET_EXPORT": "web",
        "TARGETS.HTML5.RELOAD_AFTER_BUILD": "true",
        "TARGETS.HTML5.DEVICE_WRAPPER.CLASS": "HTML5_BROWSER",
        "TARGETS.HTML5.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/web/CocoPlayer",
        "TARGETS.HTML5.DEVICE_WRAPPER.TEMPLATES": "*.html;*.css",
        "TARGETS.HTML5.DEVICES.Chrome.Debug": "<C:/Program Files (x86)/Google/Chrome/Application/chrome.exe> --app",
        "TARGETS.HTML5.DEVICES.Chrome.Release": "<C:/Program Files (x86)/Google/Chrome/Application/chrome.exe> --app",
        "TARGETS.HTML5.DEVICES.FireFox.Debug": "<C:/Program Files (x86)/Mozilla Firefox/firefox.exe> -jsconsole -url <file:///D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/main.js>",
        "TARGETS.HTML5.DEVICES.FireFox.Release": "<C:/Program Files (x86)/Mozilla Firefox/firefox.exe> -url <file:///D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/main.js>",
        "TARGETS.HTML5.APP_ICONS.16": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/favicon.ico",
        "TARGETS.HTML5.APP_ICONS.72": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/apple-touch-icon-72x72.png",
        "TARGETS.HTML5.APP_ICONS.76": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/apple-touch-icon-76x76.png",
        "TARGETS.HTML5.APP_ICONS.114": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/apple-touch-icon-114x114.png",
        "TARGETS.HTML5.APP_ICONS.120": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/apple-touch-icon-120x120.png",
        "TARGETS.HTML5.APP_ICONS.144": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/apple-touch-icon-144x144.png",
        "TARGETS.HTML5.APP_ICONS.152": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/apple-touch-icon-152x152.png",
        "TARGETS.Android.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Android",
        "TARGETS.Android.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj",
        "TARGETS.Android.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.Android.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin/Coconut2D.apk",
        "TARGETS.Android.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.Android.TARGET_EXPORT": "native",
        "TARGETS.Android.TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/jni/src",
        "TARGETS.Android.TARGET_NATIVE_MASK": "*.cpp;*.hpp;*.h",
        "TARGETS.Android.TARGET_RESOURCES_MASK": "*.png;*.jpeg;*.ogg;*.ttf",
        "TARGETS.Android.RELOAD_AFTER_BUILD": "true",
        "TARGETS.Android.DEVICE_WRAPPER.CLASS": "ANDROID",
        "TARGETS.Android.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/CocoPlayer",
        "TARGETS.Android.DEVICE_WRAPPER.TEMPLATES": "*.xml;*.properties;*.java;*.cpp",
        "TARGETS.Android.DEVICES['Android (x86)'].Debugger": "Debugger_GDB",
        "TARGETS.Android.DEVICES['Android (x86)'].Debug": "DeviceBridge",
        "TARGETS.Android.DEVICES['Android (x86)'].Release": "DeviceBridge",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).DEVICE_TYPE_FILTER": "ANDROID",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).Debugger": "Debugger_GDB",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).Debug": "DeviceBridge",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).Release": "DeviceBridge",
        "TARGETS.Android.APP_SETTINGS.ANDROID_PLATFORM": "android-10",
        "TARGETS.Android.APP_SETTINGS.MIN_SDK_VERSION": "10",
        "TARGETS.Android.APP_SETTINGS.TARGET_SDK_VERSION": "19",
        "TARGETS.Android.APP_SETTINGS.SCREEN_ORIENTATION": "landscape",
        "TARGETS.Android.APP_ICONS.48": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/res/drawable-mdpi/ic_launcher.png",
        "TARGETS.Android.APP_ICONS.72": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/res/drawable-hdpi/ic_launcher.png",
        "TARGETS.Android.APP_ICONS.96": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/res/drawable-xhdpi/ic_launcher.png",
        "TARGETS.Android.APP_ICONS.144": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/res/drawable-xxhdpi/ic_launcher.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/res/drawable/ic_launcher.png",
        "TARGETS.Android.CODE_SIGNING.COMPANY": "mobileFX",
        "TARGETS.Android.CODE_SIGNING.ORGANIZATION": "mobileFX",
        "TARGETS.Android.CODE_SIGNING.COUNTRY": "US",
        "TARGETS.Android.CODE_SIGNING.PASSWORD": "password",
        "TARGETS.iOS.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/iOS",
        "TARGETS.iOS.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj",
        "TARGETS.iOS.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.iOS.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin/Coconut2D.ipa",
        "TARGETS.iOS.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.iOS.TARGET_EXPORT": "native",
        "TARGETS.iOS.TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/src",
        "TARGETS.iOS.TARGET_NATIVE_MASK": "*.m;*.cpp;*.hpp;*.h",
        "TARGETS.iOS.TARGET_RESOURCES_MASK": "*.plist;*.png;*.jpeg;*.ogg;*.ttf",
        "TARGETS.iOS.RELOAD_AFTER_BUILD": "true",
        "TARGETS.iOS.DEVICE_WRAPPER.CLASS": "IOS",
        "TARGETS.iOS.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/CocoPlayer",
        "TARGETS.iOS.DEVICE_WRAPPER.TEMPLATES": "*.m;*.plist",
        "TARGETS.iOS.DEVICE_WRAPPER.TEMPLATE_EXCLUDE_VARS": "IOSBUILDENV_PATH;PAYLOAD;NAME;CPUSET;IOSMINVER;SRC;OBJDIR;OBJ;OUTDIR;BIN;RES;CFLAGS;LDFLAGS;OBJ_OBJ;PROVISION;CERTIFICATES;PRIVATE_KEY;PASSPHRASE",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).DEVICE_TYPE_FILTER": "IOS",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).Debugger": "Debugger_LLDB",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).Debug": "DeviceBridge",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).Release": "DeviceBridge",
        "TARGETS.iOS.APP_SETTINGS.IOSMINVER": "5",
        "TARGETS.iOS.APP_SETTINGS.CPUSET": "armv7",
        "TARGETS.iOS.APP_SETTINGS.CFBundleIdentifier": "com.mobilefx.Coconut2D",
        "TARGETS.iOS.APP_SETTINGS.UIStatusBarHidden": "true",
        "TARGETS.iOS.APP_SETTINGS.UIStatusBarStyle": "UIStatusBarStyleBlackTranslucent",
        "TARGETS.iOS.APP_SETTINGS.UIViewControllerBasedStatusBarAppearance": "true",
        "TARGETS.iOS.APP_SETTINGS.UIViewEdgeAntialiasing": "false",
        "TARGETS.iOS.APP_SETTINGS.UIApplicationExitsOnSuspend": "true",
        "TARGETS.iOS.APP_SETTINGS.UIInterfaceOrientation": "UIInterfaceOrientationPortrait",
        "TARGETS.iOS.APP_SETTINGS.UIInterfaceOrientation_iPad": "UIInterfaceOrientationPortrait",
        "TARGETS.iOS.APP_SETTINGS.UIPrerenderedIcon": "true",
        "TARGETS.iOS.APP_ICONS.29": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-29.png",
        "TARGETS.iOS.APP_ICONS.40": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-40.png",
        "TARGETS.iOS.APP_ICONS.48": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-48.png",
        "TARGETS.iOS.APP_ICONS.50": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-50.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-Small-50.png",
        "TARGETS.iOS.APP_ICONS.57": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-57.png",
        "TARGETS.iOS.APP_ICONS.58": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-29@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-58.png",
        "TARGETS.iOS.APP_ICONS.60": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-60.png",
        "TARGETS.iOS.APP_ICONS.72": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-72.png",
        "TARGETS.iOS.APP_ICONS.76": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-76.png",
        "TARGETS.iOS.APP_ICONS.80": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-40@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-80.png",
        "TARGETS.iOS.APP_ICONS.96": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-48@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-96.png",
        "TARGETS.iOS.APP_ICONS.100": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-Small-50@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-100.png",
        "TARGETS.iOS.APP_ICONS.114": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-57@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-114.png",
        "TARGETS.iOS.APP_ICONS.120": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-60@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-120.png",
        "TARGETS.iOS.APP_ICONS.144": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-72@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-144.png",
        "TARGETS.iOS.APP_ICONS.152": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-76@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Icon-152.png",
        "TARGETS.iOS.APP_ICONS.512": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/iTunesArtwork.png",
        "TARGETS.iOS.APP_ICONS.1024": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/iTunesArtwork@2x.png",
        "TARGETS.iOS.CODE_SIGNING.IOS_CERTIFICATES": "ios_development.cer:AppleIncRootCertificate.cer:AppleWWDRCA.cer",
        "TARGETS.iOS.CODE_SIGNING.IOS_PRIVATE_KEY": "ios_development.key",
        "TARGETS.iOS.CODE_SIGNING.IOS_PRIVATE_KEY_PASSPHRASE": "puerre",
        "TARGETS.iOS.CODE_SIGNING.IOS_PROVISION": "mobileFX.mobileprovision",
        "TARGETS.Win32.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32",
        "TARGETS.Win32.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj",
        "TARGETS.Win32.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.Win32.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Coconut2D.exe",
        "TARGETS.Win32.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/Coconut2D.exe;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/assets",
        "TARGETS.Win32.TARGET_EXPORT": "native",
        "TARGETS.Win32.TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/src",
        "TARGETS.Win32.TARGET_NATIVE_MASK": "*.cpp;*.hpp;*.h",
        "TARGETS.Win32.TARGET_RESOURCES_MASK": "*.png;*.jpeg;*.ogg;*.ttf",
        "TARGETS.Win32.RELOAD_AFTER_BUILD": "true",
        "TARGETS.Win32.DEVICE_WRAPPER.CLASS": "WIN32",
        "TARGETS.Win32.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/CocoPlayer",
        "TARGETS.Win32.DEVICE_WRAPPER.TEMPLATES": "resource.h;debugger-config.gdb;*.cpp",
        "TARGETS.Win32.DEVICE_WRAPPER.TEMPLATE_EXCLUDE_VARS": "SRC;BIN;OUT;OBJS;CC;LDFLAGS;CFLAGS;RC;OBJ;OBJ_OBJ;LDLIBS",
        "TARGETS.Win32.DEVICES['Windows (x86)'].Debugger": "Debugger_GDB",
        "TARGETS.Win32.DEVICES['Windows (x86)'].Debug": "<D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW/bin/gdb.exe> -q -nw -r -f -x <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/debugger-config.gdb> -cd <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer> -d <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer>",
        "TARGETS.Win32.DEVICES['Windows (x86)'].Release": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/main.js",
        "TARGETS.Win32.APP_ICONS.32": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer/res/Application.ico",
        "TARGETS.Win32.CODE_SIGNING.IOS_CERTIFICATES": "ios_development.cer:AppleIncRootCertificate.cer:AppleWWDRCA.cer",
        "TARGETS.Win32.CODE_SIGNING.IOS_PRIVATE_KEY": "ios_development.key",
        "TARGETS.Win32.CODE_SIGNING.IOS_PRIVATE_KEY_PASSPHRASE": "puerre",
        "TARGETS.Win32.CODE_SIGNING.IOS_PROVISION": "Coconut2D.mobileprovision",
        "PATH_IDE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio",
        "PATH_3RD_PARTY": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party",
        "PATH_3RD_PARTY_MAKE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/make",
        "PATH_3RD_PARTY_CLOSURE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/closure",
        "PATH_3RD_PARTY_FFMPEG": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/ffmpeg",
        "PATH_3RD_PARTY_FIGLET": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/figlet",
        "PATH_3RD_PARTY_GIT": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/git",
        "PATH_3RD_PARTY_JSON": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/json",
        "PATH_3RD_PARTY_LIBMOBILEDEVICE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/libmobiledevice",
        "PATH_3RD_PARTY_ANT": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/ant",
        "PATH_3RD_PARTY_JAVA": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/java",
        "PATH_3RD_PARTY_WINDBG": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/WinDBG",
        "PATH_3RD_PARTY_MINGW": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW",
        "PATH_3RD_PARTY_GDB": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW/bin",
        "PATH_3RD_PARTY_EMSDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk",
        "PATH_3RD_PARTY_LLDB": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/LLDB",
        "PATH_3RD_PARTY_EMSCRIPTEN": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk/emscripten/1.12.0",
        "PATH_3RD_PARTY_LLVM": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk/clang/3.2_32bit",
        "PATH_3RD_PARTY_NODEJS": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk/node/0.10.17_32bit",
        "PATH_3RD_PARTY_PYTHON": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk/python/2.7.5.3_32bit",
        "PATH_3RD_PARTY_ANDROID_SDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/android-sdk",
        "PATH_3RD_PARTY_ANDROID_NDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/android-ndk",
        "PATH_3RD_PARTY_IOS_BUILD_ENV": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/iOS",
        "PATH_IDE_CONFIG": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config",
        "FILE_PATH_SETTINGS_DEFAULT": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config/settings.ini",
        "FILE_PATH_DEVICES_XML": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config/devices.xml",
        "FILE_PATH_DATABASE_TEMPLATE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config/project.db",
        "PATH_IDE_DOCS": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/docs",
        "PATH_IDE_ICONS": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/icons",
        "PATH_IDE_CODEMAX_LANGUAGES": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/languages",
        "FILE_PATH_SETTINGS_USER": "C:/Users/admin/Coconut2D/settings.ini",
        "PATH_SDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/.SDK",
        "FILE_PATH_SDK_FRAMEWORKS_REGISTRY": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/.SDK/Frameworks/Frameworks.json",
        "FILE_PATH_SDK_SHADERS_REGISTRY": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/.SDK/Shaders/shaders.json",
        "PATH_SDK_DEVICE_WRAPPERS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers",
        "PATH_SDK_COMMON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common",
        "PATH_SDK_INCLUDES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Includes",
        "PATH_SDK_LIBRARIES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Libraries",
        "PATH_SDK_FRAMEWORKS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks",
        "PATH_SDK_FRAMEWORKS_WEB": "web",
        "PATH_SDK_FRAMEWORKS_NATIVE": "native",
        "PATH_SDK_FRAMEWORKS_GEN": "gen",
        "PATH_SDK_FRAMEWORKS_SRC": "src",
        "PATH_SDK_FRAMEWORKS_LIB": "lib",
        "PATH_SDK_FRAMEWORKS_EMS": "ems",
        "PATH_SDK_TEMPLATES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates",
        "PATH_SDK_TEMPLATE_COCO_PROJECT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/Coco.Project",
        "FILE_PATH_TEMPLATE_PROJECT_JSON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/Coco.Project/project.json",
        "PATH_SDK_TEMPLATE_XCODE": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/XCode.Project",
        "PATH_SDK_TEMPLATE_MSVC2010": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/MSVC2010.Project",
        "PATH_SDK_TEMPLATE_ECLIPSE": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/Eclipse.Project",
        "PATH_SDK_TOOLCHAIN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Toolchain",
        "PATH_SDK_COMPILER": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Toolchain/Compiler",
        "PATH_SDK_DEBUGGER": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Toolchain/Debugger",
        "FILE_PATH_SDK_CRL_COCONUT2D_HPP": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common/Coconut2D.hpp",
        "PROJECT_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project",
        "ORG.COCONUT2D.SDK.HTML5": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.html5",
        "ORG.COCONUT2D.SDK.WEBGL": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.webgl",
        "ORG.COCONUT2D.SDK.SYSTEM": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.system",
        "ORG.COCONUT2D.SDK.ANIM": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.anim",
        "ORG.COCONUT2D.SDK.NET": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.net",
        "ORG.COCONUT2D.SDK.UI": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.ui",
        "ORG.EMSCRIPTEN.BOX2D": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.emscripten.box2d",
        "ORG.COCONUT2D.SDK.GAME2D": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d",
        "ORG.COCONUT2D.SDK.GAME2D.CASINO": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d.casino",
        "ORG.COCONUT2D.SDK.GAME2D.PHYSICS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d.physics",
        "ORG.COCONUT2D.SDK.GAME2D.PLATFORM": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d.platform",
        "ORG.COCONUT2D.SDK.GAME2D.PUZZLE": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d.puzzle",
        "ORG.COCONUT2D.SDK.GAME2D.TOWER": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d.tower",
        "ORG.COCONUT2D.SDK.TESTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.tests",
        "TEXT_FILES": "*.mk;*.asp;*.c;*.cc;*.cpp;*.css;*.csv;*.cxx;*.doc;*.gdl;*.h;*.hh;*.hpp;*.hta;*.htc;*.htm;*.html;*.inc;*.include;*.j;*.java;*.javascript;*.jspp;*.js;*.jscript;*.glsl;*.json;*.jx;*.log;*.m;*.makefile;*.mx;*.mxx;*.pbxproj;*.pch;*.plist;*.strings;*.txt;*.xhtml;*.xml;*.xsd;*.xslt;*.bat;*.cmd;*.ini;*.mm;*.settings;*.jobj;*.md;*.lst;*.properties;*.conf;*.gdb;*.gitignore"
    },
    "Components": {
        "Frameworks": {
            "org.coconut2d.sdk.html5": {
                "Name": "Coconut2D HTML5 Bindings Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_HTML5",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.html5",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.webgl": {
                "Name": "Coconut2D WebGL Bindings Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_WEBGL",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.webgl",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.system": {
                "Name": "Coconut2D Core System Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_APP",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.system",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.anim": {
                "Name": "Coconut2D Core Animation Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_ANIMATION",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.anim",
                "Description": "",
                "Dependencies": "",
                "FSM": true
            },
            "org.coconut2d.sdk.net": {
                "Name": "Coconut2D Core Network Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_NET",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.net",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.ui": {
                "Name": "Coconut2D Core Application Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_APPLICATION",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.ui",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.anim",
                "FSM": true
            },
            "org.emscripten.box2d": {
                "Name": "Box2D Physics Engine",
                "Version": "2.1",
                "Type": "Emscripten Library",
                "Copyright": "Copyright (c) 2006-2010 Erin Catto - http://www.gphysics.com",
                "License": "zlib license + acknowledgement",
                "PrecompilerVarName": "EMS_BOX2D",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.emscripten.box2d",
                "Description": "Box2D is an open source C++ engine for simulating rigid bodies in 2D. Box2D is developed by Erin Catto and has the zlib license. While the zlib license does not require acknowledgement, we encourage you to give credit to Box2D in your product.",
                "Dependencies": "org.coconut2d.sdk.anim",
                "Include": "Box2D/Box2D.h",
                "FSM": false
            },
            "org.coconut2d.sdk.game2d": {
                "Name": "Coconut2D Core 2D Game Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_GAME2D",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.anim",
                "FSM": true
            },
            "org.coconut2d.sdk.game2d.casino": {
                "Name": "Coconut2D Core Casino Games Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "Private",
                "PrecompilerVarName": "COCONUT2D_GAME_CASINO",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d.casino",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.game2d",
                "FSM": true
            },
            "org.coconut2d.sdk.game2d.physics": {
                "Name": "Coconut2D Core 2D Physics Games Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "Private",
                "PrecompilerVarName": "COCONUT2D_GAME_PHYSICS",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d.physics",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.game2d",
                "FSM": true
            },
            "org.coconut2d.sdk.game2d.platform": {
                "Name": "Coconut2D Core Platform Games Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "Private",
                "PrecompilerVarName": "COCONUT2D_GAME_PLATFORM",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d.platform",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.game2d",
                "FSM": true
            },
            "org.coconut2d.sdk.game2d.puzzle": {
                "Name": "Coconut2D Core Puzzle Games Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "Private",
                "PrecompilerVarName": "COCONUT2D_GAME_PUZZLE",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d.puzzle",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.game2d",
                "FSM": true
            },
            "org.coconut2d.sdk.game2d.tower": {
                "Name": "Coconut2D Core Tower Defence Games Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "Private",
                "PrecompilerVarName": "COCONUT2D_GAME_TOWER_DEFENCE",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d.tower",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.game2d",
                "FSM": true
            },
            "org.coconut2d.sdk.tests": {
                "Name": "Coconut2D Tests Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_ANIMATION",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.tests",
                "Description": "",
                "Dependencies": "",
                "FSM": true
            }
        }
    }
};