var makefile =
{
    "Config": {
        "PROJECT_NAME": "Coconut2D",
        "PROJECT_DISPLAY_NAME": "Coconut2D",
        "PROJECT_PACKAGE": "com.mobilefx.Coconut2D",
        "PROJECT_VERSION": "1.0.0",
        "PROJECT_VERSION_SHORT": "1.0",
        "PROJECT_FRAMEWORKS": "org.coconut2d.sdk.html5;org.coconut2d.sdk.webgl;org.coconut2d.sdk.anim;org.coconut2d.sdk.net;org.coconut2d.sdk.ui",
        "CONFIGURATION": "Debug",
        "DEBUG_HOST_IP": "192.168.1.108",
        "DEBUG_HOST_PORT": "9999",
        "TAGS": {
            "OG_COMPANY_ADDRESS": "52 Electras str",
            "OG_COMPANY_COUNTRY": "Greece",
            "OG_COMPANY_EMAIL": "info@mobilefx.com",
            "OG_COMPANY_NAME": "mobileFX",
            "OG_COMPANY_PHONE": "+302109522504",
            "OG_COMPANY_POSTCODE": "17673",
            "OG_COMPANY_REGION": "N. Attikis",
            "OG_COPYRIGHT": "Copyright (C) 2014 mobileFX, All Rights Reserved",
            "OG_CURRENCY": "Eur",
            "OG_DEMO_VIDEO_HEIGHT": "385",
            "OG_DEMO_VIDEO_URL": "http://www.youtube.com/mobileFX",
            "OG_DEMO_VIDEO_WIDTH": "640",
            "OG_DESCRIPTION": "mobileFX presents Coconut2D",
            "OG_PRICE": "Free",
            "OG_PUBLISHER": "mobileFX",
            "OG_TITLE": "Coconut2D",
            "OG_HOST": "http://www.mobilefx.com/games",
            "OG_URL": "http://www.mobilefx.com/games/Coconut2D.html"
        },
        "PROJECT_PATHS": {
            "TARGETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets",
            "SDK": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK",
            "SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src",
            "NATIVE_COMMON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/_Common",
            "SOURCES_MASK": "*.jspp",
            "ANIMATION_SCRIPTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src/animations",
            "ICON_2048x2048": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/icon.png",
            "ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets",
            "ASSETS_ANIMATIONS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/animations",
            "ASSETS_FONTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/fonts",
            "ASSETS_IMAGES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/images",
            "ASSETS_SOUNDS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/sounds",
            "ASSETS_VIDEOS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/videos"
        },
        "DEVICE_VIEWPORT": {
            "VIEW_WIDTH": "480",
            "VIEW_HEIGHT": "320",
            "VIEW_PIXEL_RATIO": "1"
        },
        "TARGETS": {
            "Win32": {
                "TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32",
                "TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj",
                "TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
                "TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe",
                "TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
                "TARGET_EXPORT": "native",
                "TARGET_ADDITIONAL_FRAMEWORKS": null,
                "TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/src",
                "TARGET_NATIVE_MASK": "*.cpp;*.hpp;*.h",
                "TARGET_RESOURCES_MASK": "*.png;*.jpeg;*.ogg;*.ttf",
                "RELOAD_AFTER_BUILD": true,
                "DEVICE_WRAPPER": {
                    "CLASS": "WIN32",
                    "PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/Win32",
                    "TEMPLATES": "resource.h;debugger-config.gdb",
                    "TEMPLATE_EXCLUDE_VARS": "SRC;BIN;OUT;OBJS;CC;LDFLAGS;CFLAGS;RC;OBJ;OBJ_OBJ;LDLIBS"
                },
                "DEVICES": {
                    "Windows (x86)": {
                        "Debugger": "Debugger_GDB",
                        "Debug": "<D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW/bin/gdb.exe> -q -nw -r -f -x <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/debugger-config.gdb> -cd <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32> -d <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32>",
                        "Release": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe"
                    }
                },
                "APP_SETTINGS": {
                    "IOSMINVER": "5",
                    "CPUSET": "armv7",
                    "CFBundleIdentifier": "com.mobilefx.Coconut2D",
                    "UIStatusBarHidden": true,
                    "UIStatusBarStyle": "UIStatusBarStyleBlackTranslucent",
                    "UIViewControllerBasedStatusBarAppearance": true,
                    "UIViewEdgeAntialiasing": false,
                    "UIApplicationExitsOnSuspend": true,
                    "UIInterfaceOrientation": "UIInterfaceOrientationLandscapeRight",
                    "UIInterfaceOrientation_iPad": "UIInterfaceOrientationPortrait",
                    "UIPrerenderedIcon": true
                },
                "APP_ICONS": {
                    "32": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/Application.ico"
                },
                "CODE_SIGNING": {
                    "IOS_CERTIFICATES": "ios_development.cer:AppleIncRootCertificate.cer:AppleWWDRCA.cer",
                    "IOS_PRIVATE_KEY": "ios_development.key",
                    "IOS_PRIVATE_KEY_PASSPHRASE": "puerre",
                    "IOS_PROVISION": "Coconut2D.mobileprovision"
                }
            }
        },
        "Workspace": "k7IAAMQqAAAIAAsAK9qH17gmAABkAG8AYwBrAGkAbgBnAHAAYQBuAGUASBMAADwATABhAHkAbwB1AHQAPgA8AEMAbwBtAG0AbwBuACAAQwBvAG0AcABhAGMAdABNAG8AZABlAD0AIgAxACIAPgA8AFMAdQBtAG0AYQByAHkAIABQAGEAbgBlAHMAPQAiADQANwAiACAAVABvAHAAQwBvAG4AdABhAGkAbgBlAHIAPQAiADEANgAiACAAQwBsAGkAZQBuAHQAPQAiADIAMwAiAC8APgA8AFAAYQBuAGUALQAxACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAyADYAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAzADYANAAiACAAVABpAHQAbABlAD0AIgBUAGkAbQBlAGwAaQBuAGUAXABuAFwAbgAiACAASQBEAD0AIgA5ACIAIABJAGMAbwBuAEkARAA9ACIAMQAyADUAMwAyADAAMwA5ADkAOAAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMgA3ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADcAIgAvAD4APABQAGEAbgBlAC0AMgAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgAyADQAMQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADgANAAxACIAIABUAGkAdABsAGUAPQAiAEEAcwBzAGUAdABzAFwAbgBcAG4AIgAgAEkARAA9ACIAMQA0ACIAIABJAGMAbwBuAEkARAA9ACIALQA4ADcANwA4ADYANQA1ADgANAAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwAyACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAzADIAIgAvAD4APABQAGEAbgBlAC0AMwAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA0ADMAMgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADUANgAwACIAIABUAGkAdABsAGUAPQAiAFAAcgBvAGoAZQBjAHQAIABFAHgAcABsAG8AcgBlAHIAXABuAFwAbgAiACAASQBEAD0AIgAxACIAIABJAGMAbwBuAEkARAA9ACIALQA2ADEAMQA4ADUAOQA4ADQANgAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMQA5ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAxADkAIgAvAD4APABQAGEAbgBlAC0ANAAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgAyADcANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADUAMwA2ACIAIABUAGkAdABsAGUAPQAiAFAAcgBvAHAAZQByAHQAaQBlAHMAXABuAFwAbgAiACAASQBEAD0AIgAyACIAIABJAGMAbwBuAEkARAA9ACIALQAxADEANgA2ADkAOAA3ADUANAA4ACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAyADAAIgAgAEwAYQBzAHQASABvAGwAZABlAHIAPQAiADIAMAAiAC8APgA8AFAAYQBuAGUALQA1ACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA4ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMgAyADEAIgAgAFQAaQB0AGwAZQA9ACIATwB1AHQAcAB1AHQAXABuAFwAbgAiACAASQBEAD0AIgAzACIAIABJAGMAbwBuAEkARAA9ACIAMQA2ADQANAAwADcAOAA2ADUANgAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwAwACIAIABGAGwAbwBhAHQAaQBuAGcASABvAGwAZABlAHIAPQAiADMAOAAiACAATABhAHMAdABIAG8AbABkAGUAcgA9ACIAMwAwACIALwA+ADwAUABhAG4AZQAtADYAIABUAHkAcABlAD0AIgAwACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIANwAwADkAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADYANQAiACAAVABpAHQAbABlAD0AIgBCAHIAZQBhAGsAcABvAGkAbgB0AHMAXABuAFwAbgAiACAASQBEAD0AIgA0ACIAIABJAGMAbwBuAEkARAA9ACIAOQA3ADAANgAzADEANwA4ADkAIgAgAEQAbwBjAGsAaQBuAGcASABvAGwAZABlAHIAPQAiADMAMQAiACAARgBsAG8AYQB0AGkAbgBnAEgAbwBsAGQAZQByAD0AIgA0ADQAIgAgAEwAYQBzAHQASABvAGwAZABlAHIAPQAiADMAMQAiAC8APgA8AFAAYQBuAGUALQA3ACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQAxACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA0ADEAIgAgAFQAaQB0AGwAZQA9ACIAQwBhAGwAbAAgAFMAdABhAGMAawBcAG4AXABuACIAIABJAEQAPQAiADYAIgAgAEkAYwBvAG4ASQBEAD0AIgAxADQAOAAwADkANQA4ADAAMwA3ACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAzADAAIgAgAEYAbABvAGEAdABpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwA1ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAzADAAIgAvAD4APABQAGEAbgBlAC0AOAAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEANwAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADIAMQAwACIAIABUAGkAdABsAGUAPQAiAEUAeABwAHIAZQBzAHMAaQBvAG4AXABuAFwAbgAiACAASQBEAD0AIgA1ACIAIABJAGMAbwBuAEkARAA9ACIALQAyADEAMgA3ADQAMwA2ADgAMQAxACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAyADUAIgAgAEYAbABvAGEAdABpAG4AZwBIAG8AbABkAGUAcgA9ACIANAAxACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADUAIgAvAD4APABQAGEAbgBlAC0AOQAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAMQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADEANAAxACIAIABUAGkAdABsAGUAPQAiAFAAcgBvAGYAaQBsAGUAcgBcAG4AXABuACIAIABJAEQAPQAiADcAIgAgAEkAYwBvAG4ASQBEAD0AIgAtADkAMAA4ADAANwA0ADcAMgAxACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAzADAAIgAgAEYAbABvAGEAdABpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwA1ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAzADAAIgAvAD4APABQAGEAbgBlAC0AMQAwACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQAyACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA1ADEAIgAgAFQAaQB0AGwAZQA9ACIAQwBvAG0AcABpAGwAZQByACAARQByAHIAbwByAHMAXABuAFwAbgAiACAASQBEAD0AIgA4ACIAIABJAGMAbwBuAEkARAA9ACIAMQA0ADQAMwAxADEANAAwADQAMAAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwAwACIAIABGAGwAbwBhAHQAaQBuAGcASABvAGwAZABlAHIAPQAiADMANQAiACAATABhAHMAdABIAG8AbABkAGUAcgA9ACIAMwAwACIALwA+ADwAUABhAG4AZQAtADEAMQAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAOAAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADIAMgAxACIAIABUAGkAdABsAGUAPQAiAEcAaQB0AEgAdQBiAFwAbgBcAG4AIgAgAEkARAA9ACIAMQAwACIAIABJAGMAbwBuAEkARAA9ACIAMQA1ADUAMwA4ADUAMgA0ADcAOQAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMgA3ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADcAIgAvAD4APABQAGEAbgBlAC0AMQAyACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA4ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMgAyADEAIgAgAFQAaQB0AGwAZQA9ACIAQQBEAEIAXABuAFwAbgAiACAASQBEAD0AIgAxADEAIgAgAEkAYwBvAG4ASQBEAD0AIgAtADIAMAA5ADkAMwA0ADIAMgA0ADgAIgAgAEQAbwBjAGsAaQBuAGcASABvAGwAZABlAHIAPQAiADIANwAiACAATABhAHMAdABIAG8AbABkAGUAcgA9ACIAMgA3ACIALwA+ADwAUABhAG4AZQAtADEAMwAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAOAAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADIAMgAxACIAIABUAGkAdABsAGUAPQAiAGkATwBTAFwAbgBcAG4AIgAgAEkARAA9ACIAMQAyACIAIABJAGMAbwBuAEkARAA9ACIAMQAwADMANgAyADgANgA1ADIAMQAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMgA3ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADcAIgAvAD4APABQAGEAbgBlAC0AMQA0ACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA4ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMgAyADEAIgAgAFQAaQB0AGwAZQA9ACIARwBEAEIAXABuAFwAbgAiACAASQBEAD0AIgAxADMAIgAgAEkAYwBvAG4ASQBEAD0AIgAtADIAMAA0ADEAMwAyADEAMgAzADgAIgAgAEQAbwBjAGsAaQBuAGcASABvAGwAZABlAHIAPQAiADMAMQAiACAARgBsAG8AYQB0AGkAbgBnAEgAbwBsAGQAZQByAD0AIgA0ADcAIgAgAEwAYQBzAHQASABvAGwAZABlAHIAPQAiADMAMQAiAC8APgA8AFAAYQBuAGUALQAxADUAIABUAHkAcABlAD0AIgA1ACIAIABEAGkAcgBlAGMAdABpAG8AbgA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADEANgAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgAyADUANQAwACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUABhAG4AZQAtADEAPQAiADEANwAiAC8APgA8AFAAYQBuAGUALQAxADcAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQA5ADEAMAAiACAASABvAHIAaQB6AD0AIgAxACIAIABQAGEAbgBlAHMAPQAiADMAIgAgAFAAYQBuAGUALQAxAD0AIgAxADgAIgAgAFAAYQBuAGUALQAyAD0AIgAyADEAIgAgAFAAYQBuAGUALQAzAD0AIgAzADIAIgAvAD4APABQAGEAbgBlAC0AMQA4ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADMAMQA3ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQAwADgANwAiACAAUABhAG4AZQBzAD0AIgAyACIAIABQAGEAbgBlAC0AMQA9ACIAMQA5ACIAIABQAGEAbgBlAC0AMgA9ACIAMgAwACIALwA+ADwAUABhAG4AZQAtADEAOQAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA0ADMAMgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADcAMgA1ACIAIABQAGEAbgBlAHMAPQAiADEAIgAgAFMAZQBsAGUAYwB0AGUAZAA9ACIAMwAiACAAUABhAG4AZQAtADEAPQAiADMAIgAvAD4APABQAGEAbgBlAC0AMgAwACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADIANwA2ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMwA1ADUAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUwBlAGwAZQBjAHQAZQBkAD0AIgA0ACIAIABQAGEAbgBlAC0AMQA9ACIANAAiAC8APgA8AFAAYQBuAGUALQAyADEAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMgAyADIANgAiACAAUABhAG4AZQBzAD0AIgAyACIAIABQAGEAbgBlAC0AMQA9ACIAMgAyACIAIABQAGEAbgBlAC0AMgA9ACIAMgA2ACIALwA+ADwAUABhAG4AZQAtADIAMgAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADEAMAAzACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMgAiACAAUABhAG4AZQAtADEAPQAiADIAMwAiACAAUABhAG4AZQAtADIAPQAiADIANAAiAC8APgA8AFAAYQBuAGUALQAyADMAIABUAHkAcABlAD0AIgA0ACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQAzADkANwAiAC8APgA8AFAAYQBuAGUALQAyADQAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAOAAyADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgA2ADAANAAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIAMgA1ACIALwA+ADwAUABhAG4AZQAtADIANQAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA2ADgANQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADYAMAA0ACIAIABQAGEAbgBlAHMAPQAiADEAIgAgAFMAZQBsAGUAYwB0AGUAZAA9ACIAOAAiACAAUABhAG4AZQAtADEAPQAiADgAIgAvAD4APABQAGEAbgBlAC0AMgA2ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAyADYAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAyADEANwAiACAASABvAHIAaQB6AD0AIgAxACIAIABQAGEAbgBlAHMAPQAiADIAIgAgAFAAYQBuAGUALQAxAD0AIgAyADcAIgAgAFAAYQBuAGUALQAyAD0AIgAyADgAIgAvAD4APABQAGEAbgBlAC0AMgA3ACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAyADYAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAzADYANAAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADIAOAAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADAAOQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMANgA0ACIAIABQAGEAbgBlAHMAPQAiADEAIgAgAFAAYQBuAGUALQAxAD0AIgAyADkAIgAvAD4APABQAGEAbgBlAC0AMgA5ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAwADcAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADkANQAiACAASABvAHIAaQB6AD0AIgAxACIAIABQAGEAbgBlAHMAPQAiADIAIgAgAFAAYQBuAGUALQAxAD0AIgAzADAAIgAgAFAAYQBuAGUALQAyAD0AIgAzADEAIgAvAD4APABQAGEAbgBlAC0AMwAwACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAwADcAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADkANQAiACAAUABhAG4AZQBzAD0AIgA0ACIAIABTAGUAbABlAGMAdABlAGQAPQAiADUAIgAgAFAAYQBuAGUALQAxAD0AIgA1ACIAIABQAGEAbgBlAC0AMgA9ACIAOQAiACAAUABhAG4AZQAtADMAPQAiADEAMAAiACAAUABhAG4AZQAtADQAPQAiADcAIgAvAD4APABQAGEAbgBlAC0AMwAxACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMAA5ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA2ADUAIgAgAFAAYQBuAGUAcwA9ACIAMgAiACAAUwBlAGwAZQBjAHQAZQBkAD0AIgA2ACIAIABQAGEAbgBlAC0AMQA9ACIANgAiACAAUABhAG4AZQAtADIAPQAiADEANAAiAC8APgA8AFAAYQBuAGUALQAzADIAIABUAHkAcABlAD0AIgAxACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMgA0ADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgA4ADQAMQAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADMAMwAgAFQAeQBwAGUAPQAiADMAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAVABvAHAAUABvAHMAPQAiADEAMQA2ADAAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAQgBvAHQAdABvAG0AUABvAHMAPQAiADEAMwAwADEAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQATABlAGYAdABQAG8AcwA9ACIAOAA0ADIAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAUgBpAGcAaAB0AFAAbwBzAD0AIgAxADUANQAzACIAIABUAG8AcABDAG8AbgB0AGEAbgBlAHIAPQAiADMANAAiAC8APgA8AFAAYQBuAGUALQAzADQAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQAxADIANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMANgA0ACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUABhAG4AZQAtADEAPQAiADMANQAiAC8APgA8AFAAYQBuAGUALQAzADUAIABUAHkAcABlAD0AIgAxACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQAxADIANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMANgA0ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APABQAGEAbgBlAC0AMwA2ACAAVAB5AHAAZQA9ACIAMwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABUAG8AcABQAG8AcwA9ACIAMQAxADYAMAAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABCAG8AdAB0AG8AbQBQAG8AcwA9ACIAMQAzADAAMQAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgA3ADgAMgAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABSAGkAZwBoAHQAUABvAHMAPQAiADEANAA5ADMAIgAgAFQAbwBwAEMAbwBuAHQAYQBuAGUAcgA9ACIAMwA3ACIALwA+ADwAUABhAG4AZQAtADMANwAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAOAAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADQAMAAxACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUABhAG4AZQAtADEAPQAiADMAOAAiAC8APgA8AFAAYQBuAGUALQAzADgAIABUAHkAcABlAD0AIgAxACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIANwAxADgAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgA0ADAAMQAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADMAOQAgAFQAeQBwAGUAPQAiADMAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAVABvAHAAUABvAHMAPQAiADUANQA3ACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AEIAbwB0AHQAbwBtAFAAbwBzAD0AIgA3ADYANwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgAxADQAMAA1ACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AFIAaQBnAGgAdABQAG8AcwA9ACIAMgAxADIAMgAiACAAVABvAHAAQwBvAG4AdABhAG4AZQByAD0AIgA0ADAAIgAvAD4APABQAGEAbgBlAC0ANAAwACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA3ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIANgAwADQAIgAgAEgAbwByAGkAegA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIANAAxACIALwA+ADwAUABhAG4AZQAtADQAMQAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEANwAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADYAMAA0ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APABQAGEAbgBlAC0ANAAyACAAVAB5AHAAZQA9ACIAMwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABUAG8AcABQAG8AcwA9ACIAMQAxADMAMAAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABCAG8AdAB0AG8AbQBQAG8AcwA9ACIAMQAyADkANQAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgAxADAAMwAzACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AFIAaQBnAGgAdABQAG8AcwA9ACIAMQA3ADQAMgAiACAAVABvAHAAQwBvAG4AdABhAG4AZQByAD0AIgA0ADMAIgAvAD4APABQAGEAbgBlAC0ANAAzACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMAA5ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA2ADUAIgAgAEgAbwByAGkAegA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIANAA0ACIALwA+ADwAUABhAG4AZQAtADQANAAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADAAOQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADEANgA1ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APABQAGEAbgBlAC0ANAA1ACAAVAB5AHAAZQA9ACIAMwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABUAG8AcABQAG8AcwA9ACIAMQAwADMAOAAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABCAG8AdAB0AG8AbQBQAG8AcwA9ACIAMQAyADUAOQAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgAxADUAMwA3ACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AFIAaQBnAGgAdABQAG8AcwA9ACIAMgAyADUANQAiACAAVABvAHAAQwBvAG4AdABhAG4AZQByAD0AIgA0ADYAIgAvAD4APABQAGEAbgBlAC0ANAA2ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADYANwA2ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMwAwADgAIgAgAEgAbwByAGkAegA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIANAA3ACIALwA+ADwAUABhAG4AZQAtADQANwAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA2ADcANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMAMAA4ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APAAvAEMAbwBtAG0AbwBuAD4APAAvAEwAYQB5AG8AdQB0AD4AAAADAAwAr0IgpigAAABlAGQAaQB0AG8AcgBnAHIAbwB1AHAAcwABAAAACwAQAP91R+MwAAAAZQBkAGkAdABvAHIAZwByAG8AdQBwAGgAbwByAGkAegD//wAACAAHAPg6h7qYAAAAZQBkAGkAdABvAHIAMQA8AAAALgBTAEQASwBcAEYAcgBhAG0AZQB3AG8AcgBrAHMAXABvAHIAZwAuAGMAbwBjAG8AbgB1AHQAMgBkAC4AcwBkAGsALgBhAG4AaQBtAFwAdwBlAGIAXABzAHIAYwBcAEMAbwBjAG8AQwBsAGkAcAAuAGoAcwBwAHAAAAADAAwA7UIgpigAAABlAGQAaQB0AG8AcgBnAHIAbwB1AHAAMQAAAAAACAAHAPs6h7qgAAAAZQBkAGkAdABvAHIAMgBAAAAALgBTAEQASwBcAEYAcgBhAG0AZQB3AG8AcgBrAHMAXABvAHIAZwAuAGMAbwBjAG8AbgB1AHQAMgBkAC4AcwBkAGsALgBhAG4AaQBtAFwAdwBlAGIAXABzAHIAYwBcAEMAbwBjAG8AVABpAG0AZQBsAGkAbgBlAC4AagBzAHAAcAAAAAMADADuQiCmKAAAAGUAZABpAHQAbwByAGcAcgBvAHUAcAAyAAAAAAAIAAcA+jqHumQAAABlAGQAaQB0AG8AcgAzACMAAAAuAFMARABLAFwAVABvAG8AbABjAGgAYQBpAG4AXABDAG8AbQBwAGkAbABlAHIAXABjAG8AbQBwAGkAbABlAHIALgBqAHMAAwAMAO9CIKYoAAAAZQBkAGkAdABvAHIAZwByAG8AdQBwADMAAAAAAAMABwC6Ooe6IAAAAGUAZABpAHQAbwByAHMABAAAAAAACAAPAPEex7ggAQAAYgByAGUAYQBrAHAAbwBpAG4AdABmAGkAbABlADEAeAAAAEQAOgAvAG0AbwBiAGkAbABlAEYAWAAvAFAAcgBvAGoAZQBjAHQAcwAvAFMAbwBmAHQAdwBhAHIAZQAvAEMAbwBjAG8AbgB1AHQALwBQAHIAbwBqAGUAYwB0AHMALwBDAG8AYwBvAC4AcAByAG8AagBlAGMAdAAvAC4AUwBEAEsALwBGAHIAYQBtAGUAdwBvAHIAawBzAC8AbwByAGcALgBjAG8AYwBvAG4AdQB0ADIAZAAuAHMAZABrAC4AYQBuAGkAbQAvAHcAZQBiAC8AcwByAGMALwBDAG8AYwBvAEMAbABpAHAALgBqAHMAcABwAAAAAwAPAPEeZ7AwAAAAYgByAGUAYQBrAHAAbwBpAG4AdABsAGkAbgBlADEAbgEAAAAAAwALAJkQpLhs1f//YgByAGUAYQBrAHAAbwBpAG4AdABzAAEAAAAAAA=="
    },
    "Vars": {
        "APP_PATH": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio",
        "USERPROFILE": "C:/Users/admin",
        "TARGET": "Win32",
        "TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32",
        "TARGET_DEVICE": "Windows (x86)",
        "CHROME_DEBUG_PORT": "9999",
        "TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe",
        "SURFACE_WIDTH": "480",
        "SURFACE_HEIGHT": "320",
        "LOCALHOST_IP": "192.168.1.108",
        "PROJECT_NAME": "Coconut2D",
        "PROJECT_DISPLAY_NAME": "Coconut2D",
        "PROJECT_PACKAGE": "com.mobilefx.Coconut2D",
        "PROJECT_VERSION": "1.0.0",
        "PROJECT_VERSION_SHORT": "1.0",
        "PROJECT_FRAMEWORKS": "org.coconut2d.sdk.html5;org.coconut2d.sdk.webgl;org.coconut2d.sdk.anim;org.coconut2d.sdk.net;org.coconut2d.sdk.ui",
        "CONFIGURATION": "Debug",
        "DEBUG_HOST_IP": "192.168.1.108",
        "DEBUG_HOST_PORT": "9999",
        "TAGS.OG_COMPANY_ADDRESS": "52 Electras str",
        "TAGS.OG_COMPANY_COUNTRY": "Greece",
        "TAGS.OG_COMPANY_EMAIL": "info@mobilefx.com",
        "TAGS.OG_COMPANY_NAME": "mobileFX",
        "TAGS.OG_COMPANY_PHONE": "+302109522504",
        "TAGS.OG_COMPANY_POSTCODE": "17673",
        "TAGS.OG_COMPANY_REGION": "N. Attikis",
        "TAGS.OG_COPYRIGHT": "Copyright (C) 2014 mobileFX, All Rights Reserved",
        "TAGS.OG_CURRENCY": "Eur",
        "TAGS.OG_DEMO_VIDEO_HEIGHT": "385",
        "TAGS.OG_DEMO_VIDEO_URL": "http://www.youtube.com/mobileFX",
        "TAGS.OG_DEMO_VIDEO_WIDTH": "640",
        "TAGS.OG_DESCRIPTION": "mobileFX presents Coconut2D",
        "TAGS.OG_PRICE": "Free",
        "TAGS.OG_PUBLISHER": "mobileFX",
        "TAGS.OG_TITLE": "Coconut2D",
        "TAGS.OG_HOST": "http://www.mobilefx.com/games",
        "TAGS.OG_URL": "http://www.mobilefx.com/games/Coconut2D.html",
        "PROJECT_PATHS.TARGETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets",
        "PROJECT_PATHS.SDK": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK",
        "PROJECT_PATHS.SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src",
        "PROJECT_PATHS.NATIVE_COMMON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/_Common",
        "PROJECT_PATHS.SOURCES_MASK": "*.jspp",
        "PROJECT_PATHS.ANIMATION_SCRIPTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/src/animations",
        "PROJECT_PATHS.ICON_2048x2048": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/icon.png",
        "PROJECT_PATHS.ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets",
        "PROJECT_PATHS.ASSETS_ANIMATIONS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/animations",
        "PROJECT_PATHS.ASSETS_FONTS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/fonts",
        "PROJECT_PATHS.ASSETS_IMAGES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/images",
        "PROJECT_PATHS.ASSETS_SOUNDS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/sounds",
        "PROJECT_PATHS.ASSETS_VIDEOS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/assets/videos",
        "DEVICE_VIEWPORT.VIEW_WIDTH": "480",
        "DEVICE_VIEWPORT.VIEW_HEIGHT": "320",
        "DEVICE_VIEWPORT.VIEW_PIXEL_RATIO": "1",
        "TARGETS.CocoPlayer.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/CocoPlayer",
        "TARGETS.CocoPlayer.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj",
        "TARGETS.CocoPlayer.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.CocoPlayer.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/main.js",
        "TARGETS.CocoPlayer.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.CocoPlayer.TARGET_EXPORT": "all",
        "TARGETS.CocoPlayer.TARGET_FILTER": "",
        "TARGETS.CocoPlayer.RELOAD_AFTER_BUILD": "true",
        "TARGETS.CocoPlayer.DEVICE_WRAPPER.CLASS": "COCO_PLAYER",
        "TARGETS.CocoPlayer.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/web/Win32",
        "TARGETS.CocoPlayer.DEVICES.CocoPlayer.Debugger": "Debugger_V8Local",
        "TARGETS.CocoPlayer.DEVICES.CocoPlayer.Debug": "CocoPlayer",
        "TARGETS.CocoPlayer.DEVICES.CocoPlayer.Release": "CocoPlayer",
        "TARGETS.HTML5.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/web/HTML5",
        "TARGETS.HTML5.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj",
        "TARGETS.HTML5.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.HTML5.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/index.html",
        "TARGETS.HTML5.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.HTML5.TARGET_EXPORT": "web",
        "TARGETS.HTML5.RELOAD_AFTER_BUILD": "true",
        "TARGETS.HTML5.DEVICE_WRAPPER.CLASS": "HTML5_BROWSER",
        "TARGETS.HTML5.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/web/Win32",
        "TARGETS.HTML5.DEVICE_WRAPPER.TEMPLATES": "*.html;*.css",
        "TARGETS.HTML5.DEVICES.Chrome.Debug": "<C:/Program Files (x86)/Google/Chrome/Application/chrome.exe> --app",
        "TARGETS.HTML5.DEVICES.Chrome.Release": "<C:/Program Files (x86)/Google/Chrome/Application/chrome.exe> --app",
        "TARGETS.HTML5.DEVICES.FireFox.Debug": "<C:/Program Files (x86)/Mozilla Firefox/firefox.exe> -jsconsole -url <file:///D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe>",
        "TARGETS.HTML5.DEVICES.FireFox.Release": "<C:/Program Files (x86)/Mozilla Firefox/firefox.exe> -url <file:///D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe>",
        "TARGETS.HTML5.APP_ICONS.16": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/favicon.ico",
        "TARGETS.HTML5.APP_ICONS.72": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/apple-touch-icon-72x72.png",
        "TARGETS.HTML5.APP_ICONS.76": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/apple-touch-icon-76x76.png",
        "TARGETS.HTML5.APP_ICONS.114": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/apple-touch-icon-114x114.png",
        "TARGETS.HTML5.APP_ICONS.120": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/apple-touch-icon-120x120.png",
        "TARGETS.HTML5.APP_ICONS.144": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/apple-touch-icon-144x144.png",
        "TARGETS.HTML5.APP_ICONS.152": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/apple-touch-icon-152x152.png",
        "TARGETS.Android.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Android",
        "TARGETS.Android.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj",
        "TARGETS.Android.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.Android.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/bin/Coconut2D.apk",
        "TARGETS.Android.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.Android.TARGET_EXPORT": "native",
        "TARGETS.Android.TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/jni/src",
        "TARGETS.Android.TARGET_NATIVE_MASK": "*.cpp;*.hpp;*.h",
        "TARGETS.Android.TARGET_RESOURCES_MASK": "*.png;*.jpeg;*.ogg;*.ttf",
        "TARGETS.Android.RELOAD_AFTER_BUILD": "true",
        "TARGETS.Android.DEVICE_WRAPPER.CLASS": "ANDROID",
        "TARGETS.Android.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/Win32",
        "TARGETS.Android.DEVICE_WRAPPER.TEMPLATES": "*.xml;*.properties;*.java;*.cpp",
        "TARGETS.Android.DEVICES['Android (x86)'].Debugger": "Debugger_GDB",
        "TARGETS.Android.DEVICES['Android (x86)'].Debug": "DeviceBridge",
        "TARGETS.Android.DEVICES['Android (x86)'].Release": "DeviceBridge",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).DEVICE_TYPE_FILTER": "ANDROID",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).Debugger": "Debugger_GDB",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).Debug": "DeviceBridge",
        "TARGETS.Android.DEVICES.(DEBUG_BRIDGE_DEVICES).Release": "DeviceBridge",
        "TARGETS.Android.APP_SETTINGS.ANDROID_PLATFORM": "android-10",
        "TARGETS.Android.APP_SETTINGS.MIN_SDK_VERSION": "10",
        "TARGETS.Android.APP_SETTINGS.TARGET_SDK_VERSION": "19",
        "TARGETS.Android.APP_SETTINGS.SCREEN_ORIENTATION": "landscape",
        "TARGETS.Android.APP_ICONS.48": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/drawable-mdpi/ic_launcher.png",
        "TARGETS.Android.APP_ICONS.72": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/drawable-hdpi/ic_launcher.png",
        "TARGETS.Android.APP_ICONS.96": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/drawable-xhdpi/ic_launcher.png",
        "TARGETS.Android.APP_ICONS.144": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/drawable-xxhdpi/ic_launcher.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/drawable/ic_launcher.png",
        "TARGETS.Android.CODE_SIGNING.COMPANY": "mobileFX",
        "TARGETS.Android.CODE_SIGNING.ORGANIZATION": "mobileFX",
        "TARGETS.Android.CODE_SIGNING.COUNTRY": "US",
        "TARGETS.Android.CODE_SIGNING.PASSWORD": "password",
        "TARGETS.iOS.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/iOS",
        "TARGETS.iOS.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj",
        "TARGETS.iOS.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.iOS.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/bin/Coconut2D.ipa",
        "TARGETS.iOS.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/bin;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.iOS.TARGET_EXPORT": "native",
        "TARGETS.iOS.TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/src",
        "TARGETS.iOS.TARGET_NATIVE_MASK": "*.m;*.cpp;*.hpp;*.h",
        "TARGETS.iOS.TARGET_RESOURCES_MASK": "*.plist;*.png;*.jpeg;*.ogg;*.ttf",
        "TARGETS.iOS.RELOAD_AFTER_BUILD": "true",
        "TARGETS.iOS.DEVICE_WRAPPER.CLASS": "IOS",
        "TARGETS.iOS.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/Win32",
        "TARGETS.iOS.DEVICE_WRAPPER.TEMPLATES": "*.m;*.plist",
        "TARGETS.iOS.DEVICE_WRAPPER.TEMPLATE_EXCLUDE_VARS": "IOSBUILDENV_PATH;PAYLOAD;NAME;CPUSET;IOSMINVER;SRC;OBJDIR;OBJ;OUTDIR;BIN;RES;CFLAGS;LDFLAGS;OBJ_OBJ;PROVISION;CERTIFICATES;PRIVATE_KEY;PASSPHRASE",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).DEVICE_TYPE_FILTER": "IOS",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).Debugger": "Debugger_LLDB",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).Debug": "DeviceBridge",
        "TARGETS.iOS.DEVICES.(DEBUG_BRIDGE_DEVICES).Release": "DeviceBridge",
        "TARGETS.iOS.APP_SETTINGS.IOSMINVER": "5",
        "TARGETS.iOS.APP_SETTINGS.CPUSET": "armv7",
        "TARGETS.iOS.APP_SETTINGS.CFBundleIdentifier": "com.mobilefx.Coconut2D",
        "TARGETS.iOS.APP_SETTINGS.UIStatusBarHidden": "true",
        "TARGETS.iOS.APP_SETTINGS.UIStatusBarStyle": "UIStatusBarStyleBlackTranslucent",
        "TARGETS.iOS.APP_SETTINGS.UIViewControllerBasedStatusBarAppearance": "true",
        "TARGETS.iOS.APP_SETTINGS.UIViewEdgeAntialiasing": "false",
        "TARGETS.iOS.APP_SETTINGS.UIApplicationExitsOnSuspend": "true",
        "TARGETS.iOS.APP_SETTINGS.UIInterfaceOrientation": "UIInterfaceOrientationLandscapeRight",
        "TARGETS.iOS.APP_SETTINGS.UIInterfaceOrientation_iPad": "UIInterfaceOrientationPortrait",
        "TARGETS.iOS.APP_SETTINGS.UIPrerenderedIcon": "true",
        "TARGETS.iOS.APP_ICONS.29": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-29.png",
        "TARGETS.iOS.APP_ICONS.40": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-40.png",
        "TARGETS.iOS.APP_ICONS.48": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-48.png",
        "TARGETS.iOS.APP_ICONS.50": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-50.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-Small-50.png",
        "TARGETS.iOS.APP_ICONS.57": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-57.png",
        "TARGETS.iOS.APP_ICONS.58": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-29@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-58.png",
        "TARGETS.iOS.APP_ICONS.60": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-60.png",
        "TARGETS.iOS.APP_ICONS.72": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-72.png",
        "TARGETS.iOS.APP_ICONS.76": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-76.png",
        "TARGETS.iOS.APP_ICONS.80": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-40@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-80.png",
        "TARGETS.iOS.APP_ICONS.96": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-48@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-96.png",
        "TARGETS.iOS.APP_ICONS.100": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-Small-50@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-100.png",
        "TARGETS.iOS.APP_ICONS.114": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-57@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-114.png",
        "TARGETS.iOS.APP_ICONS.120": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-60@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-120.png",
        "TARGETS.iOS.APP_ICONS.144": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-72@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-144.png",
        "TARGETS.iOS.APP_ICONS.152": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-76@2x.png;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Icon-152.png",
        "TARGETS.iOS.APP_ICONS.512": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/iTunesArtwork.png",
        "TARGETS.iOS.APP_ICONS.1024": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/iTunesArtwork@2x.png",
        "TARGETS.iOS.CODE_SIGNING.IOS_CERTIFICATES": "ios_development.cer:AppleIncRootCertificate.cer:AppleWWDRCA.cer",
        "TARGETS.iOS.CODE_SIGNING.IOS_PRIVATE_KEY": "ios_development.key",
        "TARGETS.iOS.CODE_SIGNING.IOS_PRIVATE_KEY_PASSPHRASE": "puerre",
        "TARGETS.iOS.CODE_SIGNING.IOS_PROVISION": "Coconut2D.mobileprovision",
        "TARGETS.Win32.TARGET_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32",
        "TARGETS.Win32.TARGET_OBJ": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj",
        "TARGETS.Win32.TARGET_ASSETS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.Win32.TARGET_OUTPUT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe",
        "TARGETS.Win32.TARGET_CLEAN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/obj;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/assets",
        "TARGETS.Win32.TARGET_EXPORT": "native",
        "TARGETS.Win32.TARGET_ADDITIONAL_NATIVE_SOURCES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common;D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/src",
        "TARGETS.Win32.TARGET_NATIVE_MASK": "*.cpp;*.hpp;*.h",
        "TARGETS.Win32.TARGET_RESOURCES_MASK": "*.png;*.jpeg;*.ogg;*.ttf",
        "TARGETS.Win32.RELOAD_AFTER_BUILD": "true",
        "TARGETS.Win32.DEVICE_WRAPPER.CLASS": "WIN32",
        "TARGETS.Win32.DEVICE_WRAPPER.PATH": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/Win32",
        "TARGETS.Win32.DEVICE_WRAPPER.TEMPLATES": "resource.h;debugger-config.gdb",
        "TARGETS.Win32.DEVICE_WRAPPER.TEMPLATE_EXCLUDE_VARS": "SRC;BIN;OUT;OBJS;CC;LDFLAGS;CFLAGS;RC;OBJ;OBJ_OBJ;LDLIBS",
        "TARGETS.Win32.DEVICES['Windows (x86)'].Debugger": "Debugger_GDB",
        "TARGETS.Win32.DEVICES['Windows (x86)'].Debug": "<D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW/bin/gdb.exe> -q -nw -r -f -x <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/debugger-config.gdb> -cd <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32> -d <D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32>",
        "TARGETS.Win32.DEVICES['Windows (x86)'].Release": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/Coconut2D.exe",
        "TARGETS.Win32.APP_SETTINGS.IOSMINVER": "5",
        "TARGETS.Win32.APP_SETTINGS.CPUSET": "armv7",
        "TARGETS.Win32.APP_SETTINGS.CFBundleIdentifier": "com.mobilefx.Coconut2D",
        "TARGETS.Win32.APP_SETTINGS.UIStatusBarHidden": "true",
        "TARGETS.Win32.APP_SETTINGS.UIStatusBarStyle": "UIStatusBarStyleBlackTranslucent",
        "TARGETS.Win32.APP_SETTINGS.UIViewControllerBasedStatusBarAppearance": "true",
        "TARGETS.Win32.APP_SETTINGS.UIViewEdgeAntialiasing": "false",
        "TARGETS.Win32.APP_SETTINGS.UIApplicationExitsOnSuspend": "true",
        "TARGETS.Win32.APP_SETTINGS.UIInterfaceOrientation": "UIInterfaceOrientationLandscapeRight",
        "TARGETS.Win32.APP_SETTINGS.UIInterfaceOrientation_iPad": "UIInterfaceOrientationPortrait",
        "TARGETS.Win32.APP_SETTINGS.UIPrerenderedIcon": "true",
        "TARGETS.Win32.APP_ICONS.32": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.targets/native/Win32/res/Application.ico",
        "TARGETS.Win32.CODE_SIGNING.IOS_CERTIFICATES": "ios_development.cer:AppleIncRootCertificate.cer:AppleWWDRCA.cer",
        "TARGETS.Win32.CODE_SIGNING.IOS_PRIVATE_KEY": "ios_development.key",
        "TARGETS.Win32.CODE_SIGNING.IOS_PRIVATE_KEY_PASSPHRASE": "puerre",
        "TARGETS.Win32.CODE_SIGNING.IOS_PROVISION": "Coconut2D.mobileprovision",
        "Workspace": "k7IAAMQqAAAIAAsAK9qH17gmAABkAG8AYwBrAGkAbgBnAHAAYQBuAGUASBMAADwATABhAHkAbwB1AHQAPgA8AEMAbwBtAG0AbwBuACAAQwBvAG0AcABhAGMAdABNAG8AZABlAD0AIgAxACIAPgA8AFMAdQBtAG0AYQByAHkAIABQAGEAbgBlAHMAPQAiADQANwAiACAAVABvAHAAQwBvAG4AdABhAGkAbgBlAHIAPQAiADEANgAiACAAQwBsAGkAZQBuAHQAPQAiADIAMwAiAC8APgA8AFAAYQBuAGUALQAxACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAyADYAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAzADYANAAiACAAVABpAHQAbABlAD0AIgBUAGkAbQBlAGwAaQBuAGUAXABuAFwAbgAiACAASQBEAD0AIgA5ACIAIABJAGMAbwBuAEkARAA9ACIAMQAyADUAMwAyADAAMwA5ADkAOAAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMgA3ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADcAIgAvAD4APABQAGEAbgBlAC0AMgAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgAyADQAMQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADgANAAxACIAIABUAGkAdABsAGUAPQAiAEEAcwBzAGUAdABzAFwAbgBcAG4AIgAgAEkARAA9ACIAMQA0ACIAIABJAGMAbwBuAEkARAA9ACIALQA4ADcANwA4ADYANQA1ADgANAAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwAyACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAzADIAIgAvAD4APABQAGEAbgBlAC0AMwAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA0ADMAMgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADUANgAwACIAIABUAGkAdABsAGUAPQAiAFAAcgBvAGoAZQBjAHQAIABFAHgAcABsAG8AcgBlAHIAXABuAFwAbgAiACAASQBEAD0AIgAxACIAIABJAGMAbwBuAEkARAA9ACIALQA2ADEAMQA4ADUAOQA4ADQANgAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMQA5ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAxADkAIgAvAD4APABQAGEAbgBlAC0ANAAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgAyADcANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADUAMwA2ACIAIABUAGkAdABsAGUAPQAiAFAAcgBvAHAAZQByAHQAaQBlAHMAXABuAFwAbgAiACAASQBEAD0AIgAyACIAIABJAGMAbwBuAEkARAA9ACIALQAxADEANgA2ADkAOAA3ADUANAA4ACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAyADAAIgAgAEwAYQBzAHQASABvAGwAZABlAHIAPQAiADIAMAAiAC8APgA8AFAAYQBuAGUALQA1ACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA4ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMgAyADEAIgAgAFQAaQB0AGwAZQA9ACIATwB1AHQAcAB1AHQAXABuAFwAbgAiACAASQBEAD0AIgAzACIAIABJAGMAbwBuAEkARAA9ACIAMQA2ADQANAAwADcAOAA2ADUANgAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwAwACIAIABGAGwAbwBhAHQAaQBuAGcASABvAGwAZABlAHIAPQAiADMAOAAiACAATABhAHMAdABIAG8AbABkAGUAcgA9ACIAMwAwACIALwA+ADwAUABhAG4AZQAtADYAIABUAHkAcABlAD0AIgAwACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIANwAwADkAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADYANQAiACAAVABpAHQAbABlAD0AIgBCAHIAZQBhAGsAcABvAGkAbgB0AHMAXABuAFwAbgAiACAASQBEAD0AIgA0ACIAIABJAGMAbwBuAEkARAA9ACIAOQA3ADAANgAzADEANwA4ADkAIgAgAEQAbwBjAGsAaQBuAGcASABvAGwAZABlAHIAPQAiADMAMQAiACAARgBsAG8AYQB0AGkAbgBnAEgAbwBsAGQAZQByAD0AIgA0ADQAIgAgAEwAYQBzAHQASABvAGwAZABlAHIAPQAiADMAMQAiAC8APgA8AFAAYQBuAGUALQA3ACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQAxACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA0ADEAIgAgAFQAaQB0AGwAZQA9ACIAQwBhAGwAbAAgAFMAdABhAGMAawBcAG4AXABuACIAIABJAEQAPQAiADYAIgAgAEkAYwBvAG4ASQBEAD0AIgAxADQAOAAwADkANQA4ADAAMwA3ACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAzADAAIgAgAEYAbABvAGEAdABpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwA1ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAzADAAIgAvAD4APABQAGEAbgBlAC0AOAAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEANwAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADIAMQAwACIAIABUAGkAdABsAGUAPQAiAEUAeABwAHIAZQBzAHMAaQBvAG4AXABuAFwAbgAiACAASQBEAD0AIgA1ACIAIABJAGMAbwBuAEkARAA9ACIALQAyADEAMgA3ADQAMwA2ADgAMQAxACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAyADUAIgAgAEYAbABvAGEAdABpAG4AZwBIAG8AbABkAGUAcgA9ACIANAAxACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADUAIgAvAD4APABQAGEAbgBlAC0AOQAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAMQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADEANAAxACIAIABUAGkAdABsAGUAPQAiAFAAcgBvAGYAaQBsAGUAcgBcAG4AXABuACIAIABJAEQAPQAiADcAIgAgAEkAYwBvAG4ASQBEAD0AIgAtADkAMAA4ADAANwA0ADcAMgAxACIAIABEAG8AYwBrAGkAbgBnAEgAbwBsAGQAZQByAD0AIgAzADAAIgAgAEYAbABvAGEAdABpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwA1ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAzADAAIgAvAD4APABQAGEAbgBlAC0AMQAwACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQAyACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA1ADEAIgAgAFQAaQB0AGwAZQA9ACIAQwBvAG0AcABpAGwAZQByACAARQByAHIAbwByAHMAXABuAFwAbgAiACAASQBEAD0AIgA4ACIAIABJAGMAbwBuAEkARAA9ACIAMQA0ADQAMwAxADEANAAwADQAMAAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMwAwACIAIABGAGwAbwBhAHQAaQBuAGcASABvAGwAZABlAHIAPQAiADMANQAiACAATABhAHMAdABIAG8AbABkAGUAcgA9ACIAMwAwACIALwA+ADwAUABhAG4AZQAtADEAMQAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAOAAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADIAMgAxACIAIABUAGkAdABsAGUAPQAiAEcAaQB0AEgAdQBiAFwAbgBcAG4AIgAgAEkARAA9ACIAMQAwACIAIABJAGMAbwBuAEkARAA9ACIAMQA1ADUAMwA4ADUAMgA0ADcAOQAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMgA3ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADcAIgAvAD4APABQAGEAbgBlAC0AMQAyACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA4ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMgAyADEAIgAgAFQAaQB0AGwAZQA9ACIAQQBEAEIAXABuAFwAbgAiACAASQBEAD0AIgAxADEAIgAgAEkAYwBvAG4ASQBEAD0AIgAtADIAMAA5ADkAMwA0ADIAMgA0ADgAIgAgAEQAbwBjAGsAaQBuAGcASABvAGwAZABlAHIAPQAiADIANwAiACAATABhAHMAdABIAG8AbABkAGUAcgA9ACIAMgA3ACIALwA+ADwAUABhAG4AZQAtADEAMwAgAFQAeQBwAGUAPQAiADAAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAOAAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADIAMgAxACIAIABUAGkAdABsAGUAPQAiAGkATwBTAFwAbgBcAG4AIgAgAEkARAA9ACIAMQAyACIAIABJAGMAbwBuAEkARAA9ACIAMQAwADMANgAyADgANgA1ADIAMQAiACAARABvAGMAawBpAG4AZwBIAG8AbABkAGUAcgA9ACIAMgA3ACIAIABMAGEAcwB0AEgAbwBsAGQAZQByAD0AIgAyADcAIgAvAD4APABQAGEAbgBlAC0AMQA0ACAAVAB5AHAAZQA9ACIAMAAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA4ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMgAyADEAIgAgAFQAaQB0AGwAZQA9ACIARwBEAEIAXABuAFwAbgAiACAASQBEAD0AIgAxADMAIgAgAEkAYwBvAG4ASQBEAD0AIgAtADIAMAA0ADEAMwAyADEAMgAzADgAIgAgAEQAbwBjAGsAaQBuAGcASABvAGwAZABlAHIAPQAiADMAMQAiACAARgBsAG8AYQB0AGkAbgBnAEgAbwBsAGQAZQByAD0AIgA0ADcAIgAgAEwAYQBzAHQASABvAGwAZABlAHIAPQAiADMAMQAiAC8APgA8AFAAYQBuAGUALQAxADUAIABUAHkAcABlAD0AIgA1ACIAIABEAGkAcgBlAGMAdABpAG8AbgA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADEANgAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgAyADUANQAwACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUABhAG4AZQAtADEAPQAiADEANwAiAC8APgA8AFAAYQBuAGUALQAxADcAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQA5ADEAMAAiACAASABvAHIAaQB6AD0AIgAxACIAIABQAGEAbgBlAHMAPQAiADMAIgAgAFAAYQBuAGUALQAxAD0AIgAxADgAIgAgAFAAYQBuAGUALQAyAD0AIgAyADEAIgAgAFAAYQBuAGUALQAzAD0AIgAzADIAIgAvAD4APABQAGEAbgBlAC0AMQA4ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADMAMQA3ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQAwADgANwAiACAAUABhAG4AZQBzAD0AIgAyACIAIABQAGEAbgBlAC0AMQA9ACIAMQA5ACIAIABQAGEAbgBlAC0AMgA9ACIAMgAwACIALwA+ADwAUABhAG4AZQAtADEAOQAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA0ADMAMgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADcAMgA1ACIAIABQAGEAbgBlAHMAPQAiADEAIgAgAFMAZQBsAGUAYwB0AGUAZAA9ACIAMwAiACAAUABhAG4AZQAtADEAPQAiADMAIgAvAD4APABQAGEAbgBlAC0AMgAwACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADIANwA2ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMwA1ADUAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUwBlAGwAZQBjAHQAZQBkAD0AIgA0ACIAIABQAGEAbgBlAC0AMQA9ACIANAAiAC8APgA8AFAAYQBuAGUALQAyADEAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMgAyADIANgAiACAAUABhAG4AZQBzAD0AIgAyACIAIABQAGEAbgBlAC0AMQA9ACIAMgAyACIAIABQAGEAbgBlAC0AMgA9ACIAMgA2ACIALwA+ADwAUABhAG4AZQAtADIAMgAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADEAMAAzACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMgAiACAAUABhAG4AZQAtADEAPQAiADIAMwAiACAAUABhAG4AZQAtADIAPQAiADIANAAiAC8APgA8AFAAYQBuAGUALQAyADMAIABUAHkAcABlAD0AIgA0ACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQAzADkANwAiAC8APgA8AFAAYQBuAGUALQAyADQAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAOAAyADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgA2ADAANAAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIAMgA1ACIALwA+ADwAUABhAG4AZQAtADIANQAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA2ADgANQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADYAMAA0ACIAIABQAGEAbgBlAHMAPQAiADEAIgAgAFMAZQBsAGUAYwB0AGUAZAA9ACIAOAAiACAAUABhAG4AZQAtADEAPQAiADgAIgAvAD4APABQAGEAbgBlAC0AMgA2ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAyADYAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAyADEANwAiACAASABvAHIAaQB6AD0AIgAxACIAIABQAGEAbgBlAHMAPQAiADIAIgAgAFAAYQBuAGUALQAxAD0AIgAyADcAIgAgAFAAYQBuAGUALQAyAD0AIgAyADgAIgAvAD4APABQAGEAbgBlAC0AMgA3ACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAyADYAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAzADYANAAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADIAOAAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADAAOQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMANgA0ACIAIABQAGEAbgBlAHMAPQAiADEAIgAgAFAAYQBuAGUALQAxAD0AIgAyADkAIgAvAD4APABQAGEAbgBlAC0AMgA5ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAwADcAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADkANQAiACAASABvAHIAaQB6AD0AIgAxACIAIABQAGEAbgBlAHMAPQAiADIAIgAgAFAAYQBuAGUALQAxAD0AIgAzADAAIgAgAFAAYQBuAGUALQAyAD0AIgAzADEAIgAvAD4APABQAGEAbgBlAC0AMwAwACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADEAMQAwADcAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgAxADkANQAiACAAUABhAG4AZQBzAD0AIgA0ACIAIABTAGUAbABlAGMAdABlAGQAPQAiADUAIgAgAFAAYQBuAGUALQAxAD0AIgA1ACIAIABQAGEAbgBlAC0AMgA9ACIAOQAiACAAUABhAG4AZQAtADMAPQAiADEAMAAiACAAUABhAG4AZQAtADQAPQAiADcAIgAvAD4APABQAGEAbgBlAC0AMwAxACAAVAB5AHAAZQA9ACIAMQAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMAA5ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA2ADUAIgAgAFAAYQBuAGUAcwA9ACIAMgAiACAAUwBlAGwAZQBjAHQAZQBkAD0AIgA2ACIAIABQAGEAbgBlAC0AMQA9ACIANgAiACAAUABhAG4AZQAtADIAPQAiADEANAAiAC8APgA8AFAAYQBuAGUALQAzADIAIABUAHkAcABlAD0AIgAxACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMgA0ADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgA4ADQAMQAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADMAMwAgAFQAeQBwAGUAPQAiADMAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAVABvAHAAUABvAHMAPQAiADEAMQA2ADAAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAQgBvAHQAdABvAG0AUABvAHMAPQAiADEAMwAwADEAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQATABlAGYAdABQAG8AcwA9ACIAOAA0ADIAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAUgBpAGcAaAB0AFAAbwBzAD0AIgAxADUANQAzACIAIABUAG8AcABDAG8AbgB0AGEAbgBlAHIAPQAiADMANAAiAC8APgA8AFAAYQBuAGUALQAzADQAIABUAHkAcABlAD0AIgAyACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQAxADIANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMANgA0ACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUABhAG4AZQAtADEAPQAiADMANQAiAC8APgA8AFAAYQBuAGUALQAzADUAIABUAHkAcABlAD0AIgAxACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIAMQAxADIANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMANgA0ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APABQAGEAbgBlAC0AMwA2ACAAVAB5AHAAZQA9ACIAMwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABUAG8AcABQAG8AcwA9ACIAMQAxADYAMAAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABCAG8AdAB0AG8AbQBQAG8AcwA9ACIAMQAzADAAMQAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgA3ADgAMgAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABSAGkAZwBoAHQAUABvAHMAPQAiADEANAA5ADMAIgAgAFQAbwBwAEMAbwBuAHQAYQBuAGUAcgA9ACIAMwA3ACIALwA+ADwAUABhAG4AZQAtADMANwAgAFQAeQBwAGUAPQAiADIAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEAOAAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADQAMAAxACIAIABIAG8AcgBpAHoAPQAiADEAIgAgAFAAYQBuAGUAcwA9ACIAMQAiACAAUABhAG4AZQAtADEAPQAiADMAOAAiAC8APgA8AFAAYQBuAGUALQAzADgAIABUAHkAcABlAD0AIgAxACIAIABEAG8AYwBrAGkAbgBnAEMAWAA9ACIANwAxADgAIgAgAEQAbwBjAGsAaQBuAGcAQwBZAD0AIgA0ADAAMQAiACAAUABhAG4AZQBzAD0AIgAwACIALwA+ADwAUABhAG4AZQAtADMAOQAgAFQAeQBwAGUAPQAiADMAIgAgAFcAaQBuAGQAbwB3AFIAZQBjAHQAVABvAHAAUABvAHMAPQAiADUANQA3ACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AEIAbwB0AHQAbwBtAFAAbwBzAD0AIgA3ADYANwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgAxADQAMAA1ACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AFIAaQBnAGgAdABQAG8AcwA9ACIAMgAxADIAMgAiACAAVABvAHAAQwBvAG4AdABhAG4AZQByAD0AIgA0ADAAIgAvAD4APABQAGEAbgBlAC0ANAAwACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMQA3ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIANgAwADQAIgAgAEgAbwByAGkAegA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIANAAxACIALwA+ADwAUABhAG4AZQAtADQAMQAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADEANwAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADYAMAA0ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APABQAGEAbgBlAC0ANAAyACAAVAB5AHAAZQA9ACIAMwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABUAG8AcABQAG8AcwA9ACIAMQAxADMAMAAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABCAG8AdAB0AG8AbQBQAG8AcwA9ACIAMQAyADkANQAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgAxADAAMwAzACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AFIAaQBnAGgAdABQAG8AcwA9ACIAMQA3ADQAMgAiACAAVABvAHAAQwBvAG4AdABhAG4AZQByAD0AIgA0ADMAIgAvAD4APABQAGEAbgBlAC0ANAAzACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADcAMAA5ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMQA2ADUAIgAgAEgAbwByAGkAegA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIANAA0ACIALwA+ADwAUABhAG4AZQAtADQANAAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA3ADAAOQAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADEANgA1ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APABQAGEAbgBlAC0ANAA1ACAAVAB5AHAAZQA9ACIAMwAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABUAG8AcABQAG8AcwA9ACIAMQAwADMAOAAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABCAG8AdAB0AG8AbQBQAG8AcwA9ACIAMQAyADUAOQAiACAAVwBpAG4AZABvAHcAUgBlAGMAdABMAGUAZgB0AFAAbwBzAD0AIgAxADUAMwA3ACIAIABXAGkAbgBkAG8AdwBSAGUAYwB0AFIAaQBnAGgAdABQAG8AcwA9ACIAMgAyADUANQAiACAAVABvAHAAQwBvAG4AdABhAG4AZQByAD0AIgA0ADYAIgAvAD4APABQAGEAbgBlAC0ANAA2ACAAVAB5AHAAZQA9ACIAMgAiACAARABvAGMAawBpAG4AZwBDAFgAPQAiADYANwA2ACIAIABEAG8AYwBrAGkAbgBnAEMAWQA9ACIAMwAwADgAIgAgAEgAbwByAGkAegA9ACIAMQAiACAAUABhAG4AZQBzAD0AIgAxACIAIABQAGEAbgBlAC0AMQA9ACIANAA3ACIALwA+ADwAUABhAG4AZQAtADQANwAgAFQAeQBwAGUAPQAiADEAIgAgAEQAbwBjAGsAaQBuAGcAQwBYAD0AIgA2ADcANgAiACAARABvAGMAawBpAG4AZwBDAFkAPQAiADMAMAA4ACIAIABQAGEAbgBlAHMAPQAiADAAIgAvAD4APAAvAEMAbwBtAG0AbwBuAD4APAAvAEwAYQB5AG8AdQB0AD4AAAADAAwAr0IgpigAAABlAGQAaQB0AG8AcgBnAHIAbwB1AHAAcwABAAAACwAQAP91R+MwAAAAZQBkAGkAdABvAHIAZwByAG8AdQBwAGgAbwByAGkAegD//wAACAAHAPg6h7qYAAAAZQBkAGkAdABvAHIAMQA8AAAALgBTAEQASwBcAEYAcgBhAG0AZQB3AG8AcgBrAHMAXABvAHIAZwAuAGMAbwBjAG8AbgB1AHQAMgBkAC4AcwBkAGsALgBhAG4AaQBtAFwAdwBlAGIAXABzAHIAYwBcAEMAbwBjAG8AQwBsAGkAcAAuAGoAcwBwAHAAAAADAAwA7UIgpigAAABlAGQAaQB0AG8AcgBnAHIAbwB1AHAAMQAAAAAACAAHAPs6h7qgAAAAZQBkAGkAdABvAHIAMgBAAAAALgBTAEQASwBcAEYAcgBhAG0AZQB3AG8AcgBrAHMAXABvAHIAZwAuAGMAbwBjAG8AbgB1AHQAMgBkAC4AcwBkAGsALgBhAG4AaQBtAFwAdwBlAGIAXABzAHIAYwBcAEMAbwBjAG8AVABpAG0AZQBsAGkAbgBlAC4AagBzAHAAcAAAAAMADADuQiCmKAAAAGUAZABpAHQAbwByAGcAcgBvAHUAcAAyAAAAAAAIAAcA+jqHumQAAABlAGQAaQB0AG8AcgAzACMAAAAuAFMARABLAFwAVABvAG8AbABjAGgAYQBpAG4AXABDAG8AbQBwAGkAbABlAHIAXABjAG8AbQBwAGkAbABlAHIALgBqAHMAAwAMAO9CIKYoAAAAZQBkAGkAdABvAHIAZwByAG8AdQBwADMAAAAAAAMABwC6Ooe6IAAAAGUAZABpAHQAbwByAHMABAAAAAAACAAPAPEex7ggAQAAYgByAGUAYQBrAHAAbwBpAG4AdABmAGkAbABlADEAeAAAAEQAOgAvAG0AbwBiAGkAbABlAEYAWAAvAFAAcgBvAGoAZQBjAHQAcwAvAFMAbwBmAHQAdwBhAHIAZQAvAEMAbwBjAG8AbgB1AHQALwBQAHIAbwBqAGUAYwB0AHMALwBDAG8AYwBvAC4AcAByAG8AagBlAGMAdAAvAC4AUwBEAEsALwBGAHIAYQBtAGUAdwBvAHIAawBzAC8AbwByAGcALgBjAG8AYwBvAG4AdQB0ADIAZAAuAHMAZABrAC4AYQBuAGkAbQAvAHcAZQBiAC8AcwByAGMALwBDAG8AYwBvAEMAbABpAHAALgBqAHMAcABwAAAAAwAPAPEeZ7AwAAAAYgByAGUAYQBrAHAAbwBpAG4AdABsAGkAbgBlADEAbgEAAAAAAwALAJkQpLhs1f//YgByAGUAYQBrAHAAbwBpAG4AdABzAAEAAAAAAA",
        "PATH_IDE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio",
        "PATH_3RD_PARTY": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party",
        "PATH_3RD_PARTY_CLOSURE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/closure",
        "PATH_3RD_PARTY_FFMPEG": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/ffmpeg",
        "PATH_3RD_PARTY_FIGLET": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/figlet",
        "PATH_3RD_PARTY_GIT": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/git",
        "PATH_3RD_PARTY_JSON": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/json",
        "PATH_3RD_PARTY_LIBMOBILEDEVICE": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/libmobiledevice",
        "PATH_3RD_PARTY_ANT": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/ant",
        "PATH_3RD_PARTY_JAVA": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/java",
        "PATH_3RD_PARTY_WINDBG": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/WinDBG",
        "PATH_3RD_PARTY_MINGW": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW",
        "PATH_3RD_PARTY_GDB": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/MinGW/bin",
        "PATH_3RD_PARTY_PYTHON": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/Python27",
        "PATH_3RD_PARTY_NODEJS": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk/nodejs",
        "PATH_3RD_PARTY_EMSDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/emsdk",
        "PATH_3RD_PARTY_LLVM": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/LLVM",
        "PATH_3RD_PARTY_LLDB": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/LLDB",
        "PATH_3RD_PARTY_ANDROID_SDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/android-sdk",
        "PATH_3RD_PARTY_ANDROID_NDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/android-ndk",
        "PATH_3RD_PARTY_IOS_BUILD_ENV": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/3rd_party/iOS",
        "PATH_IDE_CONFIG": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config",
        "FILE_PATH_SETTINGS_DEFAULT": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config/settings.ini",
        "FILE_PATH_DEVICES_XML": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/config/devices.xml",
        "PATH_IDE_DOCS": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/docs",
        "PATH_IDE_ICONS": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/icons",
        "PATH_IDE_CODEMAX_LANGUAGES": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/languages",
        "FILE_PATH_SETTINGS_USER": "C:/Users/admin/Coconut2D/settings.ini",
        "PATH_SDK": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/.SDK",
        "FILE_PATH_SDK_FRAMEWORKS_REGISTRY": "D:/mobileFX/Projects/Software/Coconut/IDE/Studio/etc/.SDK/Frameworks/Frameworks.json",
        "PATH_SDK_DEVICE_WRAPPERS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers",
        "PATH_SDK_COMMON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common",
        "PATH_SDK_INCLUDES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Includes",
        "PATH_SDK_LIBRARIES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Libraries",
        "PATH_SDK_FRAMEWORKS": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks",
        "PATH_SDK_FRAMEWORKS_WEB": "web",
        "PATH_SDK_FRAMEWORKS_NATIVE": "native",
        "PATH_SDK_FRAMEWORKS_GEN": "gen",
        "PATH_SDK_FRAMEWORKS_SRC": "src",
        "PATH_SDK_FRAMEWORKS_LIB": "lib",
        "PATH_SDK_TEMPLATES": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates",
        "PATH_SDK_TEMPLATE_COCO_PROJECT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/Coco.Project",
        "FILE_PATH_TEMPLATE_PROJECT_JSON": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Templates/Coco.Project/project.json",
        "PATH_SDK_TOOLCHAIN": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Toolchain",
        "PATH_SDK_COMPILER": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Toolchain/Compiler",
        "PATH_SDK_DEBUGGER": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Toolchain/Debugger",
        "FILE_PATH_SDK_CRL_COCONUT2D_HPP": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/DeviceWrappers/native/_Common/Coconut2D.hpp",
        "PROJECT_ROOT": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project",
        "ORG.COCONUT2D.SDK.HTML5": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.html5",
        "ORG.COCONUT2D.SDK.WEBGL": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.webgl",
        "ORG.COCONUT2D.SDK.ANIM": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.anim",
        "ORG.COCONUT2D.SDK.NET": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.net",
        "ORG.COCONUT2D.SDK.UI": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.ui",
        "ORG.COCONUT2D.SDK.GAME2D": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.coconut2d.sdk.game2d",
        "ORG.EMSCRIPTEN.BOX2D": "D:/mobileFX/Projects/Software/Coconut/Projects/Coco.project/.SDK/Frameworks/org.emscripten.box2d",
        "TEXT_FILES": "*.mk;*.asp;*.c;*.cc;*.cpp;*.css;*.csv;*.cxx;*.doc;*.gdl;*.h;*.hh;*.hpp;*.hta;*.htc;*.htm;*.html;*.inc;*.include;*.j;*.java;*.javascript;*.jspp;*.js;*.jscript;*.glsl;*.json;*.jx;*.log;*.m;*.makefile;*.mx;*.mxx;*.pbxproj;*.pch;*.plist;*.strings;*.txt;*.xhtml;*.xml;*.xsd;*.xslt;*.bat;*.cmd;*.ini;*.mm;*.settings;*.jobj;*.md;*.lst;*.properties;*.conf;*.gdb"
    },
    "Components": {
        "Frameworks": {
            "org.coconut2d.sdk.html5": {
                "Name": "Coconut2D HTML5 Bindings Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_HTML5",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.html5",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.webgl": {
                "Name": "Coconut2D WebGL Bindings Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_WEBGL",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.webgl",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.anim": {
                "Name": "Coconut2D Core Animation Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_ANIMATION",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.anim",
                "Description": "",
                "Dependencies": "",
                "FSM": true
            },
            "org.coconut2d.sdk.net": {
                "Name": "Coconut2D Core Network Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_NET",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.net",
                "Description": "",
                "Dependencies": "",
                "FSM": false
            },
            "org.coconut2d.sdk.ui": {
                "Name": "Coconut2D Core Application Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_APPLICATION",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.ui",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.anim",
                "FSM": true
            },
            "org.coconut2d.sdk.game2d": {
                "Name": "Coconut2D Core 2D Game Framework",
                "Version": "0.1",
                "Type": "CocoScript",
                "Copyright": "Copyright (C) 2014, mobileFX. All Rights Reserved",
                "License": "MIT",
                "PrecompilerVarName": "COCONUT2D_GAME2D",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.coconut2d.sdk.game2d",
                "Description": "",
                "Dependencies": "org.coconut2d.sdk.anim",
                "FSM": true
            },
            "org.emscripten.box2d": {
                "Name": "Box2D Physics Engine",
                "Version": "2.1",
                "Type": "Emscripten Library",
                "Copyright": "Copyright (c) 2006-2010 Erin Catto - http://www.gphysics.com",
                "License": "zlib license + acknowledgement",
                "PrecompilerVarName": "EMS_BOX2D",
                "Path": "$(PATH_SDK_FRAMEWORKS)/org.emscripten.box2d",
                "Description": "Box2D is an open source C++ engine for simulating rigid bodies in 2D. Box2D is developed by Erin Catto and has the zlib license. While the zlib license does not require acknowledgement, we encourage you to give credit to Box2D in your product.",
                "Dependencies": "org.coconut2d.sdk.anim",
                "FSM": false
            }
        }
    }
};