/* Generated by Coconut2D C++ Compiler from file Page1.jspp */

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "Page1.hpp"
#include "CocoScene.hpp"
#include "CocoImage.hpp"
#include "CocoClip.hpp"
#include "CocoTimeline.hpp"
#include "Constants.hpp"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////
Page1::Page1()
{
	__sceneName = String("Page1");
	__fps = 30;
	__view_width = 0;
	__view_height = 0;
	__view_pixel_ratio = 0;
	CocoImage* Image_SkinSymbol_iPhone_AlertButton_Light = newResourceImage(String("SkinSymbol_iPhone_AlertButton_Light"), String("./images/"));
	{
		Image_SkinSymbol_iPhone_AlertButton_Light->viewOptimalWidth = 0;
		Image_SkinSymbol_iPhone_AlertButton_Light->viewOptimalHeight = 0;
		Image_SkinSymbol_iPhone_AlertButton_Light->addSibling(new CocoImageSibling(String("iPhone_AlertButton_Light_mdpi.png"), 1, 0, 0));
		Image_SkinSymbol_iPhone_AlertButton_Light->addSibling(new CocoImageSibling(String("iPhone_AlertButton_Light_xhdpi.png"), 2, 0, 0));
		Image_SkinSymbol_iPhone_AlertButton_Light->skin = new Float32Array((new Array<float> ())->push(43)->push(43)->push(42)->push(0)->push(43)->push(0));
		Image_SkinSymbol_iPhone_AlertButton_Light->textureCellWidth = 128;
		Image_SkinSymbol_iPhone_AlertButton_Light->textureCellHeight = 43;
		Image_SkinSymbol_iPhone_AlertButton_Light->textureGrid = new Float32Array((new Array<float> ())->push(0)->push(0));
	}
	CocoImage* Image_SkinSymbol_iPhone_Alert = newResourceImage(String("SkinSymbol_iPhone_Alert"), String("./images/"));
	{
		Image_SkinSymbol_iPhone_Alert->viewOptimalWidth = 0;
		Image_SkinSymbol_iPhone_Alert->viewOptimalHeight = 0;
		Image_SkinSymbol_iPhone_Alert->addSibling(new CocoImageSibling(String("iPhone_Alert_mdpi.png"), 1, 0, 0));
		Image_SkinSymbol_iPhone_Alert->addSibling(new CocoImageSibling(String("iPhone_Alert_xhdpi.png"), 2, 0, 0));
		Image_SkinSymbol_iPhone_Alert->skin = new Float32Array((new Array<float> ())->push(139)->push(6)->push(139)->push(30)->push(2)->push(30));
		Image_SkinSymbol_iPhone_Alert->textureCellWidth = 284;
		Image_SkinSymbol_iPhone_Alert->textureCellHeight = 62;
		Image_SkinSymbol_iPhone_Alert->textureGrid = new Float32Array((new Array<float> ())->push(0)->push(0));
	}
	CocoImage* Image_SkinSymbol_iPhone_ComboBoxPressed = newResourceImage(String("SkinSymbol_iPhone_ComboBoxPressed"), String("./images/"));
	{
		Image_SkinSymbol_iPhone_ComboBoxPressed->viewOptimalWidth = 0;
		Image_SkinSymbol_iPhone_ComboBoxPressed->viewOptimalHeight = 0;
		Image_SkinSymbol_iPhone_ComboBoxPressed->addSibling(new CocoImageSibling(String("iPhone_ComboBoxPressed_mdpi.png"), 1, 0, 0));
		Image_SkinSymbol_iPhone_ComboBoxPressed->addSibling(new CocoImageSibling(String("iPhone_ComboBoxPressed_xhdpi.png"), 2, 0, 0));
		Image_SkinSymbol_iPhone_ComboBoxPressed->skin = new Float32Array((new Array<float> ())->push(14)->push(2)->push(25)->push(0)->push(27)->push(0));
		Image_SkinSymbol_iPhone_ComboBoxPressed->textureCellWidth = 41;
		Image_SkinSymbol_iPhone_ComboBoxPressed->textureCellHeight = 27;
		Image_SkinSymbol_iPhone_ComboBoxPressed->textureGrid = new Float32Array((new Array<float> ())->push(0)->push(0));
	}
	CocoImage* Image_SkinSymbol_iPhone_ComboBox = newResourceImage(String("SkinSymbol_iPhone_ComboBox"), String("./images/"));
	{
		Image_SkinSymbol_iPhone_ComboBox->viewOptimalWidth = 0;
		Image_SkinSymbol_iPhone_ComboBox->viewOptimalHeight = 0;
		Image_SkinSymbol_iPhone_ComboBox->addSibling(new CocoImageSibling(String("iPhone_ComboBox_mdpi.png"), 1, 0, 0));
		Image_SkinSymbol_iPhone_ComboBox->addSibling(new CocoImageSibling(String("iPhone_ComboBox_xhdpi.png"), 2, 0, 0));
		Image_SkinSymbol_iPhone_ComboBox->skin = new Float32Array((new Array<float> ())->push(14)->push(2)->push(25)->push(0)->push(27)->push(0));
		Image_SkinSymbol_iPhone_ComboBox->textureCellWidth = 41;
		Image_SkinSymbol_iPhone_ComboBox->textureCellHeight = 27;
		Image_SkinSymbol_iPhone_ComboBox->textureGrid = new Float32Array((new Array<float> ())->push(0)->push(0));
	}
	__root = new CocoClip();
	__root->__instanceName = String("root");
	__root->__scene = this;
	__root->__timeline->clear();
	__root->__timeline->addKeyFrameEx(nullptr, nullptr, 0, COCO_KEYFRAME_INTERPOLATION_ENUM::KEYFRAME_INTERPOLATION_MOTION_TWEEN, false, true, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, nullptr, false, false, String(""));
}
