/* Generated by Coconut2D C++ Compiler from file GameEngine.jspp */

#ifndef __GAMEENGINE_HPP__
#define __GAMEENGINE_HPP__

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "Coconut2D.hpp"
#include "CocoEngine.hpp"
#include "CocoScene.hpp"
#include "CocoUIButton.hpp"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class GameEngine : public CocoEngine
{
public:
	CocoScene* scene;
	CocoUIButton* btn1;
	CocoUIButton* btn2;
	GameEngine();
	virtual ~GameEngine();
	struct STATE_GAME : State
	{
		GameEngine* self;
		int vzzz = 0;
		STATE_GAME(GameEngine* self) : self(self) {}
		void enter();
		void exit();
		void tick(float time);
		void paint(WebGLRenderingContext* gl, Time time);
	}* STATE_GAME = new struct STATE_GAME(this);
};

#endif // __GAMEENGINE_HPP__
