var COCO_TEXT_TRIMMING_ENUM={StringTrimmingNone:0,StringTrimmingCharacter:1,StringTrimmingWord:2,StringTrimmingEllipsisCharacter:3,StringTrimmingEllipsisWord:4,StringTrimmingEllipsisPath:5},COCO_TEXT_ALIGN_ENUM={TEXT_ALIGN_NEAR:0,TEXT_ALIGN_CENTER:1,TEXT_ALIGN_FAR:2},COCO_FILTER_ENUM={FILTER_INHERIT:0,FILTER_SIMPLE:1,FILTER_SIMPLE_WITH_ALPHA:2,FILTER_SATURATION_WITH_ALPHA:3},COCO_KEYFRAME_INTERPOLATION_ENUM={KEYFRAME_INTERPOLATION_NONE:0,KEYFRAME_INTERPOLATION_MOTION_TWEEN:1,KEYFRAME_INTERPOLATION_ECHO:2,
KEYFRAME_INTERPOLATION_PHYSICS:3},COCO_CLIP_SYMBOL_LOOP_ENUM={CLIP_SYMBOL_LOOP_CONTINUOUS:0,CLIP_SYMBOL_LOOP_SYNCHRONIZED_WITH_PARENT:1,CLIP_SYMBOL_LOOP_ONCE:2},SCREEN_RESOLUTION_DPI_ENUM={RESOLUTION_nodpi:0,RESOLUTION_ldpi:1,RESOLUTION_mdpi:2,RESOLUTION_tvdpi:3,RESOLUTION_hdpi:4,RESOLUTION_xhdpi:5,RESOLUTION_Retina:5,RESOLUTION_DefaultDpi:0};
function CocoAudio(g,b,c){return new function(a,b,c,e){var d=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.reset=function(){d.audio&&(d.audio.pause(),d.audio.ended=!1,d.audio.paused=!0,d.setCurrentTime(0),d.__PRIVATE__.__loopCount=0,d.__PRIVATE__.__firstPlayed=!1)};this.tick=function(){d.audio&&(!d.__PRIVATE__.__firstPlayed&&d.autoplay?(d.__PRIVATE__.__firstPlayed=
!0,d.play()):0<=d.loops&&d.audio.ended&&(d.__PRIVATE__.__loopCount++,(0==d.loops||0<d.loops&&d.__PRIVATE__.__loopCount<d.loops)&&d.play()))};this.play=function(){d.audio&&(d.audio.ended=!1,d.audio.paused=!1,d.setCurrentTime(0),d.audio.play())};this.pause=function(){d.audio&&(d.audio.pause(),d.audio.ended=!1,d.audio.paused=!0)};this.stop=function(){d.audio&&(d.audio.pause(),d.audio.ended=!1,d.audio.paused=!0,d.__PRIVATE__.__loopCount=0,d.__PRIVATE__.__firstPlayed=!0,d.setCurrentTime(0))};this.duration=
function(){return d.audio?d.audio.duration:0};this.paused=function(){return d.audio?d.audio.paused:!0};this.ended=function(){return d.audio?d.audio.ended:!0};this.getCurrentTime=function(){return d.audio?d.audio.currentTime:0};this.setCurrentTime=function(a){d.audio&&4==d.audio.readyState&&(d.audio.currentTime=a)};this.src="";this.audio=null;this.autoplay=!1;this.loops=0;this.__PRIVATE__.__firstPlayed=!1;this.__PRIVATE__.__loopCount=0;this.Destructor=function(){d.audio&&(d.audio.pause(),d.audio&&
(d.audio.hasOwnProperty("Destructor")&&d.audio.Destructor()||!d.audio.hasOwnProperty("Destructor"))&&delete d.audio,d.audio=null);d.src=null;d.audio=null;d.autoplay=null;d.loops=null;d.__PRIVATE__.__firstPlayed=null;d.__PRIVATE__.__loopCount=null;return!0};this.Constructor=function(a,b,f){d.audio=new Audio(a);d.audio.autoplay=!1;d.audio.loop=!1;d.src=a;d.autoplay=b;d.loops=f;d.__PRIVATE__.__firstPlayed=!1;d.__PRIVATE__.__loopCount=0};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(b,c,
e);return this}(null,g,b,c)}CocoAudio.prototype={};CocoAudio.prototype.__PRIVATE__={};CocoAudio.prototype.__PROTECTED__={};
function CocoClip(g){return new function(b,c){var a=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.prepare=function(b){a.__timeline.prepare(b,a);for(var c=a.__children.size()-1;0<=c;c--)a.__children[c].prepare(b)};this.setText=function(a){};this.createTextTexture=function(b,c,e,d,g,k,q,p,m,r){a.text=b;a.textFontName=c;a.textFontSize=e;a.textHAlign=
d;a.textVAlign=g;a.textMultiline=k;a.textTrimming=q;a.textColor=p;a.textWidth=m;a.textHeight=r;a.__image&&(a.__image.hasOwnProperty("Destructor")&&a.__image.Destructor()||!a.__image.hasOwnProperty("Destructor"))&&delete a.__image;a.__image=null;d=document.createElement("canvas");d.width=Math.pow(2,Math.ceil(Math.log(m)/Math.log(2)));d.height=Math.pow(2,Math.ceil(Math.log(r)/Math.log(2)));g=d.getContext("2d");g.font="normal normal normal "+e+"px / normal "+c;g.fillStyle="white";g.fillText(b,0,e);a.__image=
new CocoImage;a.__image.image=new Image;b=d.toDataURL();a.__image.image.load(b);a.__image.textureCellWidth=m;a.__image.textureCellHeight=r;a.__image.textureGrid=new Float32Array([0,0]);a.__image.prepare(a.__scene,gl)};this.reset=function(){a.__currentFrame&&(a.__currentFrame&&(a.__currentFrame.hasOwnProperty("Destructor")&&a.__currentFrame.Destructor()||!a.__currentFrame.hasOwnProperty("Destructor"))&&delete a.__currentFrame,a.__currentFrame=null);a.__currentFrame=null;a.__currentTime=0;a.__timeline.reset();
for(var b=a.__children.size()-1;0<=b;b--)a.__children[b].reset();a.__PRIVATE__.__currentAudio&&a.__PRIVATE__.__currentAudio.reset()};this.addChild=function(b){if(!b)return null;if(!b.__instanceName)throw"Invalid instance name.";a.__children.push(b);a.__PRIVATE__.normalize();b.__clipPath=(a.__clipPath?a.__clipPath:a.__instanceName)+"/"+b.__instanceName;return b};this.removeChild=function(b){if(!b)return null;a.__children.splice(a.getChildIndex(b),1);a.__PRIVATE__.normalize();return b};this.__PRIVATE__.normalize=
function(){a.__childWithMaxTimelineDuration=null;for(var b=a.__children.size()-1;0<=b;b--)a.__childWithMaxTimelineDuration?a.__children[b].__timeline.__durationInTime>a.__childWithMaxTimelineDuration.__timeline.__durationInTime&&(a.__childWithMaxTimelineDuration=a.__children[b]):a.__childWithMaxTimelineDuration=a.__children[b]};this.getChildByName=function(b){for(var c=a.__children.size()-1;0<=c;c--)if(a.__children[c].__instanceName==b)return a.__children[c];return null};this.getChildIndex=function(b){if(b)for(var c=
a.__children.size()-1;0<=c;c--)if(a.__children[c]==b)return c;return-1};this.gotoFrameByName=function(b,c){var e=a.__timeline.findLabelByName(b);return e?a.gotoFrameByIndex(e.frameIndex,c):!1};this.gotoFrameByIndex=function(b,c){for(var e,d=a.__children.size()-1;0<=d;d--)e=a.__children[d],b==COCO_STOP_ON_CURRENT_FRAME&&(b=e.__currentFrame?e.__currentFrame.frameIndex:0),e.__timeline.__paused=c,e.__timeline.__currentFrameIndex=-1,e.__currentTime=b*e.__timeline.__singleFrameDurationTime;return!0};this.__PRIVATE__.__advanceTime=
function(b){a.__timeline.__paused||(a.__currentTime+=engine.TICK_TIME)};this.paint=function(b,c,e,d,g){a.__scene=c;var k=engine.getTouchEvent();k&&"touchend"!=k.type&&"mouseup"!=k.type&&(k=null);var q=e?e.__childWithMaxTimelineDuration.__timeline.__durationInTime:a.__timeline.__singleFrameDurationTime;if(e){a.__loops=Math.floor(a.__currentTime/q);a.__loopTime=a.__currentTime-a.__loops*q;var p=a.__loopTime/a.__timeline.__singleFrameDurationTime;a.__currentFrame&&(a.__currentFrame&&(a.__currentFrame.hasOwnProperty("Destructor")&&
a.__currentFrame.Destructor()||!a.__currentFrame.hasOwnProperty("Destructor"))&&delete a.__currentFrame,a.__currentFrame=null);a.__currentFrame=a.__timeline.interpolate(p);if(!a.__currentFrame)return;a.__currentFrame.combine(e.__currentFrame);if(0==a.__currentFrame.alpha||!a.__currentFrame.visible){a.__PRIVATE__.__advanceTime(q);return}d=(a.__currentFrame.handleEvents||d)&&null!=k}if(a.__image)a.__currentFrame.scaleX*=a.__image.__pixelRatioScale,a.__currentFrame.scaleY*=a.__image.__pixelRatioScale,
a.__currentFrame.apply(c.__modelViewMatrix),a.__currentFrame.scaleX/=a.__image.__pixelRatioScale,a.__currentFrame.scaleY/=a.__image.__pixelRatioScale,g=a.__currentFrame.spriteSequenceName,!g&&e&&e.__currentFrame&&(g=e.__currentFrame.spriteSequenceName),g?a.__PRIVATE__.__currentSequence&&a.__PRIVATE__.__currentSequence.name==g||(a.__PRIVATE__.__currentSequence=a.__image.getSequence(g),a.__PRIVATE__.__currentSequence.sequenceStartTime=a.__currentTime):a.__PRIVATE__.__currentSequence=null,a.__image.isSpriteSheet&&
a.__PRIVATE__.__currentSequence?(g=a.__timeline.__paused?0:Math.floor((a.__currentTime-a.__PRIVATE__.__currentSequence.sequenceStartTime)/(1E3/c.__fps))%a.__PRIVATE__.__currentSequence.frames.size(),c.drawFrame(b,a.__image,a.__PRIVATE__.__currentSequence.frames[g],a.__currentFrame)):c.drawFrame(b,a.__image,0,a.__currentFrame);else if(p=a.__children.size(),0<p){var m;c.__levelParents.push(a);a.__currentFrame&&a.__currentFrame.apply(c.__modelViewMatrix);for(var r=0;r<p;r++)c.__modelViewMatrix.push(),
m=a.__children[r],m.paint(b,c,a,d,g+1),c.__modelViewMatrix.pop();c.__levelParents.pop()}a!=c.__root&&(d&&(a.__image?a.initBoundingBoxFromTexture(c,a.__image.textureCellWidth/2,a.__image.textureCellHeight/2):0<a.__children.size()&&a.initBoundingBoxFromChildren(c)),d&&a.__currentFrame.handleEvents&&a.hitTest((k.__clientX-b.canvas.width/2)/c.__view_scale,(k.__clientY-b.canvas.height/2)/c.__view_scale)&&engine.pushTouched(a),a.__timeline.__paused||(a.__parent=e,a.__currentFrame.action&&a.__currentFrame.action.call(c),
a.__currentFrame.nextState&&engine.setNextState(a.__currentFrame.nextState),a.__currentFrame.audio&&a.__currentFrame.audio.tick(),a.__currentFrame.audio&&(!a.__PRIVATE__.__currentAudio||a.__currentFrame.audio==a.__PRIVATE__.__currentAudio&&0==a.__PRIVATE__.__currentAudio.loops||a.__PRIVATE__.__currentAudio.reset(),a.__PRIVATE__.__currentAudio=a.__currentFrame.audio),a.__parent=null),a.__PRIVATE__.__currentAudio&&(a.__PRIVATE__.__currentAudio.tick(),a.__PRIVATE__.__currentAudio.ended()&&(a.__PRIVATE__.__currentAudio.reset(),
a.__PRIVATE__.__currentAudio=null)));a.__PRIVATE__.__advanceTime(q)};this.hitTest=function(b,c){return 0<((b-a.__vABS_TOP_LEFT.X)*(a.__vABS_TOP_RIGHT.Y-a.__vABS_TOP_LEFT.Y)-(a.__vABS_TOP_RIGHT.X-a.__vABS_TOP_LEFT.X)*(c-a.__vABS_TOP_LEFT.Y))*((b-a.__vABS_BOTTOM_RIGHT.X)*(a.__vABS_BOTTOM_LEFT.Y-a.__vABS_BOTTOM_RIGHT.Y)-(a.__vABS_BOTTOM_LEFT.X-a.__vABS_BOTTOM_RIGHT.X)*(c-a.__vABS_BOTTOM_RIGHT.Y))&&0<((b-a.__vABS_TOP_RIGHT.X)*(a.__vABS_BOTTOM_RIGHT.Y-a.__vABS_TOP_RIGHT.Y)-(a.__vABS_BOTTOM_RIGHT.X-a.__vABS_TOP_RIGHT.X)*
(c-a.__vABS_TOP_RIGHT.Y))*((b-a.__vABS_BOTTOM_LEFT.X)*(a.__vABS_TOP_LEFT.Y-a.__vABS_BOTTOM_LEFT.Y)-(a.__vABS_TOP_LEFT.X-a.__vABS_BOTTOM_LEFT.X)*(c-a.__vABS_BOTTOM_LEFT.Y))};this.initBoundingBoxFromTexture=function(b,c,e){a.__mTemp.identity();a.__currentFrame.scaleX*=a.__image.__pixelRatioScale;a.__currentFrame.scaleY*=a.__image.__pixelRatioScale;a.__currentFrame.apply(a.__mTemp);a.__currentFrame.scaleX/=a.__image.__pixelRatioScale;a.__currentFrame.scaleY/=a.__image.__pixelRatioScale;a.__vTemp.reset(-c,
-e,0,1);a.__vREL_TOP_LEFT=a.__mTemp.multiplyByVector(a.__vTemp);a.__vABS_TOP_LEFT=b.__modelViewMatrix.multiplyByVector(a.__vTemp);a.__vTemp.reset(c,-e,0,1);a.__vREL_TOP_RIGHT=a.__mTemp.multiplyByVector(a.__vTemp);a.__vABS_TOP_RIGHT=b.__modelViewMatrix.multiplyByVector(a.__vTemp);a.__vTemp.reset(-c,e,0,1);a.__vREL_BOTTOM_LEFT=a.__mTemp.multiplyByVector(a.__vTemp);a.__vABS_BOTTOM_LEFT=b.__modelViewMatrix.multiplyByVector(a.__vTemp);a.__vTemp.reset(c,e,0,1);a.__vREL_BOTTOM_RIGHT=a.__mTemp.multiplyByVector(a.__vTemp);
a.__vABS_BOTTOM_RIGHT=b.__modelViewMatrix.multiplyByVector(a.__vTemp);a.__hasBoundingBox=!0};this.initBoundingBoxFromChildren=function(b){a.__hasBoundingBox=!1;if(0!=a.__children.size()){a.__vREL_TOP_LEFT.X=1E5;a.__vREL_TOP_RIGHT.X=-1E5;a.__vREL_TOP_LEFT.Y=1E5;a.__vREL_BOTTOM_LEFT.Y=-1E5;for(var c,e=0,d=a.__children.size();e<d;e++)c=a.__children[e],c.__hasBoundingBox&&(c.__vREL_TOP_LEFT.X<a.__vREL_TOP_LEFT.X&&(a.__vREL_TOP_LEFT.X=c.__vREL_TOP_LEFT.X),c.__vREL_TOP_LEFT.X>a.__vREL_TOP_RIGHT.X&&(a.__vREL_TOP_RIGHT.X=
c.__vREL_TOP_LEFT.X),c.__vREL_TOP_LEFT.Y<a.__vREL_TOP_LEFT.Y&&(a.__vREL_TOP_LEFT.Y=c.__vREL_TOP_LEFT.Y),c.__vREL_TOP_LEFT.Y>a.__vREL_BOTTOM_LEFT.Y&&(a.__vREL_BOTTOM_LEFT.Y=c.__vREL_TOP_LEFT.Y),c.__vREL_TOP_RIGHT.X<a.__vREL_TOP_LEFT.X&&(a.__vREL_TOP_LEFT.X=c.__vREL_TOP_RIGHT.X),c.__vREL_TOP_RIGHT.X>a.__vREL_TOP_RIGHT.X&&(a.__vREL_TOP_RIGHT.X=c.__vREL_TOP_RIGHT.X),c.__vREL_TOP_RIGHT.Y<a.__vREL_TOP_LEFT.Y&&(a.__vREL_TOP_LEFT.Y=c.__vREL_TOP_RIGHT.Y),c.__vREL_TOP_RIGHT.Y>a.__vREL_BOTTOM_LEFT.Y&&(a.__vREL_BOTTOM_LEFT.Y=
c.__vREL_TOP_RIGHT.Y),c.__vREL_BOTTOM_LEFT.X<a.__vREL_TOP_LEFT.X&&(a.__vREL_TOP_LEFT.X=c.__vREL_BOTTOM_LEFT.X),c.__vREL_BOTTOM_LEFT.X>a.__vREL_TOP_RIGHT.X&&(a.__vREL_TOP_RIGHT.X=c.__vREL_BOTTOM_LEFT.X),c.__vREL_BOTTOM_LEFT.Y<a.__vREL_TOP_LEFT.Y&&(a.__vREL_TOP_LEFT.Y=c.__vREL_BOTTOM_LEFT.Y),c.__vREL_BOTTOM_LEFT.Y>a.__vREL_BOTTOM_LEFT.Y&&(a.__vREL_BOTTOM_LEFT.Y=c.__vREL_BOTTOM_LEFT.Y),c.__vREL_BOTTOM_RIGHT.X<a.__vREL_TOP_LEFT.X&&(a.__vREL_TOP_LEFT.X=c.__vREL_BOTTOM_RIGHT.X),c.__vREL_BOTTOM_RIGHT.X>
a.__vREL_TOP_RIGHT.X&&(a.__vREL_TOP_RIGHT.X=c.__vREL_BOTTOM_RIGHT.X),c.__vREL_BOTTOM_RIGHT.Y<a.__vREL_TOP_LEFT.Y&&(a.__vREL_TOP_LEFT.Y=c.__vREL_BOTTOM_RIGHT.Y),c.__vREL_BOTTOM_RIGHT.Y>a.__vREL_BOTTOM_LEFT.Y&&(a.__vREL_BOTTOM_LEFT.Y=c.__vREL_BOTTOM_RIGHT.Y));a.__vREL_TOP_RIGHT.Y=a.__vREL_TOP_LEFT.Y;a.__vREL_BOTTOM_LEFT.X=a.__vREL_TOP_LEFT.X;a.__vREL_BOTTOM_RIGHT.X=a.__vREL_TOP_RIGHT.X;a.__vREL_BOTTOM_RIGHT.Y=a.__vREL_BOTTOM_LEFT.Y;a.__vABS_TOP_LEFT=b.__modelViewMatrix.multiplyByVector(a.__vREL_TOP_LEFT);
a.__vABS_TOP_RIGHT=b.__modelViewMatrix.multiplyByVector(a.__vREL_TOP_RIGHT);a.__vABS_BOTTOM_LEFT=b.__modelViewMatrix.multiplyByVector(a.__vREL_BOTTOM_LEFT);a.__vABS_BOTTOM_RIGHT=b.__modelViewMatrix.multiplyByVector(a.__vREL_BOTTOM_RIGHT);a.__mTemp.identity();a.__currentFrame.apply(a.__mTemp);a.__vREL_TOP_LEFT=a.__mTemp.multiplyByVector(a.__vREL_TOP_LEFT);a.__vREL_TOP_RIGHT=a.__mTemp.multiplyByVector(a.__vREL_TOP_RIGHT);a.__vREL_BOTTOM_LEFT=a.__mTemp.multiplyByVector(a.__vREL_BOTTOM_LEFT);a.__vREL_BOTTOM_RIGHT=
a.__mTemp.multiplyByVector(a.__vREL_BOTTOM_RIGHT);a.__hasBoundingBox=!0}};this.drawBoundingBox=function(b,c){a.__hasBoundingBox&&(c.disableVertexAttribArray(b.__glProgram.GLSLiTexCoords),c.disableVertexAttribArray(b.__glProgram.GLSLiVecCoords),c.useProgram(b.__boundingBoxProgram),c.enableVertexAttribArray(b.__boundingBoxProgram.GLSLiVec2Coords),c.bindBuffer(c.ARRAY_BUFFER,b.__boundingBoxBuffer),c.bufferSubData(c.ARRAY_BUFFER,0,new Float32Array([a.__vABS_TOP_LEFT.X,a.__vABS_TOP_LEFT.Y,a.__vABS_TOP_RIGHT.X,
a.__vABS_TOP_RIGHT.Y,a.__vABS_BOTTOM_RIGHT.X,a.__vABS_BOTTOM_RIGHT.Y,a.__vABS_BOTTOM_LEFT.X,a.__vABS_BOTTOM_LEFT.Y])),c.vertexAttribPointer(b.__boundingBoxProgram.GLSLiVec2Coords,2,c.FLOAT,!1,0,0),b.__projectionMatrix.update(c,b.__boundingBoxProgram.GLSLuProjMat),c.drawArrays(c.LINE_LOOP,0,4),c.bindBuffer(c.ARRAY_BUFFER,null),c.disableVertexAttribArray(b.__boundingBoxProgram.GLSLiVec2Coords),c.useProgram(b.__glProgram),c.enableVertexAttribArray(b.__glProgram.GLSLiTexCoords),c.enableVertexAttribArray(b.__glProgram.GLSLiVecCoords))};
this.__clipPath=this.__instanceName="";this.__symbolLoop=this.__image=this.__scene=null;this.__children=[];this.__parent=this.__timeline=null;this.textFontName=this.text="";this.textFontSize=0;this.textVAlign=this.textHAlign=null;this.textMultiline=!1;this.textTrimming=null;this.textColor="";this.textHeight=this.textWidth=0;this.__loopTime=this.__currentTime=null;this.__loops=0;this.__childWithMaxTimelineDuration=this.__currentFrame=null;this.__hasBoundingBox=!1;this.__mTemp=this.__vTemp=this.__vREL_BOTTOM_RIGHT=
this.__vREL_BOTTOM_LEFT=this.__vREL_TOP_RIGHT=this.__vREL_TOP_LEFT=this.__vABS_BOTTOM_RIGHT=this.__vABS_BOTTOM_LEFT=this.__vABS_TOP_RIGHT=this.__vABS_TOP_LEFT=null;this.__PRIVATE__.__currentSequence=null;this.__PRIVATE__.__currentAudio=null;this.Destructor=function(){a.__image&&(a.__image.hasOwnProperty("Destructor")&&a.__image.Destructor()||!a.__image.hasOwnProperty("Destructor"))&&delete a.__image;a.__image=null;var b=a.__children;if(b)for(var c=b.length;c--;)b[c]&&(b[c].hasOwnProperty("Destructor")&&
b[c].Destructor()||!b[c].hasOwnProperty("Destructor"))&&delete b[c],b[c]=null;a.__children&&(a.__children.hasOwnProperty("Destructor")&&a.__children.Destructor()||!a.__children.hasOwnProperty("Destructor"))&&delete a.__children;a.__children=null;a.__timeline&&(a.__timeline.hasOwnProperty("Destructor")&&a.__timeline.Destructor()||!a.__timeline.hasOwnProperty("Destructor"))&&delete a.__timeline;a.__timeline=null;a.__vABS_TOP_LEFT&&(a.__vABS_TOP_LEFT.hasOwnProperty("Destructor")&&a.__vABS_TOP_LEFT.Destructor()||
!a.__vABS_TOP_LEFT.hasOwnProperty("Destructor"))&&delete a.__vABS_TOP_LEFT;a.__vABS_TOP_LEFT=null;a.__vABS_TOP_RIGHT&&(a.__vABS_TOP_RIGHT.hasOwnProperty("Destructor")&&a.__vABS_TOP_RIGHT.Destructor()||!a.__vABS_TOP_RIGHT.hasOwnProperty("Destructor"))&&delete a.__vABS_TOP_RIGHT;a.__vABS_TOP_RIGHT=null;a.__vABS_BOTTOM_LEFT&&(a.__vABS_BOTTOM_LEFT.hasOwnProperty("Destructor")&&a.__vABS_BOTTOM_LEFT.Destructor()||!a.__vABS_BOTTOM_LEFT.hasOwnProperty("Destructor"))&&delete a.__vABS_BOTTOM_LEFT;a.__vABS_BOTTOM_LEFT=
null;a.__vABS_BOTTOM_RIGHT&&(a.__vABS_BOTTOM_RIGHT.hasOwnProperty("Destructor")&&a.__vABS_BOTTOM_RIGHT.Destructor()||!a.__vABS_BOTTOM_RIGHT.hasOwnProperty("Destructor"))&&delete a.__vABS_BOTTOM_RIGHT;a.__vABS_BOTTOM_RIGHT=null;a.__vREL_TOP_LEFT&&(a.__vREL_TOP_LEFT.hasOwnProperty("Destructor")&&a.__vREL_TOP_LEFT.Destructor()||!a.__vREL_TOP_LEFT.hasOwnProperty("Destructor"))&&delete a.__vREL_TOP_LEFT;a.__vREL_TOP_LEFT=null;a.__vREL_TOP_RIGHT&&(a.__vREL_TOP_RIGHT.hasOwnProperty("Destructor")&&a.__vREL_TOP_RIGHT.Destructor()||
!a.__vREL_TOP_RIGHT.hasOwnProperty("Destructor"))&&delete a.__vREL_TOP_RIGHT;a.__vREL_TOP_RIGHT=null;a.__vREL_BOTTOM_LEFT&&(a.__vREL_BOTTOM_LEFT.hasOwnProperty("Destructor")&&a.__vREL_BOTTOM_LEFT.Destructor()||!a.__vREL_BOTTOM_LEFT.hasOwnProperty("Destructor"))&&delete a.__vREL_BOTTOM_LEFT;a.__vREL_BOTTOM_LEFT=null;a.__vREL_BOTTOM_RIGHT&&(a.__vREL_BOTTOM_RIGHT.hasOwnProperty("Destructor")&&a.__vREL_BOTTOM_RIGHT.Destructor()||!a.__vREL_BOTTOM_RIGHT.hasOwnProperty("Destructor"))&&delete a.__vREL_BOTTOM_RIGHT;
a.__vREL_BOTTOM_RIGHT=null;a.__vTemp&&(a.__vTemp.hasOwnProperty("Destructor")&&a.__vTemp.Destructor()||!a.__vTemp.hasOwnProperty("Destructor"))&&delete a.__vTemp;a.__vTemp=null;a.__mTemp&&(a.__mTemp.hasOwnProperty("Destructor")&&a.__mTemp.Destructor()||!a.__mTemp.hasOwnProperty("Destructor"))&&delete a.__mTemp;a.__mTemp=null;a.__instanceName=null;a.__clipPath=null;a.__scene=null;a.__image=null;a.__symbolLoop=null;a.__children=null;a.__timeline=null;a.__parent=null;a.text=null;a.textFontName=null;
a.textFontSize=null;a.textHAlign=null;a.textVAlign=null;a.textMultiline=null;a.textTrimming=null;a.textColor=null;a.textWidth=null;a.textHeight=null;a.__currentTime=null;a.__loopTime=null;a.__loops=null;a.__currentFrame=null;a.__childWithMaxTimelineDuration=null;a.__hasBoundingBox=null;a.__vABS_TOP_LEFT=null;a.__vABS_TOP_RIGHT=null;a.__vABS_BOTTOM_LEFT=null;a.__vABS_BOTTOM_RIGHT=null;a.__vREL_TOP_LEFT=null;a.__vREL_TOP_RIGHT=null;a.__vREL_BOTTOM_LEFT=null;a.__vREL_BOTTOM_RIGHT=null;a.__vTemp=null;
a.__mTemp=null;a.__PRIVATE__.__currentSequence=null;a.__PRIVATE__.__currentAudio=null;return!0};this.Constructor=function(b){a.__symbolLoop=COCO_CLIP_SYMBOL_LOOP_ENUM.CLIP_SYMBOL_LOOP_CONTINUOUS;a.__timeline=new CocoTimeline;a.__children=[];a.__parent=null;a.__currentTime=0;a.__currentFrame=null;a.__hasBoundingBox=!1;a.__vABS_TOP_LEFT=new CocoVector;a.__vABS_TOP_RIGHT=new CocoVector;a.__vABS_BOTTOM_LEFT=new CocoVector;a.__vABS_BOTTOM_RIGHT=new CocoVector;a.__vREL_TOP_LEFT=new CocoVector;a.__vREL_TOP_RIGHT=
new CocoVector;a.__vREL_BOTTOM_LEFT=new CocoVector;a.__vREL_BOTTOM_RIGHT=new CocoVector;a.__vTemp=new CocoVector;a.__mTemp=new CocoMatrix;a.__childWithMaxTimelineDuration=null;a.__PRIVATE__.__currentSequence=null;a.__PRIVATE__.__currentAudio=null;a.__clipPath="";a.__image=b};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(c);return this}(null,g)}CocoClip.prototype={};CocoClip.prototype.__PRIVATE__={};CocoClip.prototype.__PROTECTED__={};
function CocoEngine(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.setNextState=function(c){b.__PRIVATE__.__nextState=c};this.run=function(c,a){if(b.__PRIVATE__.__currentState||b.__PRIVATE__.__nextState)null!=b.__PRIVATE__.__nextState&&(b.__PRIVATE__.__currentState&&b.__PRIVATE__.__currentState.exit(),b.__PRIVATE__.__currentState=
b.__PRIVATE__.__nextState,b.__PRIVATE__.__nextState=null,trace("\n@@STATE "+b.__PRIVATE__.__currentState.__name),b.__PRIVATE__.__clicked.clear(),b.__PRIVATE__.__currentState&&b.__PRIVATE__.__currentState.enter()),b.__PRIVATE__.__currentState&&b.__PRIVATE__.__currentState.tick(b.__PRIVATE__.__clock),b.__PRIVATE__.__clicked.clear(),null==b.__PRIVATE__.__nextState&&null!=b.__PRIVATE__.__currentState&&(c.clearColor(0,0,0,1),c.clear(c.COLOR_BUFFER_BIT),b.__PRIVATE__.__currentState.paint(c,b.__PRIVATE__.__clock)),
b.__PRIVATE__.__deviceEvent=null,b.__PRIVATE__.__clock+=b.TICK_TIME};this.__PRIVATE__.__setTouchEvent=function(c){b.__PRIVATE__.__deviceEvent=c;b.__PRIVATE__.__deviceEvent.__clientX=c.touches?c.touches[0].clientX:c.clientX;b.__PRIVATE__.__deviceEvent.__clientY=c.touches?c.touches[0].clientY:c.clientY};this.getTouchEvent=function(){return b.__PRIVATE__.__deviceEvent};this.pushTouched=function(c){trace("click: "+c.__instanceName);b.__PRIVATE__.__clicked.push(c)};this.isClicked=function(c){for(var a=
b.__PRIVATE__.__clicked.size()-1;0<=a;a--)for(var f=c.size()-1;0<=f;f--)if(c[f]==b.__PRIVATE__.__clicked[a])return f;return-1};this.__debug_trace=function(b,a,f){};this.TICK_TIME=1E3/60;this.debugbreak=!1;this.__PRIVATE__.__currentState=null;this.__PRIVATE__.__nextState=null;this.__PRIVATE__.__deviceEvent=null;this.__PRIVATE__.__clicked=[];this.__PRIVATE__.__clock=null;this.Destructor=function(){var c=b.__PRIVATE__.__clicked;if(c)for(var a=c.length;a--;)c[a]&&(c[a].hasOwnProperty("Destructor")&&c[a].Destructor()||
!c[a].hasOwnProperty("Destructor"))&&delete c[a],c[a]=null;b.__PRIVATE__.__clicked&&(b.__PRIVATE__.__clicked.hasOwnProperty("Destructor")&&b.__PRIVATE__.__clicked.Destructor()||!b.__PRIVATE__.__clicked.hasOwnProperty("Destructor"))&&delete b.__PRIVATE__.__clicked;b.__PRIVATE__.__clicked=null;b.TICK_TIME=null;b.debugbreak=null;b.__PRIVATE__.__currentState=null;b.__PRIVATE__.__nextState=null;b.__PRIVATE__.__deviceEvent=null;b.__PRIVATE__.__clicked=null;b.__PRIVATE__.__clock=null;return!0};this.Constructor=
function(){b.__PRIVATE__.__clicked=[];b.__PRIVATE__.__currentState=null;b.__PRIVATE__.__deviceEvent=null;b.__PRIVATE__.__clock=0;b.debugbreak=!1;window.addEventListener("mouseup",b.__PRIVATE__.__setTouchEvent);window.addEventListener("touchstart",b.__PRIVATE__.__setTouchEvent);window.addEventListener("touchmove",b.__PRIVATE__.__setTouchEvent);window.addEventListener("touchend",b.__PRIVATE__.__setTouchEvent)};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}(null)}
CocoEngine.prototype={};CocoEngine.prototype.__PRIVATE__={};CocoEngine.prototype.__PROTECTED__={};
function CocoImage(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.addSibling=function(c){b.viewSiblings.push(c);return c};this.addSequence=function(c){if(!c)return null;if(b.getSequence(c.name))throw"Sequence "+c.name+" already exists.";b.sequences.push(c);b.isSpriteSheet=!0;return c};this.getSequence=function(c){for(var a=
b.sequences.size()-1;0<=a;a--)if(b.sequences[a].name==c)return b.sequences[a];return null};this.prepare=function(c,a){b.__pixelRatioScale=c.__view_pixel_ratio/b.pixelRatio;var f=b.textureCellWidth/2,h=b.textureCellHeight/2;b.texSize=new Float32Array([b.textureCellWidth/b.image.naturalWidth,b.textureCellHeight/b.image.naturalHeight]);b.texture=a.createTexture();a.bindTexture(a.TEXTURE_2D,b.texture);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,b.image);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,
a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR_MIPMAP_NEAREST);a.generateMipmap(a.TEXTURE_2D);a.bindTexture(a.TEXTURE_2D,null);f=new Float32Array([0,0,-f,-h,0,1,-f,h,1,0,f,-h,1,1,f,h]);b.buffer=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,b.buffer);a.bufferData(a.ARRAY_BUFFER,f,a.STATIC_DRAW);a.bindBuffer(a.ARRAY_BUFFER,null)};this.symbolName="";this.image=
null;this.textureCellHeight=this.textureCellWidth=0;this.texSize=this.color=this.textureGrid=null;this.isSpriteSheet=!1;this.__pixelRatioScale=0;this.buffer=this.texture=null;this.sequences=[];this.baseUrl="";this.viewOptimalHeight=this.viewOptimalWidth=0;this.viewSiblings=[];this.pixelRatio=0;this.Destructor=function(){(function(b){if(b)for(var a=b.length;a--;)b[a]&&(b[a].hasOwnProperty("Destructor")&&b[a].Destructor()||!b[a].hasOwnProperty("Destructor"))&&delete b[a],b[a]=null})(b.viewSiblings);
b.viewSiblings&&(b.viewSiblings.hasOwnProperty("Destructor")&&b.viewSiblings.Destructor()||!b.viewSiblings.hasOwnProperty("Destructor"))&&delete b.viewSiblings;b.viewSiblings=null;(function(b){if(b)for(var a=b.length;a--;)b[a]&&(b[a].hasOwnProperty("Destructor")&&b[a].Destructor()||!b[a].hasOwnProperty("Destructor"))&&delete b[a],b[a]=null})(b.sequences);b.sequences&&(b.sequences.hasOwnProperty("Destructor")&&b.sequences.Destructor()||!b.sequences.hasOwnProperty("Destructor"))&&delete b.sequences;
b.sequences=null;b.texture&&(b.texture.hasOwnProperty("Destructor")&&b.texture.Destructor()||!b.texture.hasOwnProperty("Destructor"))&&delete b.texture;b.texture=null;b.textureGrid&&(b.textureGrid.hasOwnProperty("Destructor")&&b.textureGrid.Destructor()||!b.textureGrid.hasOwnProperty("Destructor"))&&delete b.textureGrid;b.textureGrid=null;b.color&&(b.color.hasOwnProperty("Destructor")&&b.color.Destructor()||!b.color.hasOwnProperty("Destructor"))&&delete b.color;b.color=null;b.texSize&&(b.texSize.hasOwnProperty("Destructor")&&
b.texSize.Destructor()||!b.texSize.hasOwnProperty("Destructor"))&&delete b.texSize;b.texSize=null;b.buffer&&(b.buffer.hasOwnProperty("Destructor")&&b.buffer.Destructor()||!b.buffer.hasOwnProperty("Destructor"))&&delete b.buffer;b.buffer=null;b.symbolName=null;b.image=null;b.textureCellWidth=null;b.textureCellHeight=null;b.textureGrid=null;b.color=null;b.texSize=null;b.isSpriteSheet=null;b.__pixelRatioScale=null;b.texture=null;b.buffer=null;b.sequences=null;b.baseUrl=null;b.viewOptimalWidth=null;b.viewOptimalHeight=
null;b.viewSiblings=null;b.pixelRatio=null;return!0};this.Constructor=function(){b.viewSiblings=[];b.sequences=[];b.image=null;b.symbolName="";b.texture=null;b.textureCellWidth=0;b.textureCellHeight=0;b.textureGrid=new Float32Array([0]);b.textureGrid=new Float32Array([0,0]);b.color=new Float32Array([1,1,1,1]);b.texSize=new Float32Array([1,1]);b.buffer=null;b.isSpriteSheet=!1;b.baseUrl="";b.viewOptimalWidth=0;b.viewOptimalHeight=0;b.pixelRatio=1};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();
return this}(null)}CocoImage.prototype={};CocoImage.prototype.__PRIVATE__={};CocoImage.prototype.__PROTECTED__={};
function CocoImageSibling(g,b,c,a){return new function(a,b,c,d,g){var k=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.url="";this.textureHeight=this.textureWidth=this.pixelRatio=0;this.Destructor=function(){k.url=null;k.pixelRatio=null;k.textureWidth=null;k.textureHeight=null;return!0};this.Constructor=function(a,b,c,f){k.url=a;k.pixelRatio=b;k.textureWidth=
c;k.textureHeight=f};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(b,c,d,g);return this}(null,g,b,c,a)}CocoImageSibling.prototype={};CocoImageSibling.prototype.__PRIVATE__={};CocoImageSibling.prototype.__PROTECTED__={};
function CocoKeyFrame(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.clone=function(c){var a=new CocoKeyFrame;a.filter=b.filter;a.red=b.red;a.green=b.green;a.blue=b.blue;a.alpha=b.alpha;a.frameIndex=b.frameIndex;a.frameInterpolation=b.frameInterpolation;a.handleEvents=b.handleEvents;a.pivotX=b.pivotX;a.pivotY=b.pivotY;
a.rotation=b.rotation;a.scaleX=b.scaleX;a.scaleY=b.scaleY;a.visible=b.visible;a.x=b.x;a.y=b.y;a.flipH=b.flipH;a.flipV=b.flipV;a.spriteSequenceName=b.spriteSequenceName;a.__frameIndex=b.frameIndex;a.__PRIVATE__.__isCloned=!0;c&&(b.action||b.nextState||b.audio)&&(a.action=b.action,a.nextState=b.nextState,a.audio=b.audio);return a};this.reset=function(){b.audio&&b.audio.reset()};this.interpolate=function(c,a,f){b.red=c.red+f*(a.red-c.red);b.green=c.green+f*(a.green-c.green);b.blue=c.blue+f*(a.blue-c.blue);
b.alpha=c.alpha+f*(a.alpha-c.alpha);b.x=c.x+f*(a.x-c.x);b.y=c.y+f*(a.y-c.y);b.scaleX=c.scaleX+f*(a.scaleX-c.scaleX);b.scaleY=c.scaleY+f*(a.scaleY-c.scaleY);b.rotation=c.rotation+f*(a.rotation-c.rotation);b.pivotX=c.pivotX+f*(a.pivotX-c.pivotX);b.pivotY=c.pivotY+f*(a.pivotY-c.pivotY)};this.combine=function(c){c&&(b.filter||(b.filter=c.filter),b.red*=c.red,b.green*=c.green,b.blue*=c.blue,b.alpha*=c.alpha,b.visible=b.visible&&c.visible,b.flipH=b.flipH&&!c.flipH||!b.flipH&&c.flipH,b.flipV=b.flipV&&!c.flipV||
!b.flipV&&c.flipV)};this.apply=function(c){0==b.x&&0==b.y||c.translate(b.x,b.y);0!=b.rotation&&c.rotateZ(b.rotation*RADIANS);1==b.scaleX&&1==b.scaleY||c.scale(b.scaleX,b.scaleY);0==b.pivotX&&0==b.pivotY||c.translate(-b.pivotX,-b.pivotY)};this.__frameIndex=this.frameIndex=0;this.frameInterpolation=null;this.visible=this.handleEvents=!1;this.rotation=this.scaleY=this.scaleX=this.pivotY=this.pivotX=this.y=this.x=this.alpha=this.blue=this.green=this.red=this.filter=0;this.audio=this.nextState=this.action=
null;this.flipV=this.flipH=!1;this.spriteSequenceName="";this.__PRIVATE__.__isCloned=!1;this.Destructor=function(){b.audio&&!b.__PRIVATE__.__isCloned&&(b.audio&&(b.audio.hasOwnProperty("Destructor")&&b.audio.Destructor()||!b.audio.hasOwnProperty("Destructor"))&&delete b.audio,b.audio=null);b.frameIndex=null;b.__frameIndex=null;b.frameInterpolation=null;b.handleEvents=null;b.visible=null;b.filter=null;b.red=null;b.green=null;b.blue=null;b.alpha=null;b.x=null;b.y=null;b.pivotX=null;b.pivotY=null;b.scaleX=
null;b.scaleY=null;b.rotation=null;b.action=null;b.nextState=null;b.audio=null;b.flipH=null;b.flipV=null;b.spriteSequenceName=null;b.__PRIVATE__.__isCloned=null;return!0};this.Constructor=function(){b.frameIndex=0;b.__frameIndex=0;b.frameInterpolation=COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN;b.handleEvents=!1;b.visible=!0;b.filter=0;b.x=0;b.y=0;b.scaleX=1;b.scaleY=1;b.rotation=0;b.pivotX=0;b.pivotY=0;b.red=1;b.green=1;b.blue=1;b.alpha=1;b.action=null;b.nextState=null;b.audio=
null;b.flipH=!1;b.flipV=!1;b.__PRIVATE__.__isCloned=!1;b.spriteSequenceName=""};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}(null)}CocoKeyFrame.prototype={};CocoKeyFrame.prototype.__PRIVATE__={};CocoKeyFrame.prototype.__PROTECTED__={};
function CocoMatrix(g){return new function(b,c){var a=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.identity=function(){a.rc11=1;a.rc12=0;a.rc13=0;a.rc14=0;a.rc21=0;a.rc22=1;a.rc23=0;a.rc24=0;a.rc31=0;a.rc32=0;a.rc33=1;a.rc34=0;a.rc41=0;a.rc42=0;a.rc43=0;a.rc44=1;a.__dirty=!0};this.ortho=function(b,c,e,d,g,k){a.rc11=2/(c-b);a.rc12=0;a.rc13=0;a.rc14=
0;a.rc21=0;a.rc22=2/(d-e);a.rc23=0;a.rc24=0;a.rc31=0;a.rc32=0;a.rc33=-2/(k-g);a.rc34=0;a.rc41=-(c+b)/(c-b);a.rc42=-(d+e)/(d-e);a.rc43=-(k+g)/(k-g);a.rc44=1;a.__dirty=!0};this.transpose=function(){var b=0,b=a.rc12;a.rc12=a.rc21;a.rc21=b;b=a.rc13;a.rc13=a.rc31;a.rc31=b;b=a.rc14;a.rc14=a.rc41;a.rc41=b;b=a.rc21;a.rc21=a.rc12;a.rc12=b;b=a.rc23;a.rc23=a.rc32;a.rc32=b;b=a.rc24;a.rc24=a.rc42;a.rc42=b;b=a.rc31;a.rc31=a.rc13;a.rc13=b;b=a.rc32;a.rc32=a.rc23;a.rc23=b;b=a.rc34;a.rc34=a.rc43;a.rc43=b;b=a.rc41;
a.rc41=a.rc14;a.rc14=b;b=a.rc42;a.rc42=a.rc24;a.rc24=b;b=a.rc43;a.rc43=a.rc34;a.rc34=b;a.__dirty=!0};this.determinant=function(){return a.rc14*a.rc23*a.rc32*a.rc41-a.rc13*a.rc24*a.rc32*a.rc41-a.rc14*a.rc22*a.rc33*a.rc41+a.rc12*a.rc24*a.rc33*a.rc41+a.rc13*a.rc22*a.rc34*a.rc41-a.rc12*a.rc23*a.rc34*a.rc41-a.rc14*a.rc23*a.rc31*a.rc42+a.rc13*a.rc24*a.rc31*a.rc42+a.rc14*a.rc21*a.rc33*a.rc42-a.rc11*a.rc24*a.rc33*a.rc42-a.rc13*a.rc21*a.rc34*a.rc42+a.rc11*a.rc23*a.rc34*a.rc42+a.rc14*a.rc22*a.rc31*a.rc43-a.rc12*
a.rc24*a.rc31*a.rc43-a.rc14*a.rc21*a.rc32*a.rc43+a.rc11*a.rc24*a.rc32*a.rc43+a.rc12*a.rc21*a.rc34*a.rc43-a.rc11*a.rc22*a.rc34*a.rc43-a.rc13*a.rc22*a.rc31*a.rc44+a.rc12*a.rc23*a.rc31*a.rc44+a.rc13*a.rc21*a.rc32*a.rc44-a.rc11*a.rc23*a.rc32*a.rc44-a.rc12*a.rc21*a.rc33*a.rc44+a.rc11*a.rc22*a.rc33*a.rc44};this.invert=function(){var b=a.determinant();if(0!=b){var c=a.rc14*a.rc33*a.rc42-a.rc13*a.rc34*a.rc42-a.rc14*a.rc32*a.rc43+a.rc12*a.rc34*a.rc43+a.rc13*a.rc32*a.rc44-a.rc12*a.rc33*a.rc44,e=a.rc13*a.rc24*
a.rc42-a.rc14*a.rc23*a.rc42+a.rc14*a.rc22*a.rc43-a.rc12*a.rc24*a.rc43-a.rc13*a.rc22*a.rc44+a.rc12*a.rc23*a.rc44,d=a.rc14*a.rc23*a.rc32-a.rc13*a.rc24*a.rc32-a.rc14*a.rc22*a.rc33+a.rc12*a.rc24*a.rc33+a.rc13*a.rc22*a.rc34-a.rc12*a.rc23*a.rc34,g=a.rc24*a.rc33*a.rc41-a.rc23*a.rc34*a.rc41-a.rc24*a.rc31*a.rc43+a.rc21*a.rc34*a.rc43+a.rc23*a.rc31*a.rc44-a.rc21*a.rc33*a.rc44,k=a.rc13*a.rc34*a.rc41-a.rc14*a.rc33*a.rc41+a.rc14*a.rc31*a.rc43-a.rc11*a.rc34*a.rc43-a.rc13*a.rc31*a.rc44+a.rc11*a.rc33*a.rc44,q=a.rc14*
a.rc23*a.rc41-a.rc13*a.rc24*a.rc41-a.rc14*a.rc21*a.rc43+a.rc11*a.rc24*a.rc43+a.rc13*a.rc21*a.rc44-a.rc11*a.rc23*a.rc44,p=a.rc13*a.rc24*a.rc31-a.rc14*a.rc23*a.rc31+a.rc14*a.rc21*a.rc33-a.rc11*a.rc24*a.rc33-a.rc13*a.rc21*a.rc34+a.rc11*a.rc23*a.rc34,m=a.rc22*a.rc34*a.rc41-a.rc24*a.rc32*a.rc41+a.rc24*a.rc31*a.rc42-a.rc21*a.rc34*a.rc42-a.rc22*a.rc31*a.rc44+a.rc21*a.rc32*a.rc44,r=a.rc14*a.rc32*a.rc41-a.rc12*a.rc34*a.rc41-a.rc14*a.rc31*a.rc42+a.rc11*a.rc34*a.rc42+a.rc12*a.rc31*a.rc44-a.rc11*a.rc32*a.rc44,
v=a.rc12*a.rc24*a.rc41-a.rc14*a.rc22*a.rc41+a.rc14*a.rc21*a.rc42-a.rc11*a.rc24*a.rc42-a.rc12*a.rc21*a.rc44+a.rc11*a.rc22*a.rc44,w=a.rc14*a.rc22*a.rc31-a.rc12*a.rc24*a.rc31-a.rc14*a.rc21*a.rc32+a.rc11*a.rc24*a.rc32+a.rc12*a.rc21*a.rc34-a.rc11*a.rc22*a.rc34,x=a.rc23*a.rc32*a.rc41-a.rc22*a.rc33*a.rc41-a.rc23*a.rc31*a.rc42+a.rc21*a.rc33*a.rc42+a.rc22*a.rc31*a.rc43-a.rc21*a.rc32*a.rc43,u=a.rc12*a.rc33*a.rc41-a.rc13*a.rc32*a.rc41+a.rc13*a.rc31*a.rc42-a.rc11*a.rc33*a.rc42-a.rc12*a.rc31*a.rc43+a.rc11*a.rc32*
a.rc43,s=a.rc13*a.rc22*a.rc41-a.rc12*a.rc23*a.rc41-a.rc13*a.rc21*a.rc42+a.rc11*a.rc23*a.rc42+a.rc12*a.rc21*a.rc43-a.rc11*a.rc22*a.rc43,t=a.rc12*a.rc23*a.rc31-a.rc13*a.rc22*a.rc31+a.rc13*a.rc21*a.rc32-a.rc11*a.rc23*a.rc32-a.rc12*a.rc21*a.rc33+a.rc11*a.rc22*a.rc33;a.rc11=(a.rc23*a.rc34*a.rc42-a.rc24*a.rc33*a.rc42+a.rc24*a.rc32*a.rc43-a.rc22*a.rc34*a.rc43-a.rc23*a.rc32*a.rc44+a.rc22*a.rc33*a.rc44)/b;a.rc12=c/b;a.rc13=e/b;a.rc14=d/b;a.rc21=g/b;a.rc22=k/b;a.rc23=q/b;a.rc24=p/b;a.rc31=m/b;a.rc32=r/b;a.rc33=
v/b;a.rc34=w/b;a.rc41=x/b;a.rc42=u/b;a.rc43=s/b;a.rc44=t/b;a.__dirty=!0}};this.multiplyByVector=function(b){var c=new CocoVector;c.X=b.X*a.rc11+b.Y*a.rc21+b.Z*a.rc31+b.W*a.rc41;c.Y=b.X*a.rc12+b.Y*a.rc22+b.Z*a.rc32+b.W*a.rc42;c.Z=b.X*a.rc13+b.Y*a.rc23+b.Z*a.rc33+b.W*a.rc43;c.W=b.X*a.rc14+b.Y*a.rc24+b.Z*a.rc34+b.W*a.rc44;return c};this.multiplyByMatrix=function(b){var c=new CocoMatrix;c.rc11=a.rc11*b.rc11+a.rc21*b.rc12+a.rc31*b.rc13+a.rc41*b.rc14;c.rc12=a.rc12*b.rc11+a.rc22*b.rc12+a.rc32*b.rc13+a.rc42*
b.rc14;c.rc13=a.rc13*b.rc11+a.rc23*b.rc12+a.rc33*b.rc13+a.rc43*b.rc14;c.rc14=a.rc14*b.rc11+a.rc24*b.rc12+a.rc34*b.rc13+a.rc44*b.rc14;c.rc21=a.rc11*b.rc21+a.rc21*b.rc22+a.rc31*b.rc23+a.rc41*b.rc24;c.rc22=a.rc12*b.rc21+a.rc22*b.rc22+a.rc32*b.rc23+a.rc42*b.rc24;c.rc23=a.rc13*b.rc21+a.rc23*b.rc22+a.rc33*b.rc23+a.rc43*b.rc24;c.rc24=a.rc14*b.rc21+a.rc24*b.rc22+a.rc34*b.rc23+a.rc44*b.rc24;c.rc31=a.rc11*b.rc31+a.rc21*b.rc32+a.rc31*b.rc33+a.rc41*b.rc34;c.rc32=a.rc12*b.rc31+a.rc22*b.rc32+a.rc32*b.rc33+a.rc42*
b.rc34;c.rc33=a.rc13*b.rc31+a.rc23*b.rc32+a.rc33*b.rc33+a.rc43*b.rc34;c.rc34=a.rc14*b.rc31+a.rc24*b.rc32+a.rc34*b.rc33+a.rc44*b.rc34;c.rc41=a.rc11*b.rc41+a.rc21*b.rc42+a.rc31*b.rc43+a.rc41*b.rc44;c.rc42=a.rc12*b.rc41+a.rc22*b.rc42+a.rc32*b.rc43+a.rc42*b.rc44;c.rc43=a.rc13*b.rc41+a.rc23*b.rc42+a.rc33*b.rc43+a.rc43*b.rc44;c.rc44=a.rc14*b.rc41+a.rc24*b.rc42+a.rc34*b.rc43+a.rc44*b.rc44;c.__dirty=!0;return c};this.translate=function(b,c){a.rc41+=a.rc11*b+a.rc21*c;a.rc42+=a.rc12*b+a.rc22*c;a.rc43+=a.rc13*
b+a.rc23*c;a.__dirty=!0};this.scale=function(b,c){a.rc11*=b;a.rc21*=c;a.rc12*=b;a.rc22*=c;a.rc13*=b;a.rc23*=c;a.rc14*=b;a.rc24*=c;a.__dirty=!0};this.rotateZ=function(b){var c=Math.cos(b);b=Math.sin(b);var e=0,d=0,e=a.rc11,d=a.rc21;a.rc11=e*c+d*b;a.rc21=-e*b+d*c;e=a.rc12;d=a.rc22;a.rc12=e*c+d*b;a.rc22=-e*b+d*c;e=a.rc13;d=a.rc23;a.rc13=e*c+d*b;a.rc23=-e*b+d*c;e=a.rc14;d=a.rc24;a.rc14=e*c+d*b;a.rc24=-e*b+d*c;a.__dirty=!0};this.refresh=function(){a.__data[0]=a.rc11;a.__data[1]=a.rc12;a.__data[2]=a.rc13;
a.__data[3]=a.rc14;a.__data[4]=a.rc21;a.__data[5]=a.rc22;a.__data[6]=a.rc23;a.__data[7]=a.rc24;a.__data[8]=a.rc31;a.__data[9]=a.rc32;a.__data[10]=a.rc33;a.__data[11]=a.rc34;a.__data[12]=a.rc41;a.__data[13]=a.rc42;a.__data[14]=a.rc43;a.__data[15]=a.rc44;a.__dirty=!1};this.update=function(b,c){b&&c&&(a.__dirty&&a.refresh(),b.uniformMatrix4fv(c,!1,a.__data))};this.push=function(){a.__stack.push(new Float32Array([a.rc11,a.rc12,a.rc13,a.rc14,a.rc21,a.rc22,a.rc23,a.rc24,a.rc31,a.rc32,a.rc33,a.rc34,a.rc41,
a.rc42,a.rc43,a.rc44]))};this.pop=function(){if(a.__stack.size()){var b=a.__stack.pop();a.rc11=b[0];a.rc12=b[1];a.rc13=b[2];a.rc14=b[3];a.rc21=b[4];a.rc22=b[5];a.rc23=b[6];a.rc24=b[7];a.rc31=b[8];a.rc32=b[9];a.rc33=b[10];a.rc34=b[11];a.rc41=b[12];a.rc42=b[13];a.rc43=b[14];a.rc44=b[15];a.__dirty=!0;b&&(b.hasOwnProperty("Destructor")&&b.Destructor()||!b.hasOwnProperty("Destructor"))&&delete b}};this.rc44=this.rc43=this.rc42=this.rc41=this.rc34=this.rc33=this.rc32=this.rc31=this.rc24=this.rc23=this.rc22=
this.rc21=this.rc14=this.rc13=this.rc12=this.rc11=0;this.__stack=[];this.__data=null;this.__dirty=!1;this.Destructor=function(){var b=a.__stack;if(b)for(var c=b.length;c--;)b[c]&&(b[c].hasOwnProperty("Destructor")&&b[c].Destructor()||!b[c].hasOwnProperty("Destructor"))&&delete b[c],b[c]=null;a.__stack&&(a.__stack.hasOwnProperty("Destructor")&&a.__stack.Destructor()||!a.__stack.hasOwnProperty("Destructor"))&&delete a.__stack;a.__stack=null;a.__data&&(a.__data.hasOwnProperty("Destructor")&&a.__data.Destructor()||
!a.__data.hasOwnProperty("Destructor"))&&delete a.__data;a.__data=null;a.rc11=null;a.rc12=null;a.rc13=null;a.rc14=null;a.rc21=null;a.rc22=null;a.rc23=null;a.rc24=null;a.rc31=null;a.rc32=null;a.rc33=null;a.rc34=null;a.rc41=null;a.rc42=null;a.rc43=null;a.rc44=null;a.__stack=null;a.__data=null;a.__dirty=null;return!0};this.Constructor=function(b){b?(a.rc11=b.rc11,a.rc12=b.rc12,a.rc13=b.rc13,a.rc14=b.rc14,a.rc21=b.rc21,a.rc22=b.rc22,a.rc23=b.rc23,a.rc24=b.rc24,a.rc31=b.rc31,a.rc32=b.rc32,a.rc33=b.rc33,
a.rc34=b.rc34,a.rc41=b.rc41,a.rc42=b.rc42,a.rc43=b.rc43,a.rc44=b.rc44):a.identity();a.__data=new Float32Array([a.rc11,a.rc12,a.rc13,a.rc14,a.rc21,a.rc22,a.rc23,a.rc24,a.rc31,a.rc32,a.rc33,a.rc34,a.rc41,a.rc42,a.rc43,a.rc44]);a.__stack=[];a.__dirty=!1};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(c);return this}(null,g)}CocoMatrix.prototype={};CocoMatrix.prototype.__PRIVATE__={};CocoMatrix.prototype.__PROTECTED__={};
function CocoRect(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.bottom=this.right=this.top=this.left=0;this.Destructor=function(){b.left=null;b.top=null;b.right=null;b.bottom=null;return!0};this.Constructor=function(){};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}(null)}
CocoRect.prototype={};CocoRect.prototype.__PRIVATE__={};CocoRect.prototype.__PROTECTED__={};
function CocoScene(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.getImageSymbol=function(c){for(var a=b.__imageSymbols.size()-1;0<=a;a--)if(b.__imageSymbols[a].symbolName==c)return b.__imageSymbols[a];return null};this.newResourceImage=function(c,a){if(b.getImageSymbol(c))throw"Resource image "+c+" already exists.";
var f=new CocoImage;f.symbolName=c;f.baseUrl=a;b.__imageSymbols.push(f);return f};this.__PRIVATE__.prepare=function(c){c.disable(c.DEPTH_TEST);c.enable(c.BLEND);c.blendFunc(c.SRC_ALPHA,c.ONE_MINUS_SRC_ALPHA);c.disable(c.CULL_FACE);b.__view_scale=0<b.__view_width&&0<b.__view_height?Math.min(c.canvas.width/b.__view_width,c.canvas.height/b.__view_height):window.devicePixelRatio;if(window.deviceRotation){var a=Math.cos(window.deviceRotation),f=Math.sin(window.deviceRotation),h=Math.abs(a*c.canvas.width+
f*c.canvas.height),a=Math.abs(-f*c.canvas.width+a*c.canvas.height);b.__projectionMatrix.ortho(-h/2,h/2,a/2,-a/2,-1,1);b.__projectionMatrix.rotateZ(-window.deviceRotation)}else b.__projectionMatrix.ortho(-(c.canvas.width/2),c.canvas.width/2,c.canvas.height/2,-(c.canvas.height/2),-1,1);b.__projectionMatrix.scale(b.__view_scale,b.__view_scale);b.__boundingBoxProgram=b.__PRIVATE__.makeProgram(c,b.__boundingBoxVertexShader,b.__boundingBoxFragmentShader);c.useProgram(b.__boundingBoxProgram);b.__boundingBoxProgram.GLSLiVec2Coords=
c.getAttribLocation(b.__boundingBoxProgram,"iVec2Coords");b.__boundingBoxProgram.GLSLuProjMat=c.getUniformLocation(b.__boundingBoxProgram,"uProjMat");b.__boundingBoxBuffer=c.createBuffer();c.bindBuffer(c.ARRAY_BUFFER,b.__boundingBoxBuffer);c.bufferData(c.ARRAY_BUFFER,new Float32Array([0,0,0,0,0,0,0,0]),c.DYNAMIC_DRAW);b.__glProgram_Simple=b.__PRIVATE__.makeProgram(c,b.__vertex_shader_Common,b.__fragment_shader_Simple);c.useProgram(b.__glProgram_Simple);b.__glProgram_Simple.GLSLiVecCoords=c.getAttribLocation(b.__glProgram_Simple,
"iVecCoords");b.__glProgram_Simple.GLSLiTexCoords=c.getAttribLocation(b.__glProgram_Simple,"iTexCoords");b.__glProgram_Simple.GLSLuProjMat=c.getUniformLocation(b.__glProgram_Simple,"uProjMat");b.__glProgram_Simple.GLSLuMVMat=c.getUniformLocation(b.__glProgram_Simple,"uMVMat");b.__glProgram_Simple.GLSLuSprSize=c.getUniformLocation(b.__glProgram_Simple,"uSprSize");b.__glProgram_Simple.GLSLuSprFrame=c.getUniformLocation(b.__glProgram_Simple,"uSprFrame");b.__glProgram_Simple.GLSLuSprFlip=c.getUniformLocation(b.__glProgram_Simple,
"uSprFlip");b.__glProgram_Simple.GLSLuSampler=c.getUniformLocation(b.__glProgram_Simple,"uSampler");c.enableVertexAttribArray(b.__glProgram_Simple.GLSLiVecCoords);c.enableVertexAttribArray(b.__glProgram_Simple.GLSLiTexCoords);c.uniform1i(b.__glProgram_Simple.GLSLuSampler,0);b.__modelViewMatrix.update(c,b.__glProgram_Simple.GLSLuMVMat);b.__projectionMatrix.update(c,b.__glProgram_Simple.GLSLuProjMat);b.__glProgram_SimpleWithAlpha=b.__PRIVATE__.makeProgram(c,b.__vertex_shader_Common,b.__fragment_shader_SimpleWithAlpha);
c.useProgram(b.__glProgram_SimpleWithAlpha);b.__glProgram_SimpleWithAlpha.GLSLiVecCoords=c.getAttribLocation(b.__glProgram_SimpleWithAlpha,"iVecCoords");b.__glProgram_SimpleWithAlpha.GLSLiTexCoords=c.getAttribLocation(b.__glProgram_SimpleWithAlpha,"iTexCoords");b.__glProgram_SimpleWithAlpha.GLSLuProjMat=c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uProjMat");b.__glProgram_SimpleWithAlpha.GLSLuMVMat=c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uMVMat");b.__glProgram_SimpleWithAlpha.GLSLuSprSize=
c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uSprSize");b.__glProgram_SimpleWithAlpha.GLSLuSprFrame=c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uSprFrame");b.__glProgram_SimpleWithAlpha.GLSLuSprFlip=c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uSprFlip");b.__glProgram_SimpleWithAlpha.GLSLuSampler=c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uSampler");b.__glProgram_SimpleWithAlpha.GLSLuAlpha=c.getUniformLocation(b.__glProgram_SimpleWithAlpha,"uAlpha");c.enableVertexAttribArray(b.__glProgram_SimpleWithAlpha.GLSLiVecCoords);
c.enableVertexAttribArray(b.__glProgram_SimpleWithAlpha.GLSLiTexCoords);c.uniform1i(b.__glProgram_SimpleWithAlpha.GLSLuSampler,0);b.__modelViewMatrix.update(c,b.__glProgram_SimpleWithAlpha.GLSLuMVMat);b.__projectionMatrix.update(c,b.__glProgram_SimpleWithAlpha.GLSLuProjMat);b.__glProgram_SaturationWithAlpha=b.__PRIVATE__.makeProgram(c,b.__vertex_shader_Common,b.__fragment_shader_SaturationWithAlpha);c.useProgram(b.__glProgram_SaturationWithAlpha);b.__glProgram_SaturationWithAlpha.GLSLiVecCoords=c.getAttribLocation(b.__glProgram_SaturationWithAlpha,
"iVecCoords");b.__glProgram_SaturationWithAlpha.GLSLiTexCoords=c.getAttribLocation(b.__glProgram_SaturationWithAlpha,"iTexCoords");b.__glProgram_SaturationWithAlpha.GLSLuProjMat=c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uProjMat");b.__glProgram_SaturationWithAlpha.GLSLuMVMat=c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uMVMat");b.__glProgram_SaturationWithAlpha.GLSLuSprSize=c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uSprSize");b.__glProgram_SaturationWithAlpha.GLSLuSprFrame=
c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uSprFrame");b.__glProgram_SaturationWithAlpha.GLSLuSprFlip=c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uSprFlip");b.__glProgram_SaturationWithAlpha.GLSLuSampler=c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uSampler");b.__glProgram_SaturationWithAlpha.GLSLuColor=c.getUniformLocation(b.__glProgram_SaturationWithAlpha,"uColor");c.enableVertexAttribArray(b.__glProgram_SaturationWithAlpha.GLSLiVecCoords);c.enableVertexAttribArray(b.__glProgram_SaturationWithAlpha.GLSLiTexCoords);
c.uniform1i(b.__glProgram_SaturationWithAlpha.GLSLuSampler,0);b.__modelViewMatrix.update(c,b.__glProgram_SaturationWithAlpha.GLSLuMVMat);b.__projectionMatrix.update(c,b.__glProgram_SaturationWithAlpha.GLSLuProjMat);b.__glProgram=b.__glProgram_Simple;c.useProgram(b.__glProgram);b.__root.prepare(b)};this.__PRIVATE__.makeProgram=function(b,a,f){var h=b.createShader(b.VERTEX_SHADER),e=b.createShader(b.FRAGMENT_SHADER);b.shaderSource(h,a);b.shaderSource(e,f);b.compileShader(h);b.compileShader(e);a=b.createProgram();
b.attachShader(a,h);b.attachShader(a,e);b.linkProgram(a);return a};this.__PRIVATE__.loadResources=function(){for(var c,a,f=0,h=b.__imageSymbols.size();f<h;f++){c=b.__imageSymbols[f];if(b.__view_width&&b.__view_height)for(var e=c.viewOptimalWidth*b.__view_scale*window.devicePixelRatio,d=c.viewOptimalHeight*b.__view_scale*window.devicePixelRatio,g=0;g<c.viewSiblings.size();g++)if(a=c.viewSiblings[g],a.textureWidth>=e&&a.textureHeight>=d){c.image=new Image;c.image.load(c.baseUrl+a.url);c.textureCellWidth=
a.textureWidth;c.textureCellHeight=a.textureHeight;c.pixelRatio=a.pixelRatio;break}c.image||(a=c.viewSiblings[c.viewSiblings.size()-1],c.image=new Image,c.image.load(c.baseUrl+a.url),c.textureCellWidth=a.textureWidth,c.textureCellHeight=a.textureHeight,c.pixelRatio=a.pixelRatio);c.image&&trace("Loaded image: "+c.image.src)}};this.__PRIVATE__.resourcesLoaded=function(c){if(!b.__ready){for(var a,f=b.__imageSymbols.size()-1;0<=f;f--){a=b.__imageSymbols[f];if(!a.image||!a.image.width||!a.image.height)return!1;
if(!a.texture)return a.prepare(b,c),!1}b.__ready=!0;trace("Resources loaded.");return!1}return b.__ready};this.paint=function(c,a){if(!b.__glProgram)b.__PRIVATE__.prepare(c),b.__PRIVATE__.loadResources();else if(b.__PRIVATE__.resourcesLoaded(c)&&b.__root){b.__modelViewMatrix.identity();b.__levelParents=[b.__root];b.__root.paint(c,b,null,!1,0);b.__levelParents=[];var f=b.__root.__childWithMaxTimelineDuration;f&&f.__currentFrame&&f.__currentFrame.frameIndex==f.__timeline.lastKeyFrame().frameIndex&&
(b.__finished=!0)}};this.__PRIVATE__.setFilter=function(c){var a=!1;switch(c){case COCO_FILTER_ENUM.FILTER_INHERIT:b.__glProgram!=b.__glProgram_Simple&&(b.__glProgram=b.__glProgram_Simple,a=!0);break;case COCO_FILTER_ENUM.FILTER_SIMPLE:b.__glProgram!=b.__glProgram_Simple&&(b.__glProgram=b.__glProgram_Simple,a=!0);break;case COCO_FILTER_ENUM.FILTER_SIMPLE_WITH_ALPHA:b.__glProgram!=b.__glProgram_SimpleWithAlpha&&(b.__glProgram=b.__glProgram_SimpleWithAlpha,a=!0);break;case COCO_FILTER_ENUM.FILTER_SATURATION_WITH_ALPHA:b.__glProgram!=
b.__glProgram_SaturationWithAlpha&&(b.__glProgram=b.__glProgram_SaturationWithAlpha,a=!0)}a&&gl.useProgram(b.__glProgram);return a};this.drawFrame=function(c,a,f,h){(b.__PRIVATE__.setFilter(h.filter)||b.__modelViewMatrix.__dirty)&&b.__modelViewMatrix.update(c,b.__glProgram.GLSLuMVMat);c.uniform2f(b.__glProgram.GLSLuSprSize,a.texSize[0],a.texSize[1]);c.uniform2f(b.__glProgram.GLSLuSprFrame,a.textureGrid[2*f+1],a.textureGrid[2*f]);c.uniform2f(b.__glProgram.GLSLuSprFlip,h.flipH?1:0,h.flipV?1:0);c.bindBuffer(c.ARRAY_BUFFER,
a.buffer);c.vertexAttribPointer(b.__glProgram.GLSLiTexCoords,2,c.FLOAT,!1,16,0);c.vertexAttribPointer(b.__glProgram.GLSLiVecCoords,2,c.FLOAT,!1,16,8);c.bindTexture(c.TEXTURE_2D,a.texture);switch(h.filter){case COCO_FILTER_ENUM.FILTER_SIMPLE_WITH_ALPHA:c.uniform1f(b.__glProgram.GLSLuAlpha,h.alpha);break;case COCO_FILTER_ENUM.FILTER_SATURATION_WITH_ALPHA:c.uniform4f(b.__glProgram.GLSLuColor,h.red,h.green,h.blue,h.alpha)}c.drawArrays(c.TRIANGLE_STRIP,0,4);c.bindBuffer(c.ARRAY_BUFFER,null)};this.gotoAndPlayByName=
function(c){(0==b.__levelParents.size()?b.__root:b.__levelParents[b.__levelParents.size()-1]).gotoFrameByName(c,!1)};this.gotoAndStopByName=function(c){(0==b.__levelParents.size()?b.__root:b.__levelParents[b.__levelParents.size()-1]).gotoFrameByName(c,!0)};this.gotoAndPlayByIndex=function(c){(0==b.__levelParents.size()?b.__root:b.__levelParents[b.__levelParents.size()-1]).gotoFrameByIndex(c,!1)};this.gotoAndStopyByIndex=function(c){(0==b.__levelParents.size()?b.__root:b.__levelParents[b.__levelParents.size()-
1]).gotoFrameByIndex(c,!0)};this.stop=function(){(0==b.__levelParents.size()?b.__root:b.__levelParents[b.__levelParents.size()-1]).gotoFrameByIndex(COCO_STOP_ON_CURRENT_FRAME,!0)};this.__sceneName="";this.__imageSymbols=[];this.__view_scale=this.__view_pixel_ratio=this.__view_height=this.__view_width=this.__fps=0;this.__glProgram_SaturationWithAlpha=this.__glProgram_SimpleWithAlpha=this.__glProgram_Simple=this.__glProgram=this.__projectionMatrix=this.__modelViewMatrix=this.__root=null;this.__levelParents=
[];this.__boundingBoxFragmentShader=this.__boundingBoxVertexShader=this.__fragment_shader_SaturationWithAlpha=this.__fragment_shader_SimpleWithAlpha=this.__fragment_shader_Simple=this.__vertex_shader_Common="";this.__boundingBoxBuffer=this.__boundingBoxProgram=null;this.__finished=this.__ready=!1;this.Destructor=function(){b.__root&&(b.__root.hasOwnProperty("Destructor")&&b.__root.Destructor()||!b.__root.hasOwnProperty("Destructor"))&&delete b.__root;b.__root=null;b.__modelViewMatrix&&(b.__modelViewMatrix.hasOwnProperty("Destructor")&&
b.__modelViewMatrix.Destructor()||!b.__modelViewMatrix.hasOwnProperty("Destructor"))&&delete b.__modelViewMatrix;b.__modelViewMatrix=null;b.__projectionMatrix&&(b.__projectionMatrix.hasOwnProperty("Destructor")&&b.__projectionMatrix.Destructor()||!b.__projectionMatrix.hasOwnProperty("Destructor"))&&delete b.__projectionMatrix;b.__projectionMatrix=null;b.__glProgram_Simple&&(b.__glProgram_Simple.hasOwnProperty("Destructor")&&b.__glProgram_Simple.Destructor()||!b.__glProgram_Simple.hasOwnProperty("Destructor"))&&
delete b.__glProgram_Simple;b.__glProgram_Simple=null;b.__glProgram_SimpleWithAlpha&&(b.__glProgram_SimpleWithAlpha.hasOwnProperty("Destructor")&&b.__glProgram_SimpleWithAlpha.Destructor()||!b.__glProgram_SimpleWithAlpha.hasOwnProperty("Destructor"))&&delete b.__glProgram_SimpleWithAlpha;b.__glProgram_SimpleWithAlpha=null;b.__glProgram_SaturationWithAlpha&&(b.__glProgram_SaturationWithAlpha.hasOwnProperty("Destructor")&&b.__glProgram_SaturationWithAlpha.Destructor()||!b.__glProgram_SaturationWithAlpha.hasOwnProperty("Destructor"))&&
delete b.__glProgram_SaturationWithAlpha;b.__glProgram_SaturationWithAlpha=null;b.__boundingBoxProgram&&(b.__boundingBoxProgram.hasOwnProperty("Destructor")&&b.__boundingBoxProgram.Destructor()||!b.__boundingBoxProgram.hasOwnProperty("Destructor"))&&delete b.__boundingBoxProgram;b.__boundingBoxProgram=null;b.__boundingBoxBuffer&&(b.__boundingBoxBuffer.hasOwnProperty("Destructor")&&b.__boundingBoxBuffer.Destructor()||!b.__boundingBoxBuffer.hasOwnProperty("Destructor"))&&delete b.__boundingBoxBuffer;
b.__boundingBoxBuffer=null;for(var c=b.__imageSymbols.size();c--;)delete b.__imageSymbols[c];(function(a){if(a)for(var b=a.length;b--;)a[b]&&(a[b].hasOwnProperty("Destructor")&&a[b].Destructor()||!a[b].hasOwnProperty("Destructor"))&&delete a[b],a[b]=null})(b.__imageSymbols);b.__imageSymbols&&(b.__imageSymbols.hasOwnProperty("Destructor")&&b.__imageSymbols.Destructor()||!b.__imageSymbols.hasOwnProperty("Destructor"))&&delete b.__imageSymbols;b.__imageSymbols=null;(function(a){if(a)for(var b=a.length;b--;)a[b]&&
(a[b].hasOwnProperty("Destructor")&&a[b].Destructor()||!a[b].hasOwnProperty("Destructor"))&&delete a[b],a[b]=null})(b.__levelParents);b.__levelParents&&(b.__levelParents.hasOwnProperty("Destructor")&&b.__levelParents.Destructor()||!b.__levelParents.hasOwnProperty("Destructor"))&&delete b.__levelParents;b.__levelParents=null;b.__sceneName=null;b.__imageSymbols=null;b.__fps=null;b.__view_width=null;b.__view_height=null;b.__view_pixel_ratio=null;b.__view_scale=null;b.__root=null;b.__modelViewMatrix=
null;b.__projectionMatrix=null;b.__glProgram=null;b.__glProgram_Simple=null;b.__glProgram_SimpleWithAlpha=null;b.__glProgram_SaturationWithAlpha=null;b.__levelParents=null;b.__vertex_shader_Common=null;b.__fragment_shader_Simple=null;b.__fragment_shader_SimpleWithAlpha=null;b.__fragment_shader_SaturationWithAlpha=null;b.__boundingBoxVertexShader=null;b.__boundingBoxFragmentShader=null;b.__boundingBoxProgram=null;b.__boundingBoxBuffer=null;b.__ready=null;c=b.__finished=null;return!0};this.Constructor=
function(){b.__sceneName="";b.__view_width=0;b.__view_height=0;b.__view_pixel_ratio=0;b.__view_scale=1;b.__root=null;b.__modelViewMatrix=new CocoMatrix;b.__projectionMatrix=new CocoMatrix;b.__glProgram=null;b.__glProgram_Simple=null;b.__glProgram_SimpleWithAlpha=null;b.__glProgram_SaturationWithAlpha=null;b.__vertex_shader_Common="attribute vec2 iVecCoords;attribute vec2 iTexCoords;uniform mat4 uProjMat;uniform mat4 uMVMat;uniform vec2 uSprSize;uniform vec2 uSprFrame;uniform vec2 uSprFlip;varying vec2 pTexCoord;void main(void){ gl_Position = uProjMat * uMVMat * vec4(iVecCoords, 0.0, 1.0); pTexCoord = vec2(((abs(iTexCoords.x - uSprFlip.x) + uSprFrame.x) * uSprSize.x), ((abs(iTexCoords.y - uSprFlip.y) + uSprFrame.y) * uSprSize.y));}";
b.__fragment_shader_Simple="#ifdef GL_ES\nprecision lowp float;\n#endif\nuniform sampler2D uSampler;\nvarying vec2 pTexCoord; \n \nvoid main(void)\n{\n gl_FragColor = texture2D(uSampler, pTexCoord); }";b.__fragment_shader_SimpleWithAlpha="#ifdef GL_ES\nprecision lowp float;\n#endif\nuniform sampler2D uSampler;\nuniform float uAlpha;\nvarying vec2 pTexCoord; \n \nvoid main(void)\n{\n vec4 texColor = texture2D(uSampler, pTexCoord);\n gl_FragColor = vec4(texColor.rgb, texColor.a * uAlpha); }";b.__fragment_shader_SaturationWithAlpha=
"#ifdef GL_ES\nprecision lowp float;\n#endif\nuniform sampler2D uSampler;\nuniform vec4 uColor;\nvarying vec2 pTexCoord; \n \nvoid main(void)\n{\n vec4 texColor = texture2D(uSampler, pTexCoord);\n float c = (texColor.r + texColor.g + texColor.b) / 3.0; \n gl_FragColor = vec4((1.0 - uColor.r) * c + texColor.r * uColor.r, (1.0 - uColor.g) * c + texColor.g * uColor.g, (1.0 - uColor.b) * c + texColor.b * uColor.b, texColor.a * uColor.a);}";b.__boundingBoxVertexShader="attribute vec2 iVec2Coords;uniform mat4 uProjMat;void main(void) { gl_Position = uProjMat * vec4(iVec2Coords, 0.0, 1.0);}";
b.__boundingBoxFragmentShader="#ifdef GL_ES\nprecision lowp float;\n#endif\nvoid main(void) { gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);}";b.__boundingBoxProgram=null;b.__boundingBoxBuffer=null;b.__ready=!1;b.__finished=!1;b.__imageSymbols=[];b.__levelParents=[]};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}(null)}CocoScene.prototype={};CocoScene.prototype.__PRIVATE__={};CocoScene.prototype.__PROTECTED__={};
function CocoSequence(g,b){return new function(b,a,f){var h=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.name="";this.frames=[];this.sequenceStartTime=null;this.Destructor=function(){h.frames&&(h.frames.hasOwnProperty("Destructor")&&h.frames.Destructor()||!h.frames.hasOwnProperty("Destructor"))&&delete h.frames;h.frames=null;h.name=null;h.frames=
null;h.sequenceStartTime=null;return!0};this.Constructor=function(a,b){h.name=a;h.frames=b;h.sequenceStartTime=0};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(a,f);return this}(null,g,b)}CocoSequence.prototype={};CocoSequence.prototype.__PRIVATE__={};CocoSequence.prototype.__PROTECTED__={};
function CocoTextStyle(g,b,c,a,f,h,e,d,y,k,q,p,m){return new function(a,b,c,d,e,f,h,g,k,m,p,n,y,q){var l=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.fontFamily="";this.fontSizePixels=0;this.fontWeight=this.fontStyle="";this.underline=!1;this.color=[];this.bgcolor=[];this.Destructor=function(){l.color&&(l.color.hasOwnProperty("Destructor")&&l.color.Destructor()||
!l.color.hasOwnProperty("Destructor"))&&delete l.color;l.color=null;l.bgcolor&&(l.bgcolor.hasOwnProperty("Destructor")&&l.bgcolor.Destructor()||!l.bgcolor.hasOwnProperty("Destructor"))&&delete l.bgcolor;l.bgcolor=null;l.fontFamily=null;l.fontSizePixels=null;l.fontStyle=null;l.fontWeight=null;l.underline=null;l.color=null;l.bgcolor=null;return!0};this.Constructor=function(a,b,c,d,e,f,h,g,k,m,n,p,y){l.fontFamily=a;l.fontSizePixels=b;l.fontStyle=c;l.fontWeight=d;l.underline=e;l.color=[];l.color.push(f);
l.color.push(h);l.color.push(g);l.color.push(k);l.bgcolor=[];l.bgcolor.push(m);l.bgcolor.push(n);l.bgcolor.push(p);l.bgcolor.push(y)};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(b,c,d,e,f,h,g,k,m,p,n,y,q);return this}(null,g,b,c,a,f,h,e,d,y,k,q,p,m)}CocoTextStyle.prototype={};CocoTextStyle.prototype.__PRIVATE__={};CocoTextStyle.prototype.__PROTECTED__={};
function CocoText(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.wrap=function(c){b.lineBreaks.clear();b.lineWidths.clear();b.lineHeights.clear();for(var a=b.totalHeight=0,f=0,h=0;h<b.indices.size();h++){var e=b.styles[b.mappings[h]],f=Math.max(f,e.fontSizePixels);CocoText.prototype.c2d.font=e.fontStyle+" normal "+
e.fontWeight+" "+e.fontSizePixels+"px "+e.fontFamily;for(var d=h+1<b.indices.size()?b.indices[h+1]:b.str.size(),g=b.indices[h];g<d;g++){var k=CocoText.prototype.c2d.measureText(b.str.substr(g,1)).width;if(a+k>c){if(0==a)throw"Too small width!";b.lineBreaks.push(g);b.lineWidths.push(a);b.lineHeights.push(f);b.totalHeight+=f;a=k;f=e.fontSizePixels}else a+=k}}b.lineWidths.push(a);b.lineHeights.push(f);b.totalHeight+=f};this.draw=function(c,a,f,h,e,d,g,k){trace("CocoText::draw");if(c>CocoText.prototype.c2d.canvas.width||
a>CocoText.prototype.c2d.canvas.height)return"";CocoText.prototype.c2d.clearRect(0,0,c,a);CocoText.prototype.c2d.fillStyle="rgba("+e+", "+d+", "+g+", "+k+")";k=g=d=e=0;for(var q=!0,p=0;p<b.indices.size();p++){var m=b.styles[b.mappings[p]];CocoText.prototype.c2d.font=m.fontStyle+" normal "+m.fontWeight+" "+m.fontSizePixels+"px "+m.fontFamily;trace("CocoText::draw 1");var r=0,v=p+1<b.indices.size()?b.indices[p+1]:b.str.size();trace("CocoText::draw 2");do{trace("CocoText::draw 3");var w=g<b.lineBreaks.size()?
b.lineBreaks[g]:b.str.size();trace("CocoText::draw 4");var r=Math.min(v,w),x=b.str.substring(k,r);trace("CocoText::draw 5");q&&(q=!1);k=r;var u=CocoText.prototype.c2d.measureText(x).width;trace("CocoText::draw 5 1");var s=(c-b.lineWidths[g])*f;trace("CocoText::draw 5 2");var t=b.lineHeights[g]/1.125+(a-1.25*b.totalHeight)*h;trace("CocoText::draw 5 3");CocoText.prototype.c2d.fillStyle="rgba("+m.bgcolor[0]+", "+m.bgcolor[1]+", "+m.bgcolor[2]+", "+m.bgcolor[3]+")";trace("CocoText::draw 5 4");CocoText.prototype.c2d.fillRect(e+
s,d+t-m.fontSizePixels/1.25,u,1.125*m.fontSizePixels);trace("CocoText::draw 5 5");var z="rgba("+m.color[0]+", "+m.color[1]+", "+m.color[2]+", "+m.color[3]+")";trace("CocoText::draw 5 6");CocoText.prototype.c2d.fillStyle=z;trace("CocoText::draw 5 7");CocoText.prototype.c2d.strokeStyle=z;trace("CocoText::draw 5 8");trace("CocoText::draw 6");CocoText.prototype.c2d.fillText(x,e+s,d+t);trace("CocoText::draw 7");m.underline&&(CocoText.prototype.c2d.lineWidth=m.fontSizePixels/12,CocoText.prototype.c2d.beginPath(),
CocoText.prototype.c2d.moveTo(e+s,d+t+1.5*CocoText.prototype.c2d.lineWidth),CocoText.prototype.c2d.lineTo(e+s+u,d+t+1.5*CocoText.prototype.c2d.lineWidth),CocoText.prototype.c2d.stroke());trace("CocoText::draw 8");e+=u;r==w&&(e=0,d+=1.25*b.lineHeights[g],++g,q=!0);trace("CocoText::draw 9")}while(r!=v)}return CocoText.prototype.c2d.canvas.toDataURL()};this.str="";this.styles=[];this.indices=[];this.mappings=[];this.lineBreaks=[];this.lineWidths=[];this.lineHeights=[];this.totalHeight=0;this.Destructor=
function(){var c=b.styles;if(c)for(var a=c.length;a--;)c[a]&&(c[a].hasOwnProperty("Destructor")&&c[a].Destructor()||!c[a].hasOwnProperty("Destructor"))&&delete c[a],c[a]=null;b.styles&&(b.styles.hasOwnProperty("Destructor")&&b.styles.Destructor()||!b.styles.hasOwnProperty("Destructor"))&&delete b.styles;b.styles=null;b.indices&&(b.indices.hasOwnProperty("Destructor")&&b.indices.Destructor()||!b.indices.hasOwnProperty("Destructor"))&&delete b.indices;b.indices=null;b.mappings&&(b.mappings.hasOwnProperty("Destructor")&&
b.mappings.Destructor()||!b.mappings.hasOwnProperty("Destructor"))&&delete b.mappings;b.mappings=null;b.lineBreaks&&(b.lineBreaks.hasOwnProperty("Destructor")&&b.lineBreaks.Destructor()||!b.lineBreaks.hasOwnProperty("Destructor"))&&delete b.lineBreaks;b.lineBreaks=null;b.lineWidths&&(b.lineWidths.hasOwnProperty("Destructor")&&b.lineWidths.Destructor()||!b.lineWidths.hasOwnProperty("Destructor"))&&delete b.lineWidths;b.lineWidths=null;b.lineHeights&&(b.lineHeights.hasOwnProperty("Destructor")&&b.lineHeights.Destructor()||
!b.lineHeights.hasOwnProperty("Destructor"))&&delete b.lineHeights;b.lineHeights=null;b.c2d=null;b.str=null;b.styles=null;b.indices=null;b.mappings=null;b.lineBreaks=null;b.lineWidths=null;b.lineHeights=null;b.totalHeight=null;return!0};this.Constructor=function(){b.styles=[];b.indices=[];b.mappings=[];b.lineBreaks=[];b.lineWidths=[];b.lineHeights=[];b.totalHeight=0};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}(null)}CocoText.prototype={};
CocoText.prototype.__PRIVATE__={};CocoText.prototype.__PROTECTED__={};CocoText.prototype.npo2=function(g){--g;g|=g>>1;g|=g>>2;g|=g>>4;g|=g>>8;g|=g>>16;return++g};CocoText.prototype.init=function(g,b){var c=document.createElement("canvas");c.width=CocoText.prototype.npo2(g);c.height=CocoText.prototype.npo2(b);CocoText.prototype.c2d=c.getContext("2d")};CocoText.prototype.c2d=null;
function CocoTimeLabel(g,b){return new function(b,a,f){var h=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.frameIndex=0;this.name="";this.Destructor=function(){h.frameIndex=null;h.name=null;return!0};this.Constructor=function(a,b){h.frameIndex=a;h.name=b};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor(a,f);return this}(null,g,b)}
CocoTimeLabel.prototype={};CocoTimeLabel.prototype.__PRIVATE__={};CocoTimeLabel.prototype.__PROTECTED__={};
function CocoTimeline(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.prepare=function(c,a){b.__fps=c.__fps;b.normalizetimeline()};this.clear=function(){b.reset();(function(b){if(b)for(var a=b.length;a--;)b[a]&&(b[a].hasOwnProperty("Destructor")&&b[a].Destructor()||!b[a].hasOwnProperty("Destructor"))&&delete b[a],b[a]=
null})(b.__labels);b.__labels&&(b.__labels.hasOwnProperty("Destructor")&&b.__labels.Destructor()||!b.__labels.hasOwnProperty("Destructor"))&&delete b.__labels;b.__labels=null;(function(b){if(b)for(var a=b.length;a--;)b[a]&&(b[a].hasOwnProperty("Destructor")&&b[a].Destructor()||!b[a].hasOwnProperty("Destructor"))&&delete b[a],b[a]=null})(b.__keyFrames);b.__keyFrames&&(b.__keyFrames.hasOwnProperty("Destructor")&&b.__keyFrames.Destructor()||!b.__keyFrames.hasOwnProperty("Destructor"))&&delete b.__keyFrames;
b.__keyFrames=null;b.__labels=[];b.__keyFrames=[];b.normalizetimeline()};this.reset=function(){b.__paused=!1;b.__currentFrameIndex=-1;for(var c=b.__keyFrames.size()-1;0<=c;c--)b.__keyFrames[c].reset()};this.addLabel=function(c){c&&b.__labels.push(c);return c};this.addLabelEx=function(c,a){var f=new CocoTimeLabel(c,a);return b.addLabel(f)};this.findLabelByName=function(c){for(var a=b.__labels.size()-1;0<=a;a--)if(b.__labels[a].name==c)return b.__labels[a];return null};this.keyFrame=function(c){for(var a=
b.__keyFrames.size()-1;0<=a;a--)if(b.__keyFrames[a].frameIndex==c)return b.__keyFrames[a];return null};this.firstKeyFrame=function(){return b.__keyFrames[0]};this.lastKeyFrame=function(){return b.__keyFrames[b.__keyFrames.size()-1]};this.addKeyFrame=function(c){c&&(c.frameIndex=Math.floor(c.frameIndex),b.__keyFrames.push(c),b.normalizetimeline());return c};this.addKeyFrameEx=function(c,a,f,h,e,d,g,k,q,p,m,r,v,w,x,u,s,t,z,A,B,C){var n=new CocoKeyFrame;n.nextState=c;n.action=a;n.frameIndex=f;n.frameInterpolation=
h;n.handleEvents=e;n.visible=d;n.filter=w;n.x=g;n.y=k;n.scaleX=q;n.scaleY=p;n.rotation=m;n.pivotX=r;n.pivotY=v;n.red=x;n.green=u;n.blue=s;n.alpha=t;n.audio=z;n.flipH=A;n.flipV=B;n.spriteSequenceName=C;return b.addKeyFrame(n)};this.normalizetimeline=function(){b.__durationInFrames=0;b.__durationInTime=0;b.__singleFrameDurationTime=0;0<b.__keyFrames.size()&&(b.__durationInFrames=b.__keyFrames[b.__keyFrames.size()-1].frameIndex+1,b.__singleFrameDurationTime=1E3/b.__fps,b.__durationInTime=b.__durationInFrames*
b.__singleFrameDurationTime,b.__firstKeyFrameIndex=b.firstKeyFrame().frameIndex,b.__lastKeyFrameIndex=b.lastKeyFrame().frameIndex)};this.findKeyFrameBeforeframeIndex=function(c,a,f){for(var h,e=b.__keyFrames.size()-1;0<=e;e--)if(e!=f)if(h=b.__keyFrames[e],a){if(h.frameIndex<=c)return h}else if(h.frameIndex<c)return h;return null};this.findKeyFrameAfterframeIndex=function(c,a,f){for(var h,e=0,d=b.__keyFrames.size();e<d;e++)if(e!=f)if(h=b.__keyFrames[e],a){if(h.frameIndex>=c)return h}else if(h.frameIndex>
c)return h;return null};this.interpolate=function(c){var a=null,f=null,h=null,e=1;0>=c&&(c=0);e=Math.floor(c);if(0==b.__keyFrames.size())return a=new CocoKeyFrame,a.frameIndex=e,a.visible=!1,a;if(f=b.findKeyFrameBeforeframeIndex(c,!0,-1)){a=!b.__paused&&(-1==b.__currentFrameIndex||b.__currentFrameIndex!=f.frameIndex);b.__currentFrameIndex=f.frameIndex;if(f.frameIndex==e)return f=f.clone(a),f.__frameIndex=c,f;switch(f.frameInterpolation){case COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_ECHO:return a=
f.clone(a),a.frameIndex=e,a.__frameIndex=c,a;case COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_NONE:return a=f.clone(a),a.frameIndex=e,a.__frameIndex=c,a.visible=!1,a;case COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN:return(h=b.findKeyFrameAfterframeIndex(c,c>e,-1))?(a=f.clone(a),a.frameIndex=e,a.__frameIndex=c,e=(c-f.frameIndex)/(h.frameIndex-f.frameIndex),a.interpolate(f,h,e)):(a=f.clone(a),a.frameIndex=e,a.__frameIndex=c),a}}else return a=new CocoKeyFrame,a.frameIndex=
e,a.__frameIndex=c,a.visible=!1,a;return null};this.__labels=[];this.__keyFrames=[];this.__durationInTime=this.__singleFrameDurationTime=null;this.__durationInFrames=0;this.__paused=!1;this.__lastKeyFrameIndex=this.__firstKeyFrameIndex=this.__currentFrameIndex=this.__fps=0;this.Destructor=function(){(function(b){if(b)for(var a=b.length;a--;)b[a]&&(b[a].hasOwnProperty("Destructor")&&b[a].Destructor()||!b[a].hasOwnProperty("Destructor"))&&delete b[a],b[a]=null})(b.__labels);b.__labels&&(b.__labels.hasOwnProperty("Destructor")&&
b.__labels.Destructor()||!b.__labels.hasOwnProperty("Destructor"))&&delete b.__labels;b.__labels=null;(function(b){if(b)for(var a=b.length;a--;)b[a]&&(b[a].hasOwnProperty("Destructor")&&b[a].Destructor()||!b[a].hasOwnProperty("Destructor"))&&delete b[a],b[a]=null})(b.__keyFrames);b.__keyFrames&&(b.__keyFrames.hasOwnProperty("Destructor")&&b.__keyFrames.Destructor()||!b.__keyFrames.hasOwnProperty("Destructor"))&&delete b.__keyFrames;b.__keyFrames=null;b.__labels=null;b.__keyFrames=null;b.__singleFrameDurationTime=
null;b.__durationInTime=null;b.__durationInFrames=null;b.__paused=null;b.__fps=null;b.__currentFrameIndex=null;b.__firstKeyFrameIndex=null;b.__lastKeyFrameIndex=null;return!0};this.Constructor=function(){b.__labels=[];b.__keyFrames=[];b.__singleFrameDurationTime=0;b.__durationInTime=0;b.__durationInFrames=0;b.__paused=!1;b.__fps=30;b.__currentFrameIndex=-1};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}(null)}CocoTimeline.prototype={};
CocoTimeline.prototype.__PRIVATE__={};CocoTimeline.prototype.__PROTECTED__={};
function CocoVector(){return new function(g){var b=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.reset=function(c,a,f,h){b.X=c;b.Y=a;b.Z=f;b.W=h};this.W=this.Z=this.Y=this.X=0;this.Destructor=function(){b.X=null;b.Y=null;b.Z=null;b.W=null;return!0};this.Constructor=function(){b.X=0;b.Y=0;b.Z=0;b.W=1};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();
return this}(null)}CocoVector.prototype={};CocoVector.prototype.__PRIVATE__={};CocoVector.prototype.__PROTECTED__={};
function GameEngine(){function g(b){var a=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.__SUPER__={};this.__BASE__=b;this.scene=null;this.STATE_GAME=function(){this.__name="STATE_GAME";this.enter=function(){a.scene=new NewAnimation};this.exit=function(){a.scene&&(a.scene.hasOwnProperty("Destructor")&&a.scene.Destructor()||!a.scene.hasOwnProperty("Destructor"))&&
delete a.scene;a.scene=null};this.tick=function(a){};this.paint=function(b,c){a.scene.paint(b,c)};return this}.call(new State);this.Destructor=function(){a.scene=null;a.STATE_GAME=null;b&&(b.hasOwnProperty("Destructor")&&b.Destructor()||!b.hasOwnProperty("Destructor"))&&delete b;return!0};this.Constructor=function(){a.__BASE__.setNextState(a.STATE_GAME)};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();return this}var b=null,b=new CocoEngine;g.prototype=b;return new g(b)}
GameEngine.prototype={};GameEngine.prototype.__PRIVATE__={};GameEngine.prototype.__PROTECTED__={};
function NewAnimation(){function g(b){var a=this;__PDEFINE__=Object.defineProperty;__NOENUM__={enumerable:!1};this.__PRIVATE__={};this.__PROTECTED__={};__PDEFINE__(this,"__PROTECTED__",__NOENUM__);__PDEFINE__(this,"__PRIVATE__",__NOENUM__);this.__SUPER__={};this.__BASE__=b;this.Destructor=function(){b&&(b.hasOwnProperty("Destructor")&&b.Destructor()||!b.hasOwnProperty("Destructor"))&&delete b;return!0};this.Constructor=function(){a.__BASE__.__sceneName="NewAnimation";a.__BASE__.__fps=30;a.__BASE__.__view_width=
480;a.__BASE__.__view_height=320;a.__BASE__.__view_pixel_ratio=1;var b=a.__BASE__.newResourceImage("SpriteSymbol_metal_slug","./assets/images/");b.viewOptimalWidth=36;b.viewOptimalHeight=42;b.addSibling(new CocoImageSibling("metal_slug_mdpi.png",1,36,42));b.addSibling(new CocoImageSibling("metal_slug_xhdpi.png",2,72,84));b.textureCellWidth=36;b.textureCellHeight=42;b.textureGrid=new Float32Array([0,0,0,1,0,2,0,3,0,4,0,5,0,6,0,7,0,8]);b.addSequence(new CocoSequence("Walk",[0,1,2,3,4,5,6,7,8]));var c=
a.__BASE__.newResourceImage("SpriteSymbol_Sparrow","./assets/images/");c.viewOptimalWidth=48;c.viewOptimalHeight=48;c.addSibling(new CocoImageSibling("Sparrow.png",1,48,48));c.textureCellWidth=48;c.textureCellHeight=48;c.textureGrid=new Float32Array([0,0,0,1,0,2,0,3,0,4,0,5,0,6,0,7,1,0,1,1,1,2,1,3,1,4,1,5,1,6,1,7,2,0,2,1,2,2,2,3,2,4,2,5,2,6,2,7,3,0,3,1,3,2,3,3,3,4,3,5,3,6,3,7,4,0,4,1,4,2,4,3,4,4,4,5,4,6,4,7,5,0,5,1,5,2,5,3,5,4,5,5,5,6,5,7,6,0,6,1,6,2,6,3]);c.addSequence(new CocoSequence("Fly",[22,
23,24]));c.addSequence(new CocoSequence("Fire",[25,26,27,28,29,30,31,32,33,34,35]));c.addSequence(new CocoSequence("Die",[37,38,39,40,41,42,41,42,41,42]));c.addSequence(new CocoSequence("Eat",[0,44,44,45,45,46,46,47,47]));c.addSequence(new CocoSequence("Burb",[0,48,48,48,49,49,49,48,48,48,49,49,49,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51,50,51]));c.addSequence(new CocoSequence("Borred",[0,1,2,1,0]));c.addSequence(new CocoSequence("Jump",[10,11,12,13,
12,13,12,13,12,13,12,13,12,13,12,13,12,13]));c.addSequence(new CocoSequence("Walk",[3,4,5,6,7,8,9]));c.addSequence(new CocoSequence("Fall",[14,15]));c.addSequence(new CocoSequence("Happy",[16,17,18,19,20,21]));a.__BASE__.__root=new CocoClip;a.__BASE__.__root.__instanceName="root";a.__BASE__.__root.__scene=a;a.__BASE__.__root.__timeline.clear();a.__BASE__.__root.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,0,0,1,1,0,0,0,0,1,1,1,1,null,
!1,!1,"");var e=new CocoClip(null);e.__instanceName="metal_slug1";a.__BASE__.__root.addChild(e);e.__scene=a;e.__timeline.clear();e.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,-171.5,-59.5,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"Walk");e.__timeline.addKeyFrameEx(null,null,60,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,189.5,5.5,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"Walk");var d=new CocoClip(b);d.__instanceName=":: SpriteSymbol_metal_slug";
e.addChild(d);d.__scene=a;d.__timeline.clear();d.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,0,0,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"");e=new CocoClip(null);e.__instanceName="Sparrow1";a.__BASE__.__root.addChild(e);e.__scene=a;e.__timeline.clear();e.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,-167.5,54.5,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"Walk");e.__timeline.addKeyFrameEx(null,
null,60,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,193.5,119.5,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"Walk");d=new CocoClip(c);d.__instanceName=":: SpriteSymbol_Sparrow";e.addChild(d);d.__scene=a;d.__timeline.clear();d.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,0,0,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"");e=new CocoClip(null);e.__instanceName="metal_slug2";a.__BASE__.__root.addChild(e);e.__scene=a;e.__timeline.clear();
e.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,103.5,-67.5,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"");b=new CocoClip(b);b.__instanceName=":: SpriteSymbol_metal_slug";e.addChild(b);b.__scene=a;b.__timeline.clear();b.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,0,0,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"");b=new CocoClip(null);b.__instanceName="Sparrow2";a.__BASE__.__root.addChild(b);
b.__scene=a;b.__timeline.clear();b.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,105.5,45.5,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"");c=new CocoClip(c);c.__instanceName=":: SpriteSymbol_Sparrow";b.addChild(c);c.__scene=a;c.__timeline.clear();c.__timeline.addKeyFrameEx(null,null,0,COCO_KEYFRAME_INTERPOLATION_ENUM.KEYFRAME_INTERPOLATION_MOTION_TWEEN,!1,!0,0,0,1,1,0,0,0,0,1,1,1,1,null,!1,!1,"")};__PDEFINE__(this,"Constructor",__NOENUM__);this.Constructor();
return this}var b=null,b=new CocoScene;g.prototype=b;return new g(b)}NewAnimation.prototype={};NewAnimation.prototype.__PRIVATE__={};NewAnimation.prototype.__PROTECTED__={};
