@echo off

@echo Cleaning Android binaries ...
del .\bin\*.* /f /q
del .\obj\com\mobilefx\cocoengine\*.* /f /q

@echo Generating R.java and packaged resources ...
"D:\mobileFX\Common\Android\android-sdk\build-tools\19.0.1\aapt.exe" package -f -m -S ".\res" -J ".\src" -M ".\AndroidManifest.xml" -I "D:\mobileFX\Common\Android\android-sdk\platforms\android-10\android.jar"

@echo Compiling Java sources ...
"C:\Program Files (x86)\Java\jdk1.7.0_09\bin\javac.exe" -target 1.6 -source 1.6 -encoding UTF-8 -g:none -d ".\obj" -cp ".\src;D:\mobileFX\Common\Android\android-sdk\platforms\android-10\android.jar;.\obj" -bootclasspath ".\src;D:\mobileFX\Common\Android\android-sdk\platforms\android-10\android.jar;.\obj" -sourcepath ".\src" @sources.lst

@echo Converting classes to Dalvik bytecode ...
call "D:\mobileFX\Common\Android\android-sdk\build-tools\19.0.1\dx.bat" --dex --output=".\bin\classes.dex" ".\obj" ".\libs"

@echo Creating unsigned APK ...
"D:\mobileFX\Common\Android\android-sdk\build-tools\19.0.1\aapt.exe" package -f -M ".\AndroidManifest.xml" -S ".\res" -A ".\assets" -I "D:\mobileFX\Common\Android\android-sdk\platforms\android-10\android.jar" -F ".\bin\Coco.unsigned.apk" ".\bin"

@echo Signing APK ...
"C:\Program Files (x86)\Java\jdk1.7.0_09\bin\jarsigner.exe" -digestalg SHA1 -sigalg MD5withRSA -keystore ".\debug.keystore" -storepass password -keypass password -signedjar ".\bin\Coco.signed.apk" ".\bin\Coco.unsigned.apk" Coco

@echo Zip-aligning APK file ...
"D:\mobileFX\Common\Android\android-sdk\tools\zipalign.exe" -f 4 ".\bin\Coco.signed.apk" ".\bin\Coco.apk"
